### ISSUE TITLE
1.16.2 support

### ISSUE THREAD

**Issue by MeikelLP** [jellysquid3/Lithium#101]
I'd like to know if this is considered, and if yes, when?

**Comment by akiraveliara** [comment]
It is being worked on. According to Jelly "No ETA, but hopefully in the next few weeks"

**Comment by FlashyReese** [comment]
Please avoid using issue tracker to ask questions. Also you can take a look at https://github.com/jellysquid3/lithium-fabric/pull/97 for the time being.

**Comment by MeikelLP** [comment]
sorry I only looked at the issues not the PRs
