### ISSUE TITLE
Explosion destroying blocks outside the world crashes the game

### ISSUE THREAD

**Issue by Fallen-Breath** [jellysquid3/Lithium#104]
### Reproduction Steps

1. Create a default super flat world (to make sure there are always some blocks to be destroyed in explosion) in single player 
2. `/tp 29999983 ~ 29999983`
3. `/summon minecraft:creeper 29999983 ~ 29999983 {ExplosionRadius: 127b, ignited: 1b}`
4. The game crashes when the creeper explodes

### Crash Report File

https://paste.ubuntu.com/p/3R6jdM6VBy/

### Additional Information

The game won't crashes if the `ExplosionRadius` of the creeper is default value `3`. Looks like the explosion must be able to afftect blocks outside `3*10^8` in order to reproduce this bug but I'm not sure

Edited: Can reproduce the crash in vanilla, so probably it's an vanilla issue instead of lithium issue

#### Environment
- Minecraft 1.16.1
- Fabric Loader 0.9.1+build.205
- [lithium-fabric-mc1.16.1-0.5.1](https://github.com/jellysquid3/lithium-fabric/tree/mc1.16.1-0.5.1)

**Comment by LucilleTea** [comment]
I've confirmed the crash also occurs in the dev branch of Lithium, as of commit 202419e997d7227cf8899863da68700bd075b1fb (so, excluding the 1.16.2 port only).

**Comment by 2No2Name** [comment]
Does the same scenario also crash in vanilla?

**Comment by FlashyReese** [comment]
> Does the same scenario also crash in vanilla?

I can confirm it does crash in vanilla

**Comment by Earthcomputer** [comment]
Is there a bug report on the vanilla bug tracker for this issue?

**Comment by FlashyReese** [comment]
It might be cause by the [MC-56388](https://bugs.mojang.com/browse/MC-56388)

**Comment by Earthcomputer** [comment]
That one's not fixed though

**Comment by maityyy** [comment]
Does this bug happen when `mixin.world.chunk_access` is disabled?

**Comment by 2No2Name** [comment]
Probably yes, as it is already confirmed by 3 people that it also happens in vanilla

**Comment by James103** [comment]
Are you able to reproduce this with the following steps? 
1. `/tp 29999983 ~ 29999983`
2. `/summon minecraft:fireball ~ ~ ~ {ExplosionPower:127}`
3. Punch the newly spawned fireball in the direction of the world border.

**Comment by Zirvac** [comment]
The fireball make it crash too (vanilla, release 0.5.1 and 202419e997d7227cf8899863da68700bd075b1fb).

**Comment by 2No2Name** [comment]
Discord user Kroppeb#2845 created a private bugreport on bugs.mojang.com . As this is a vanilla issue we won't fix it.
