### ISSUE TITLE
Water will cause the game to freeze

### ISSUE THREAD

**Issue by ScarletVirus** [jellysquid3/Lithium#106]
Water will cause the game to freeze，In my game, a bucket of water is enough to make the game's TPS drop to 5. When I use the water to spawn the monster tower, the game's mspt will soar to 500-700 and most of the time will be stagnant.These problems do not occur when I am in vanilla.English is not my native language, most of the content is translated by Google, sorry，But it seems that I do not have this problem when using JVM parameters

**Comment by James103** [comment]
Do you know what setup you are using to add 500 mspt to the tick time for just 1 bucket of water?

**Comment by ScarletVirus** [comment]
No, I’m too exaggerated. A bucket of tiled water will make my tps become 10. When I use an 18-story monster spawning tower (one bucket of water per floor), the tps will reach 2-4. I’m sorry

**Comment by ScarletVirus** [comment]
Part of the reason may be that my computer is too old

**Comment by James103** [comment]
I'm only getting an overhead of 5 mspt at most (and oftentimes lower) with 10 floors with a bucket of water each. 
CPU: i5-9400F at 2.90 GHz

**Comment by ScarletVirus** [comment]
Maybe it's my problem, sorry

**Comment by mrpopot** [comment]
I have a 9 floor flushing based mob farm, when the farm is places the water buckets there is a small 1 ms or so uptick in mspt through my testing.

**Comment by ScarletVirus** [comment]
When I restarted the game, the problem disappeared

**Comment by 2No2Name** [comment]
Not reproducible and disappeared, so I will close the issue until the problem also appears for others
