### ISSUE TITLE
useOptimizedTickScheduler breaks tile tick suppression

### ISSUE THREAD

**Issue by silversquirl** [jellysquid3/Lithium#11]
"Tile tick suppression" refers to the vanilla behaviour of delaying execution of some tile ticks when more than 65536 ticks are scheduled. This can be used for wireless transmission of redstone signals, as shown in [this video by Xcom](https://youtu.be/1GWaZ5vEd3A). See [this world download](https://github.com/jellysquid3/Lithium/files/4022828/wireless.zip) for a test case showing this breakage.

**Comment by jellysquid3** [comment]
Thanks for the report. I've fixed this in fa758b8.
