### ISSUE TITLE
Lithium for MC 1.16.2 is causing Minecraft to crash on my end 

### ISSUE THREAD

**Issue by LOuroboros** [jellysquid3/Lithium#117]
### Reproduction Steps
I just downloaded Minecraft 1.16.2 from the Minecraft Launcher, booted it up once, installed Fabric and started to slowly update my mods list. I noticed the game crashed, because mods like Phosphor and Sodium haven't jumped to 1.16.2 yet, so I took them out. Then I noticed that even though all the mods I had are compatible with 1.16.2, one or more of them weren't working as the game wouldn't have crashed yet again otherwise.
I narrowed the culprit down to Lithium v0.5.1 for MC 1.16.2, as when I removed it, the game started to boot up again just fine.

### Crash Report File
Well, there isn't one that I can find in my Minecraft folder, but there's the launcher_log.txt file
https://pastebin.com/BXBw7caP

### Additional Information
I think it's already mentioned on the launcher's log, but the only other mods I'm using are:
[Blur](https://www.curseforge.com/minecraft/mc-mods/blur-fabric), [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api), [Logical Zoom](https://www.curseforge.com/minecraft/mc-mods/logical-zoom), [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu), [NoFog](https://www.curseforge.com/minecraft/mc-mods/nofog) and [Roughly Enough Items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items).

They all work correctly without Lithium. Throwing Lithium into the mix is what causes the crash.

**Comment by amnotbananaama** [comment]
You downloaded the wrong .jar file. You want <https://github.com/jellysquid3/lithium-fabric/releases/download/mc1.16.2-0.5.2/lithium-fabric-mc1.16.2-0.5.2.jar>

**Comment by LOuroboros** [comment]
> 
> 
> You downloaded the wrong .jar file. You want https://github.com/jellysquid3/lithium-fabric/releases/download/mc1.16.2-0.5.2/lithium-fabric-mc1.16.2-0.5.2.jar

Oh shoot, I didn't notice!

Yeah, the regular .jar works just fine. Thank you!
