### ISSUE TITLE
Lithium crashes MC if there's no config folder

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#12]
Lithium crashes Minecraft when there's no config folder in the instance folder (ex: .minecraft, MultiMC instances), the only way to fix the crash is by creating an empty folder named "config" in the instance folder.

[This is the crash log.](https://gist.github.com/joaoh1/37dd99c4afb9f3143d1370c3e65a5ceb)

**Comment by jellysquid3** [comment]
Doh! That's a bit of an oversight.
