### ISSUE TITLE
Primed TNT collision check being buggy (possibly overflow)

### ISSUE THREAD

**Issue by aria1th** [jellysquid3/Lithium#120]
### Expected Behavior
TNT is primed but it cancels momentum and collides with block so falls downward(with small momentum ahead grindstone)

### Actual Behavior
TNT momentum is not cancelled and glitch through blocks or even gets accerlated 

### Reproduction Steps
1. build tnt duping contraption. I used fallen's dustless tree farm, there is WDL : https://www.youtube.com/watch?v=6qTqvMMTbB0 and check it works properly.
2. run massive amount of explosion, such as 272 world eater, or run it indefinitely. you can simply do it with attaching observer clock to tnt chamber part.
3. run again and tnt will glitch through block and gets buggy.

### Attachments
https://www.youtube.com/watch?v=ByAARFSY-k4

Any mods used : Lithium 0.5.2, carpet mod 1.4.9
MC version : 1.16.2

**Comment by jellysquid3** [comment]
Does the fix suggested [here](https://github.com/jellysquid3/lithium-fabric/issues/118#issuecomment-683225653) resolve your problem?

**Comment by aria1th** [comment]
tick warped for 144k tick and I think it works

**Comment by 2No2Name** [comment]
Probably the same issue. The oversized blocks counter overflows at 32768 and then an optimization that skips checking for fences and other oversized blocks fails.

**Comment by jellysquid3** [comment]
The fix for this issue has made it into [Lithium 0.5.3](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.2-0.5.3).
