### ISSUE TITLE
NoSuchMethodError from ChunkTicketManager

### ISSUE THREAD

**Issue by Leo40Git** [jellysquid3/Lithium#121]
### Reproduction Steps
1. Load a world. Yeah, this crash is pretty bad.

### Crash Report File
https://gist.github.com/Leo40Git/3ad067e691313a876b0e68a634dbf241

### Additional Information
This crash occurred in a **development environment**. The mod was pulled in via JitPack (so if this isn't repeatable in a production environment, there's the main culprit for a faulty build).

**Comment by jellysquid3** [comment]
Are you certain you're using the `dev` JAR? This doesn't reproduce in my environment. It's also worth checking that you're using the correct mappings between both Lithium and your developer workspace.

**Comment by Leo40Git** [comment]
I'm using build 42 of the mappings vs. your build 14... but Loom should definitely be able to handle that.
I seem to be using the `dev` JAR? The access widener uses the `named` namespace. IIRC Loom converts it to `intermediary` while remapping.

**Comment by Leo40Git** [comment]
...although, now that I look at the decompiled mixin code, I'm seeing a *lot* of intermediary names here...

**Comment by PhiProven** [comment]
This sounds like https://github.com/SpongePowered/Mixin/issues/431.
This issue was "fixed" in an older version of Fabric's mixin fork but reverted lately due to causing some other error.

As a temporary workaround I would suggest to force the older version containing a fix via adding this in the dependencies block of your buildscript
```
runtime('net.fabricmc:sponge-mixin:0.8+build.18') {
    force = true
}
```

**Comment by Leo40Git** [comment]
Welp, that fixed it. Thanks, PhiPro.
I'm assuming this issue is already open in Fabric's Mixin fork...

**Comment by PhiProven** [comment]
No, because it is an upstream Mixin issue. Hence I posted the report on the original Sponge Mixins rather than on Fabric's fork.
