### ISSUE TITLE
Chunks not loading when going through portals.

### ISSUE THREAD

**Issue by forrestw92** [jellysquid3/Lithium#124]
### Expected Behavior
Going through a portal should load the chunks.

### Actual Behavior
Does not load any chunks only entities/mobs. Have to re-log to get the chunk updates.

### Reproduction Steps
Running Lithium 0.5.3, Phosphor, Carpet. Happening to all the players on the server also.

### Attachments
![Issue](https://user-images.githubusercontent.com/35408046/91765450-a42d1700-eb9e-11ea-95d9-88b674334de3.png)

**Comment by 2No2Name** [comment]
Does adding `world.player_chunk_tick=false` to the lithium config solve the issue?

https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File

**Comment by 2No2Name** [comment]
I tested it, and adding that to the config solves it.

**Comment by jellysquid3** [comment]
Fixed with 9bfbd1b, candidate for expedited release.

**Comment by jellysquid3** [comment]
This should be fixed with [Lithium 0.5.4](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.2-0.5.4).
