### ISSUE TITLE
Entity suffocation optimizations in Lithium 0.5.3 are incompatible with Pehkui

### ISSUE THREAD

**Issue by biirds** [jellysquid3/Lithium#125]
I'm getting an Exit Code: 0 crash on launch when starting up 1.16.2 using Lithium 0.5.3. However, when I use 0.5.2, everything works fine. There's no crash log created from this, but I do have a latest.log instead. Again, everything works fine with the previous Lithium version, it's just the newest update that causes issues.

[latest.log](https://github.com/jellysquid3/lithium-fabric/files/5153295/latest.log)

**Comment by 2No2Name** [comment]
add `entity.fast_suffocation_check=false` to the lithium config file. The issue here is that compat116plus mod wants to modify a method that lithium's entity.fast_suffocation_check overwrites.

**Comment by mrmangohands** [comment]
the mod in question is pehkui

**Comment by 2No2Name** [comment]
0.5.4 probably won't require you to use `entity.fast_suffocation_check=false`

**Comment by jellysquid3** [comment]
This should be fixed with [Lithium 0.5.4](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.2-0.5.4).
