### ISSUE TITLE
Going to nether or overworld is broken

### ISSUE THREAD

**Issue by Broyojo** [jellysquid3/Lithium#126]
### Expected Behavior
I expected to go through the portal and be able to see stuff on the other side

### Actual Behavior
I just see a white abyss and I am stuck and I have to relog for it to fix. 

### Reproduction Steps
1. Go through a nether portal and then it will be white and you will be stuck. 
2. then you must relog to fix it.

**Comment by mrmangohands** [comment]
seems like a duplicate of #124, lithium 0.5.4 was just released with a fix
