### ISSUE TITLE
Incorrect version number in release page

### ISSUE THREAD

**Issue by James103** [jellysquid3/Lithium#127]
### Expected Behavior
The first sentence of the Lithium 0.5.4 release page should read: "This release fixes two issues that appeared with Lithium 0.5.**4** for Minecraft 1.16.2." (bold = changed).

### Actual Behavior
The first sentence of the Lithium 0.5.4 release page actually reads as "This release fixes two issues that appeared with Lithium 0.5.3 for Minecraft 1.16.2.".

### Reproduction Steps
Take a look at the release page for Lithium 0.5.4.

### Attachments
Screenshot from release page:
![image](https://user-images.githubusercontent.com/37945304/91788727-91ccd080-ebd2-11ea-8978-d3210637bdac.png)

**Comment by Titaniumtown** [comment]
Oooh, good catch!

**Comment by mrmangohands** [comment]
🤔 the bugs were introduced in 0.5.3, not sure why you'd think otherwise

**Comment by James103** [comment]
That was a misunderstanding on my part. Closing.
