### ISSUE TITLE
Game not loading terrain after teleportation or going trough portal

### ISSUE THREAD

**Issue by Samuelzila** [jellysquid3/Lithium#129]
I was using lithium in 1.16.1, since updating, each time you get teleported or go trough a portal, you just see the sky and you need to log out and in for the terrain de load.

The problem could be me beacause I have a weird config but I just wanted to maybe know if I'm the only one and if not, make you know that this issue exists.

Thank you :)

**Comment by mrmangohands** [comment]
duplicate of #124, fixed in lithium 0.5.4

**Comment by Samuelzila** [comment]
> duplicate of #124, fixed in lithium 0.5.4

Thank you for your reply, I'm new to github and had not seen the fixed tab, my bad
