### ISSUE TITLE
Creeper behaviour 

### ISSUE THREAD

**Issue by Gaz492** [jellysquid3/Lithium#13]
With Lithium installed I have noticed that creepers don't behave as expected around cats,
The expected behaviour is that they would run away from a cat that is within a 6 block radius however with lithium installed the creeper needs to be within a 2 block radius.

This was tested on Fabric 1.15.2

Happy to provide more information if needed,

**Comment by magneticflux-** [comment]
Could you cherry-pick 309ff9ea23237ffb53cd8def03025c1966d94fbd back to the 1.15 branch?

**Comment by jellysquid3** [comment]
@magneticflux- I'm currently working on making some more improvements in this area, but once everything is sound in 1.16 we'll make backports to 1.15. :smile:
