### ISSUE TITLE
[CRASH] Lithium Crashes with a Mixin error.

### ISSUE THREAD

**Issue by YTG1234** [jellysquid3/Lithium#133]
### Reproduction Steps
1. Open up Minecraft
2. The game crashes

### Crash Report File
https://gist.github.com/YTG1234/8eddd54a235acbfd4089c1ad592a65c7
I also turned Mixin debug on there ^

### Additional Information
A mod list can be seen in the log
Fabric API is at the latest version at the time of submitting

**Comment by 2No2Name** [comment]
Does this happen every time you run the game or only occasionally?
I experienced a similar crash in the past, but restarting the game usually fixed this.

**Comment by YTG1234** [comment]
It happens every time I open up Minecraft. It's a Mixin error not a runtime thing

**Comment by 2No2Name** [comment]
Does it also happen with no mixin.debug? If it still does, you can add `entity.replace_entitytype_predicates=false` to the Lithium config. I don't think there is anything else we can do about this. The error message hints at a problem of mixin itself, or it is just a poor message for conflicting mixins.

**Comment by 2No2Name** [comment]
If you have time, you can remove half of your mods and see if the crash still occurs to narrow it down, and then do it again until you have a minimal set of mods that lead to the crash. That might help finding the root cause

**Comment by YTG1234** [comment]
Okay, this is very weird. I just opened up Minecraft again and it suddenly worked. Haven't changed anything in the config

**Comment by 2No2Name** [comment]
I guess then it is the rare mixin race condition. If your setup makes it crash quite often, it might be a good idea to show this to the mixin developers

**Comment by 2No2Name** [comment]
Turning off debug mode should help
