### ISSUE TITLE
Lithium crashes with ComposterMixin error.

### ISSUE THREAD

**Issue by forrestw92** [jellysquid3/Lithium#135]
### Reproduction Steps
Not sure how to reproduce. Seems like after a few seconds after one my players join the server it crashes with this report below. 
Can provide the current world if needed but it is a few gigs compressed.

Also using the build for 1.16.3

### Crash Report File
https://gist.github.com/forrestw92/6c444c5abd5b033f3ba3e42df4c21f7e

**Comment by 2No2Name** [comment]
Fixed in https://github.com/jellysquid3/lithium-fabric/commit/014557c6596afcb3441f3e6d1821fb262376061a
