### ISSUE TITLE
Mobs taking fall damage/dying when falling in water.

### ISSUE THREAD

**Issue by piettieq1** [jellysquid3/Lithium#141]
### Expected Behavior
When not using lithium the falling mobs do not take damage or die.

### Actual Behavior
When using lithium some of the mobs take fall damage/die.

(using gnembons flushing mob farm, some of the mobs falling on the water filled collecting platform die)

**Comment by 2No2Name** [comment]
You can probably work around this by adding `mixin.entity.consolidated_fluid_checks=false` to lithium.properties
