### ISSUE TITLE
TNT doesn't move in water

### ISSUE THREAD

**Issue by noxifoxi** [jellysquid3/Lithium#144]
### Expected Behavior
Ignited TNT should move with the water stream.

### Actual Behavior
Ignited TNT in the first moment looks like its moving but then teleports back to origin location.
This broke a lot of farm on my server (TNT dupers / auto harvesting).
Afaik: This issue didn't occur in "lithium-fabric-mc1.16.2-0.5.4", just happened now in 1.16.3-0.5.5.

### Reproduction Steps
Place TNT above a water stream and ignite it.

### Attachments
Video comparison: https://youtu.be/nkArry-piGI

**Comment by jellysquid3** [comment]
Fixed in [Lithium 0.5.6](https://github.com/jellysquid3/lithium-fabric/releases/tag/mc1.16.3-0.5.6).

**Comment by noxifoxi** [comment]
ok that was fast
