### ISSUE TITLE
just like this

### ISSUE THREAD

**Issue by SnooComics9452** [jellysquid3/Lithium#151]
1. Install Fabric loader 1.16.2
2. put Fabric api and Lithium into mods folder
3. launch the game and The game crashes
![螢幕擷取畫面 2020-10-13 183033](https://user-images.githubusercontent.com/72796659/95849559-37eb2900-0d82-11eb-936a-e52e051c6072.png)

**Comment by AMereBagatelle** [comment]
You seem to have a version mismatch.  This is not a bug with Lithium, simply an installation mishap.  Perhaps join JellySquid's discord server at https://jellysquid.me/discord so we can debug this?

**Comment by jellysquid3** [comment]
This is not an issue with Lithium. You are using the wrong version of Lithium for that version of the game.
