### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Zarpyk** [jellysquid3/Lithium#156]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Start server
~~(1.5. Ping the server?/Reload multiplayer list?)~~ I don't need ping the server, it crash after start
2. Crash

### Crash Report File
https://gist.github.com/GuerreroCraft61/b2645fbdfd906195c7e883a599039375 line 2059

### Additional Information
I join to the world few seconds and the server crash and now I can't join/ping the server

**Comment by 2No2Name** [comment]
Can you remove Lithium and try again?

**Comment by 0f-0b** [comment]
Try [the latest version of Vanilla Experience](https://github.com/AugustoResende/VanillaExperience/releases/tag/0.2.3).

**Comment by Zarpyk** [comment]
> Can you remove Lithium and try again?

I removed it and the crash still, so I think is no lithium problem

> Try [the latest version of Vanilla Experience](https://github.com/AugustoResende/VanillaExperience/releases/tag/0.2.3).

It didn't solve the crash

**Comment by Zarpyk** [comment]
Okay, the crash is caused by vanilla experience, but the new version don't solve it
(Fix disabling ZeroTickFarm in the config)
