### ISSUE TITLE
Rays Works raid farm broken

### ISSUE THREAD

**Issue by heavybulk7812** [jellysquid3/Lithium#161]
### Expected Behavior
The farm should normally work like how he showed in his video and in the world download.

### Actual Behavior
After a small amount of rounds bad omen effect is no longer given, seems like the raid stops in a first phase, where only pillagers and vindicators spawn. No witches, no ravagers and no evokers spawn.

### Reproduction Steps
Build the [farm](https://www.youtube.com/watch?v=2gcWlWTuTj8&t=9) or put the world download on a server. Get bad omen and start using the farm.

I have noticed that there is something in the config file that has to do with raids, but toggling it doesn't seems to produce any difference.

**Comment by 2No2Name** [comment]
Does the farm work as expected for you when you uninstall lithium?

**Comment by heavybulk7812** [comment]
The bug was that the farm needs to be running on hard difficulty, but thanks for the response.
