### ISSUE TITLE
Chunk loading detector not working

### ISSUE THREAD

**Issue by Genhis** [jellysquid3/Lithium#167]
This report refers to the following contraption:

![Chunk loading detector](https://user-images.githubusercontent.com/11155942/99729418-28ff4100-2abb-11eb-8b45-e8112f25a985.png)
\* the armor stand has Frost Walker boots

### Expected Behavior
The water should freeze when the chunk is loaded.

### Actual Behavior
The water does not freeze when the chunk is loaded.

### Reproduction Steps

1. Place an armor stand on a block next to water.
2. Put Frost Walker boots on the armor stand
3. Fly far away or reconnect (wait a few seconds to get chunks unloaded - 30s seem good enough)
4. See if the water block next to the armor stand froze (it did not).

Removing Lithium fixes this issue.

**Comment by 2No2Name** [comment]
It is working for me. Which Lithium version are you using?

**Comment by Genhis** [comment]
Well, I didn't realize that spawn chunks are always loaded... It indeed does work as it's supposed to. Sorry for wasting your time.
