### ISSUE TITLE
Build fails with included wrapper

### ISSUE THREAD

**Issue by magneticflux-** [jellysquid3/Lithium#17]
The build fails with this error:
```log
> Could not resolve all dependencies for configuration ':minecraftLibraries'.
   > org.lwjgl:lwjgl:3.2.2 has more than one client module definitions.
```

As seen on Discord [here](https://discordapp.com/channels/602796788608401408/602805020861267968/684136721411342343):
>Hello, I'm having issues compiling Lithium-1.16.x when i do ./gradlew build it says build failed here's the log
https://sourceb.in/c43950c27f

I'll make a PR that changes the wrapper back to 4.10.2 so Chocohead's Loom fork works.

**Comment by jellysquid3** [comment]
The Gradle wrapper is currently configured to use Gradle 4.9 as of commit https://github.com/jellysquid3/Lithium/commit/812e4860de66d09e48b6aa46ea2eea31e24cccb6. Does this not resolve the problem?

**Comment by magneticflux-** [comment]
Sorry, I'm dumb and forgot to pull before I built earlier!
