### ISSUE TITLE
Intermittent crash near server shutdown

### ISSUE THREAD

**Issue by magneticflux-** [jellysquid3/Lithium#170]
### Reproduction Steps

I'm not able to reproduce this reliably.

I'm using the latest dev build (5e5d6e141a1f7b332d366a5e7ca7ac741102e61b).

### Crash Report File
https://gist.github.com/magneticflux-/3394221111a7936db42d5db9df852037

### Additional Information
Seems mostly likely related to the new `inactive_navigations` patch?

**Comment by magneticflux-** [comment]
~~Possibly a niche case triggering this bug? https://github.com/vigna/fastutil/issues/109~~

Actually, maybe Minecraft is modifying the list after the iterator is created.

**Comment by maityyy** [comment]
I suppose this version fixes the problem? https://github.com/jellysquid3/lithium-fabric/suites/1551209835/artifacts/27727053

**Comment by 2No2Name** [comment]
This should be fixed by the linked commit
