### ISSUE TITLE
Sugarcane can be placed in "invalid" locations

### ISSUE THREAD

**Issue by TacocaTYT** [jellysquid3/Lithium#171]
### Expected Behavior
Sugarcane can only be placed in an empty block
### Actual Behavior
sugarcane can be placed in water, providing the block to any cardinal side and one block down is a water block

### Reproduction Steps

1. place a block of sand or dirt with no adjacent blocks
2. flood area with water source blocks
3. place sugarcane on teh sand
4. The sugarcane does not break even if updated

### Attachments

![image](https://user-images.githubusercontent.com/37640938/100479872-5db75d80-30a4-11eb-9b7d-21a0d781da8d.png)

**Comment by amnotbananaama** [comment]
This is a vanilla issue. https://bugs.mojang.com/browse/MC-929. Please check that an issue doesn't occur in vanilla before filing a bug report.

**Comment by TacocaTYT** [comment]
oop sorry i didnt know mojang had a jira page
