### ISSUE TITLE
Snapshot support possibly?

### ISSUE THREAD

**Issue by QPCrummer** [jellysquid3/Lithium#172]
**Is your feature request related to a problem? Please describe.**
Not necessarily. I have tried porting it to 20w48a, but it always failed. I don’t code, so I have no clue how to fix it. 

**Describe the solution you'd like**
If you could maybe make a way for me to build a 20w48a(20w49a now) that would be great. 

**Describe alternatives you've considered**
None. 
**Additional context** Not really anything

**Comment by jellysquid3** [comment]
No. It's an unreasonable amount of work to track a constantly moving target and update our code to it every week.
