### ISSUE TITLE
Server crashes when using 'game_tick()' function in carpet mod

### ISSUE THREAD

**Issue by Tomddev** [jellysquid3/Lithium#175]
### Reproduction Steps
1. Have Lithium and Carpet mod installed
2. Place a Command block and inside have: "script run game_tick()"
3. Activate the command block
4. The game crashes (If you are using MultiMC that will also hang / crash)

### Crash Report File
Crash report: https://gist.github.com/MediumDifficulty/09d588074ba9866e98a6402eb337ace3

### Additional Information
Can be fixed by having "mixin.world.tick_scheduler=false" in the Lithium config file

**Comment by 2No2Name** [comment]
What are you expecting to happen at 4. instead of the crash?

**Comment by 2No2Name** [comment]
After gnembon explained to me what the command does when ran in a command block (runs tick n+1 when the command block is receiving the tile tick in tick n), I believe it is so unreasonable that we are not going to do any changes to support this operation.

**Comment by gnembon** [comment]
I suggest closing as invalid based on
https://github.com/gnembon/fabric-carpet/commit/51c461febc57a574f09c60d9cc460351b327993a
I added clarification on using `game_tick()` that hopefully shed the light on running your own game loop inside the vanilla game loop.
