### ISSUE TITLE
Command Blocks do not retain data as of commit a818d2a

### ISSUE THREAD

**Issue by ImperatorStorm** [jellysquid3/Lithium#177]
### Expected Behavior
Command Block works as intended, saving any inputted data

### Actual Behavior
All data inputted into the Command Block is not saved, and Lithium throws https://pastebin.com/46uR0uNB without crashing

### Reproduction Steps
1. Place a Command Block while in Creative Mode and with Operator Privileges
2. Attempt to input a command into the Command Block
3. All data inputted into the Command Block is deleted

**Comment by Heitzenberg** [comment]
Can confirm.
