### ISSUE TITLE
Mixins logs a warning that some inner-class targets are public and should be referenced directly

### ISSUE THREAD

**Issue by K0-RR** [jellysquid3/Lithium#181]
[main/WARN]: @Mixin target net/minecraft/class_3962$class_3963 is public in lithium.mixins.json:alloc.composter.ComposterMixin$ComposterBlockComposterInventoryMixin and should be specified in value

**Comment by ImperatorStorm** [comment]
this error is most likely known and doesn't matter

**Comment by K0-RR** [comment]
I know but I trying to make mods spam the console less.

**Comment by jellysquid3** [comment]
This is a harmless warning, though I'm not sure why it gets logged since the mentioned class is protected and can't be referenced directly. Per Mixin's documentation, our usage seems correct:
```
    /**
     * Since specifying targets in {@link #value} requires that the classes be
     * publicly visible, this property is provided to allow package-private,
     * anonymous innner, and private inner classes to be referenced. Referencing
     * an otherwise public class using this property is an error condition and
     * will throw an exception at runtime. It is completely fine to specify both
     * public and private targets for the same mixin however.
     *
     * @return protected or package-private classes this mixin targets
     */
```

**Comment by 2No2Name** [comment]
If anyone makes a PR that fixes these warnings, I will merge it.
