### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by TreeV2** [jellysquid3/Lithium#182]
So when i use lithium with optifabric game crash. when i use sodium with optifabric game crash. And when i use sodium lithium with optifabric game crash . Dear developer can you fix this crash or add compatibility ?

here pics: 
![image](https://user-images.githubusercontent.com/69603592/103468476-8db7e780-4d59-11eb-8294-aa797001f039.png) < here is pics when i use lithium with optifabric

![image](https://user-images.githubusercontent.com/69603592/103468481-ad4f1000-4d59-11eb-8f55-9a2fc1337a98.png)< here is pics when i use sodium with optifabric

![image](https://user-images.githubusercontent.com/69603592/103468491-ceaffc00-4d59-11eb-93a3-d5b4bf47df5a.png) < here is pics when i use sodium and lithium with optifabric

**Comment by ghost** [comment]
Sodium and lithium are permanently incompatible with OptiFabric, there is a list of substitutes on the curseforge page or something

**Comment by jellysquid3** [comment]
Yes, as the error screen literally tells you:
> sodium conflicts with optifabric
