### ISSUE TITLE
Lithium (dev branch) has issues with lunaar-carpet-addons (crash while loading world)

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [jellysquid3/Lithium#183]
### Expected Behavior
The world loads normally.

### Actual Behavior
The game crashes while loading a world (the game starts up fine).

### Reproduction Steps
1) Keep carpet mod, [lunaar-carpet-addons](https://github.com/Copetan/lunaar-carpet-addons/) and lithium (dev branch) in your mods folder. I don't think the mods require Fabric API, but I kept it in the mods folder anyway.

2) Load a world (tested on multiple worlds and in multiple MultiMc instances to make sure it is not a world issue).

3) Observe the crash.

4) Disable/remove lithium (dev branch). Load up a world and no crash will occur.

5) Re-enable/re-add lithium and disable/remove lunaar-carpet-addons. Load up a world and no crash will occur.  

### Attachments
[Crash report](https://github.com/jellysquid3/lithium-fabric/files/5761901/crash-2021-01-03_16.29.54-server.txt)

[Log](https://github.com/jellysquid3/lithium-fabric/files/5761909/2021-01-03-2.log)

**Comment by 2No2Name** [comment]
The portal forcer patch was removed from lithium. Therefore this crash is probably fixed.

**Comment by DragonEggBedrockBreaking** [comment]
After testing the mod, I was experiencing a similar crash. I have not tested for which mods caused this, but I will close later today if this is a separate issue.

**Comment by DragonEggBedrockBreaking** [comment]
Actually, I was referring to the change you made in regards to the config file. I didn't notice JellySquid's newer commit... Sorry...  I will close later today when I test (if this gets fixed).

**Comment by DragonEggBedrockBreaking** [comment]
Cannot test at the moment because of #198

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> The portal forcer patch was removed from lithium. Therefore this crash is probably fixed.

Yes, all fixed now.
