### ISSUE TITLE
Lithium used with Fabric API throws mixin target warning in log

### ISSUE THREAD

**Issue by saltyseadoggo** [jellysquid3/Lithium#184]
### Expected Behavior
Using Lithium in conjunction with the Fabric API would not trigger any warnings in Minecraft's output log.

### Actual Behavior
Using the latest version of Lithium (0.6.0) in conjunction with the latest version of the Fabric API at the time of testing (0.29.2) causes this warning to appear in the log when Minecraft starts up:
*@Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value*
This error does not appear with only the Fabric API or only Lithium in the mods folder, and does appear when Lithium and the Fabric API are the only mods in the mods folder. This was encountered using the latest version of Fabric at the time of release, 0.10.8.

### Reproduction Steps
Provide information on how to reproduce this game crash. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear! If applicable, please provide a world file as a compressed ZIP which contains a minimally reproducible example of the issue. 

1. Create a new installation in the Minecraft launcher using a fresh directory, running Fabric 0.10.8 for Minecraft 1.16.4.
2. Boot the game to let it set up the directory, then quit the game.
3. In the directory's *mods* folder, place only the latest releases of Lithium and the Fabric API.
4. In the Minecraft launcher, enable *Open output log when Minecraft: Java Edition starts* in the settings, and boot the game.
5. Note the one singular warning that appears.

### Attachments
[latest.log](https://github.com/jellysquid3/lithium-fabric/files/5762235/latest.log)

**Comment by saltyseadoggo** [comment]
May be related to #181, depending on what circumstances cause that issue. The two issues also pertain to different mixins.

**Comment by AMereBagatelle** [comment]
That's a largely irrelevant warning to my knowledge, in the development environment even without Lithium Fabric API throws a bunch of those.  Unless it's causing a crash or unexpected behavior I don't believe this is an issue.

**Comment by 2No2Name** [comment]
I think it is safe to ignore this warning.
