### ISSUE TITLE
Lithium not compatible with 1.16.5

### ISSUE THREAD

**Issue by volitle** [jellysquid3/Lithium#189]
Server fails to start after updating to 1.16.5 with Lithium installed. See attached crash.

[15:28:23] [main/FATAL]: A critical error occurred
,net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: lithium requires {minecraft @ [1.16.2 || 1.16.3 || 1.16.4]}
,	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[fabric-server-launch.jar:?]
,	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:180) ~[fabric-server-launch.jar:?]
,	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[fabric-server-launch.jar:?]
,	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [fabric-server-launch.jar:?]
,	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [fabric-server-launch.jar:?]
,	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-server-launch.jar:?]
,	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
,	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
,	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
,	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
,	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
,	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
,	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
,Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
,	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
,	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
,	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
,	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
,	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:177) ~[fabric-server-launch.jar:?]
,	... 12 more
,2021-01-15T15:28:23.913-0500	WARN	mc-server-runner	sub-process failed	{"exitCode": 1}
,2021-01-15T15:28:23.913-0500	INFO	mc-server-runner	Done

**Comment by jellysquid3** [comment]
The error message tells you what the problem is.

**Comment by volitle** [comment]
Yes I'm aware this addon is the only one on my server that has a hard coded requirement for 1.16.2/3/4, if the resolution is to change it manually then I'll just do that.
