### ISSUE TITLE
Lithium doesn't work on the latest version.

### ISSUE THREAD

**Issue by uBreeze** [jellysquid3/Lithium#192]
**Reproduction**

1. Use Fabric for Minecraft 1.16.5
2. Place the latest Lithium download into the mods folder.
3. Minecraft will fail to start.

**Crash Report File:** 

- https://gist.github.com/BreezeGH/1297db550401bf8931d9eb16fc12716f

**Additional Information:**

I apologize if you are already aware of this, based off my own inexperienced logic from reading the crash report, the problem is relatively obvious, but I could be wrong.

**Comment by DragonEggBedrockBreaking** [comment]
Read #190 
Lithium has not yet updated to 1.16.5
Thanks for the bug report, but it would be best if you close it now.
