### ISSUE TITLE
Lithium Dev Branch Crashes On Start-Up

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [jellysquid3/Lithium#198]
### Reproduction Steps
Put Lithium in mods folder. Try starting up. I tested both with and without lunaar-carpet-addons.

### Crash Report File
I couldn't get a crash report file, but hopefully the [log files](https://gist.github.com/DragonEggBedrockBreaking/016ba6f76ea0eb3421c1368b1db969de) will be enough.

### Versions:
-- Minecraft 1.16.4
-- Fabric loader 0.11.1
-- Lithium 0.6.1 SNAPSHOT, latest commit: 341c1a4
-- MultiMc 5

**Comment by Kroppeb** [comment]
Can confirm. It seems it can't find the interface in the API?

**Comment by DragonEggBedrockBreaking** [comment]
Seems like d2a5d9e should fix it, I will test, and if it works fine, I will close this report.

**Comment by DragonEggBedrockBreaking** [comment]
Can confirm, this is fixed! @2No2Name
