### ISSUE TITLE
Chunks do not render correctly on multiplayer servers

### ISSUE THREAD

**Issue by Devan-Kerman** [jellysquid3/Lithium#2]
When joining a server, chunks do not render correctly on the client. I have yet to test it with a vanilla server.

Expected: chunks render normally, no random voids and all blocks are rendered

![image](https://user-images.githubusercontent.com/28693059/69904136-b0164f00-1368-11ea-9b41-b6f578ac3bdb.png)

Installed mods:
![image](https://user-images.githubusercontent.com/28693059/69904142-c6bca600-1368-11ea-9a34-f7f172f5937d.png)

Before installing lithium chunks had rendered correctly, this only occurs after adding lithium

logs if needed:
[latest.log](https://github.com/jellysquid3/Lithium/files/3907408/latest.log)

**Comment by jellysquid3** [comment]
This has been fixed by https://github.com/jellysquid3/Lithium/commit/23919c4feb1e810caa90cf9635ff4058cf7de29c and will be available in 0.1.1. Thanks for the report.

**Comment by Devan-Kerman** [comment]
Joining a multiplayer server now crashes the game
[crash-2019-11-30_13.13.40-client.txt](https://github.com/jellysquid3/Lithium/files/3907463/crash-2019-11-30_13.13.40-client.txt)

**Comment by jellysquid3** [comment]
@Devan-Kerman Your issue pertains to a bad font rendering patch [which I've now removed](https://github.com/jellysquid3/Lithium/commit/30f4ccfabf78b3055f793cad35c16427020df065) due to it not offering any benefits. The patch has landed in 0.1.2.

**Comment by Devan-Kerman** [comment]
kewl
