### ISSUE TITLE
Crashes with Fabric Zero

### ISSUE THREAD

**Issue by FewerFlaws** [jellysquid3/Lithium#203]
### Reproduction Steps
  * Load Minecraft `1.16.5` with Fabric API `0.29.4`, Fabric Zero `0.2.0`, and Lithium `0.6.1` installed.
  * Observe crash on startup.

### Crash Report File
[Right here](https://gist.github.com/FewerFlaws/991aea5fee3d49dc7024d606a85ef7b7).

### Additional Information
[Same issue](https://github.com/Fox2Code/FabricZero/issues/14) on Fabric Zero page.

**Comment by Kroppeb** [comment]
This is due to the horrible code that is Fabric Zero's `FastMath`, that breaks some assumptions we make about the `SINE_TABLE`.

**Comment by 2No2Name** [comment]
I suggest to either add `mixin.math=false` to the lithium config file, or uninstall fabric zero. We won't fix this incompatibiity from our side.

**Comment by FewerFlaws** [comment]
Thank you for getting back to me.  Could you briefly list your criticisms of Fabric Zero?  I'll go through the code myself but I'd like appreciate a few pointers on what to notice =]
