### ISSUE TITLE
Incompatible with "Simple Planes"

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#204]
### Reproduction Steps
When Lithium and [Simple Planes](https://www.curseforge.com/minecraft/mc-mods/simple-planes-fabric) are installed together, flying over the ocean will cause an Entity Tick crash.

1. Spawn in any plane from Simple Planes
2. Fly over the ocean
3. The game crashes when seeing dolphins

### Crash Report File
[crash-2021-01-24_23.54.21-server.txt](https://github.com/jellysquid3/lithium-fabric/files/5867213/crash-2021-01-24_23.54.21-server.txt)

### Additional Information
The server is on 1.16.4

**Comment by 2No2Name** [comment]
The crash report looks like Simple Planes would also crash when Lithium is not installed.

**Comment by 2No2Name** [comment]
This isn't caused by Lithium and it is also not caused by simple planes.

**Comment by magneticflux-** [comment]
@bendooms Look for a mod with a mixin method inject called `pathfindThroughFences`, as that's what causes the issue. Neither Lithium nor Simple Planes contain such a mixin afaik.

**Comment by ghost** [comment]
Alright, I'll take a look. Thank you guys!
