### ISSUE TITLE
reuse `EntityShapeContext` instead of replacing it entirely

### ISSUE THREAD

**Issue by nnym** [jellysquid3/Lithium#208]
**The problem**
Currently `LithiumEntityShapeContext` replaces `EntityShapeContext` without extending it, with can cause incompatibilities with mods using `EntityShapeContext` specifically. (See [user11681/paradox-slabs](https://github.com/user11681/paradox-slabs/tree/1.16/src/main/java/user11681/paradoxslabs/mixin/EntityShapeContextMixin.java).)

**The solution**
Have `LithiumEntityShapeContext` extend `EntityShapeContext` or apply the optimizations in `LithiumEntityShapeContext` to `EntityShapeContext` directly with Mixin.

**Comment by 2No2Name** [comment]
That makes sense. I will do that

**Comment by 2No2Name** [comment]
For now you can work around this by adding `mixin.shapes.lazy_shape_context=false` to the lithium config file

**Comment by DragonEggBedrockBreaking** [comment]
> 
> 
> That makes sense. I will do that

Just a reminder to close this if ec7776f is where you implemented this.
