### ISSUE TITLE
Frosted Ice loads chunks 

### ISSUE THREAD

**Issue by zLauch** [jellysquid3/Lithium#209]
Mango found out that the End was loaded with nobody in it and later it was found out that the Frosted Ice loads Chunks in the End  without anybody near it.

![image](https://user-images.githubusercontent.com/44842475/106485848-513eef00-64b1-11eb-981b-3914eb6e2c90.png)

**Comment by Kroppeb** [comment]
Ugh so they didn't fully fix the issue?

**Comment by zLauch** [comment]
I don't know what do you mean but.

We've tried it with Lithium on a brand new Server: Stays End Loads
Without: Nothing

**Comment by Kroppeb** [comment]
Oh, this is caused by lithium?

**Comment by 2No2Name** [comment]
A user sent me this worlddownload ( i removed all but the end dimension). How to reproduce: Enter the end, leave the end (through end portal, not sure if relevant). Then profile the game, e.g. using /debug start and /debug stop a few seconds later.

The results in vanilla are that the end is barely taking and CPU time, while with lithium it takes a lot of CPU time

[Peaceful.zip](https://github.com/jellysquid3/lithium-fabric/files/5906246/Peaceful.zip)

**Comment by jellysquid3** [comment]
I'm marking this as critical due to the risk the bug here offers for a denial-of-service attack against servers running Lithium.

**Comment by 2No2Name** [comment]
Workaround for now is adding `mixin.world.tick_scheduler=false` to the lithium properties file

**Comment by 2No2Name** [comment]
This is likely caused by an off-by-one error at the bottom of the world. All scheduled ticks at y0 are not saved/removed from the world in the releases before 0.6.2

**Comment by 2No2Name** [comment]
No longer reproducible with commit d9ff49b312cd6dbd8098cfa09f01a97ecaf2bf0f
