### ISSUE TITLE
Instant crash with Hydrogen 0.2 Snapshot

### ISSUE THREAD

**Issue by Lentern** [jellysquid3/Lithium#210]
### Reproduction Steps
1) Add Lithium 0.6.3 and Hydrogen 0.2 Snapshot
2) Start 1.16.5 Fabric
3) Instant crash without report

### Crash Report File
The game generates an exit code of 0 without a crash report

**Comment by 2No2Name** [comment]
Are you running the client or the server? If you are running the server, did you accept the eula in the eula.txt?

**Comment by Lentern** [comment]
I am running the client. Does the Fabric build that I am using affect this? I'm using build 204.

**Comment by Lentern** [comment]
Updated Fabric to 0.11.1 and the issue is fixed.
