### ISSUE TITLE
Lithium causing game crashes with Xearo's Minimap

### ISSUE THREAD

**Issue by chxlky** [jellysquid3/Lithium#211]
### Reproduction Steps
1) Have the latest version of Lithium and Xaero's Minimap
2) Make a new world
3) Hit 'u' on your keyboard (minimap waypoints screen) 
4) Game immediately crashes

### Crash Report File
https://gist.github.com/ItsChalkyJeans/9b02096889cefdf3977207ff867e8e7d

### Additional Information
- Using AdoptOpenJDK 15.0.2

**Comment by silversquirl** [comment]
This looks like an incompatibility between Lithium and Terrestria, not Xaero's Minimap. Could you try with just Lithium and Terrestria (plus dependencies)?

**Comment by chxlky** [comment]
Ok, I'll do it

**Comment by chxlky** [comment]
It works now. I'm confused. The mods I used just for this were:
![image](https://user-images.githubusercontent.com/73715948/106855341-adbe2c00-66b4-11eb-8bbe-727371445139.png)

I'm able to create a waypoint, not just open the waypoints screen

**Comment by 2No2Name** [comment]
@ItsChalkyJeans I think you are experiencing https://github.com/CaffeineMC/hydrogen-fabric/issues/19

**Comment by chxlky** [comment]
> @ItsChalkyJeans I think you are experiencing [CaffeineMC/hydrogen-fabric#19](https://github.com/CaffeineMC/hydrogen-fabric/issues/19)

Hmm, interesting. I solved it by using BYG instead of the Terraformers mods. It works fine now.
