### ISSUE TITLE
Fern destroys local minecraft mod

### ISSUE THREAD

**Issue by Kizuati** [jellysquid3/Lithium#216]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Load lithium with the mods listed in the log.
2. Open a world with fern...
3. The game crashes

Please mention why you think Lithium may be the cause of the crash. If possible, please confirm that the crash does not happen when Lithium is not installed.

//Logs
[LITHIUMFUCKS ME.txt](https://github.com/CaffeineMC/lithium-fabric/files/5998391/LITHIUMFUCKS.ME.txt)
[lognolithium.txt](https://github.com/CaffeineMC/lithium-fabric/files/5998392/lognolithium.txt)

### Additional Information
Hilarious.

**Comment by Leo40Git** [comment]
Actual issue is incompatibility with Tiny Tweaks: https://github.com/Hephaestus-Dev/TinyTweaks/blob/master/src/main/java/dev/hephaestus/tweaks/mixin/block/planthitboxes/FernBlocks.java
