### ISSUE TITLE
At least hoppers and spawners stop functioning under light server load

### ISSUE THREAD

**Issue by Hnaguski** [jellysquid3/Lithium#217]
### Expected Behavior
Hoppers and other blocks continue to function even if there is very mild load on the server. I tested in vanilla and the bug doesn't seem to occur.

### Actual Behavior
Hoppers stop moving items, spawners stop spawning mobs, and other things might be broken if the game is under a slight amount of load (20 pistons connected to observer clock causes the bug on a Ryzen 5 3600).
I am running lithium compiled with java 15 at commit 7496b54

### Reproduction Steps
1. Place hoppers and fill with items
2. Create some load for the server
3. Wait until the hoppers stop transferring items

[Video of bug in action](https://paste.cf/72f83fb4587cbbca921be3409829c5fe26d99a53.webm)
[World download for setup](https://github.com/CaffeineMC/lithium-fabric/files/6032195/lithium_bug.zip)

**Comment by silversquirl** [comment]
Does this occur on the stable release of Lithium or on the development branch? Are you using any mods other than Lithium?

**Comment by 2No2Name** [comment]
Add mixin.block_entity_ticking.sleep=false to the config file for now. Working on a fix

**Comment by 2No2Name** [comment]
Add mixin.world.block_entity_ticking.sleeping=false to the config file for now. Working on a fix

**Comment by Hnaguski** [comment]
> Does this occur on the stable release of Lithium or on the development branch? Are you using any mods other than Lithium?

I updated the issue to explain it's on the latest dev branch

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/e5659c6c057fb67600aa5dc0b41fe0091473c7c1 works around this problem for now until it is fixed

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/df7e4e10cbd1dbd0c66fa41e1ff176e76e067ee5 fixes this issue

**Comment by Hnaguski** [comment]
Just tested the latest commit for a bit and it seems like the issue has been fixed, I think this can be closed now unless more testing needs to be done.

**Comment by 2No2Name** [comment]
There still seem to be issues, but those are tracked at https://github.com/CaffeineMC/lithium-fabric/issues/218 now
