### ISSUE TITLE
As of commit df7e4e1, client can randomly crash while connected to server

### ISSUE THREAD

**Issue by ImperatorStorm** [jellysquid3/Lithium#218]
### Reproduction Steps

1. Connect to server
2. Walk around server?
3. Crash

Notenoughcrashes suggested Lithium, lithium is 3rd in stacktrace, crash report suggested lithium
### Crash Report File
https://paste.ee/p/2t5Sa

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/53a5adf382fd9f1524374ea09e87ab5a6491c888 disables the optimization that seems to be causing several problems

**Comment by ImperatorStorm** [comment]
running around for a few minutes, can no longer reproduce
