### ISSUE TITLE
[1.15.2-Forge]Server crash

### ISSUE THREAD

**Issue by EnterFor** [jellysquid3/Lithium#22]
https://paste.ubuntu.com/p/Y5cmBnB76J/
Don't know what caused it
It looks like a chunk problem

Forge：31.1.18
Mod：0.4.5-rc2

**Comment by jellysquid3** [comment]
There is not enough information to reproduce this issue. It would be helpful if you could attach the affected world.

**Comment by EnterFor** [comment]
Sorry, this may not be your problem..
https://github.com/XYROC/DungeonCrawl/issues/23
