### ISSUE TITLE
Conflict with optifabric mod

### ISSUE THREAD

**Issue by Toffikk** [jellysquid3/Lithium#220]
### Reproduction Steps

Just startup the server with latest optifabric mod and latest lithium.

### Crash Report File

https://gist.github.com/tofikarz/2bdd1a02159e403dccf2a4d98d033615

### Additional Information
I'm using latest fabric-api 0.31.0 and the other mods that i'm using are starlight-fabric 0.0.3 and lithium 0.6.4 , optifabric 1.9.6

It doesn't happen without lithium (that's obvious i think)

**Comment by Genau6502** [comment]
There’s a reason it won’t load, if you’ve modified the fabric.mod.json then that’s your issue, not lithiums

**Comment by Toffikk** [comment]
I didn't modify anything

**Comment by Genau6502** [comment]
Lithium refuses to load with optifabric for a reason, optifine is very incompatible with other mods and optifabric is what can be described as a really massive hack

**Comment by 2No2Name** [comment]
read pin
