### ISSUE TITLE
Not able to spawn beehives on trees next to flowers

### ISSUE THREAD

**Issue by shotah** [jellysquid3/Lithium#225]
Just added lithium and fabric and now bees don't spawn with trees. I've tried 100+ times with only trees, even in areas I've previously had bees spawn.

**Comment by maityyy** [comment]
Can you provide a world seed with coordinates where the bees should be and the Lithium/Fabric API/Fabric Loader versions? Otherwise, we will not be able to solve this problem.

**Comment by shotah** [comment]
Maybe be fabric issue, I pulled the mod and tried with just fabric. 

xyz: 63 63 237
Seed: 6882081788049332486
lithium jar file: lithium-fabric-mc1.16.5-0.6.4.jar 
api jar file: fabric-api-0.32.5+1.16.jar
fabric jar: .fabric-installed-1.16.5-0.7.2

-- update --
After I pulled lithium I was able to get a spawn, but rate still seems extremely low vs before.

**Comment by 2No2Name** [comment]
Are you aware that beehive generation on growing trees is biome dependent?

https://minecraft.fandom.com/wiki/Beehive#Natural_generation

**Comment by magneticflux-** [comment]
@shotah How exactly are you checking for bees? Are you growing trees from saplings or are you looking for natural trees?

In either case, they use the same feature generation: a `Feature<TreeFeatureConfig>` that has a `BeehiveTreeDecorator` attached. Lithium only touches `StructureFeature` generation (villages, strongholds, woodland mansions, etc.), so I don't think Lithium could be causing this directly at least.
