### ISSUE TITLE
Console spammed with STDERR

### ISSUE THREAD

**Issue by srnyx** [jellysquid3/Lithium#230]
### Expected Behavior
No errors

### Actual Behavior
An error spammed console

### Reproduction Steps
1. Install Lithium
2. Install [World (Dungeons) of Exile](https://www.curseforge.com/minecraft/mc-mods/dungeons-of-exile)

### Attachments
https://paste.srnyx.xyz/bijuxesewa.csharp

**Comment by actuallyasmartname** [comment]
This is an error with World of Exile
