### ISSUE TITLE
Async ViewDistance - Sentence 

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#237]
Hi, I have a cool idea!
Your plugin generates chunks, but if you can implement visibility like this plugin, it will be a breakthrough!

https://www.spigotmc.org/resources/fartherviewdistance.84950/

P.S
+This will significantly increase the Ping of players!

**Comment by 2No2Name** [comment]
This is out of scope for lithium and if there is any fabric mod that implements this feature we will try to be compatbile with it.
