### ISSUE TITLE
Ender Pearl despawning if the player disconnects

### ISSUE THREAD

**Issue by noxifoxi** [jellysquid3/Lithium#241]
### Version Information

lithium-fabric-mc1.17-0.7.0

### Expected Behavior

Ender Pearls in stasis contraptions should stay there if the player logs out.

### Actual Behavior

Ender Pearls despawn if the player disconnects from the server.
(Only tested with me as the only one player at the server in the spawn chunks)

### Reproduction Steps

- Throw an Ender Pearl in a stasis contraption (Soul Sand bubble column)
- disconnect
- reconnect

### Other Information

fabric-api-0.34.9+1.17

**Comment by 2No2Name** [comment]
This is not changed by lithium, vanilla behaves the same.

**Comment by noxifoxi** [comment]
welp, I didn't test vanilla, because I thought mojang simply couldn't mess this up again.
