### ISSUE TITLE
glowsquid server crash?

### ISSUE THREAD

**Issue by wh0oo** [jellysquid3/Lithium#242]
version: Lithium 0.7.0

I cant tell you how to replicate it because I dont know exactly what behaviour caused it.  

[crash-2021-06-09_17.33.54-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/6627382/crash-2021-06-09_17.33.54-server.txt)

**Comment by 2No2Name** [comment]
This is a watchdog crash, a bat entity was ticking and other threads were working on world saving. Was the server lagging in the minutes before the crash?

Did this crash only happen once or does it keep happening?

**Comment by wh0oo** [comment]
It only happened once. The server was actually humming along nicely.  I am
new to using Lithium so I was, and still am actually, pleased with the
performance improvements.

**Comment by 2No2Name** [comment]
I am not sure whether this is actually an issue with Lithium. If it happens again, please report that as well
