### ISSUE TITLE
Incompatible with MCMT for Fabric

### ISSUE THREAD

**Issue by Vampiee** [jellysquid3/Lithium#243]
First time ever posting an issue, so I hope I'm doing this right, basically MCMT makes it so multithreading is possible on Minecraft servers.
`12.06 02:46:55 [Server] main/FATAL Mixin apply failed mcmtfabric.mixins.json:ServerChunkManagerMixin -> net.minecraft.class_3215: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @At("FIELD") on net/minecraft/class_3215::overwriteServerThread with priority 1000 cannot inject into net/minecraft/class_3215::method_12121(IILnet/minecraft/class_2806;Z)Lnet/minecraft/class_2791; merged by me.jellysquid.mods.lithium.mixin.world.chunk_access.ServerChunkManagerMixin with priority 1000 [PREINJECT Applicator Phase -> mcmtfabric.mixins.json:ServerChunkManagerMixin -> Prepare Injections ->  -> redirect$bbp000$overwriteServerThread(Lnet/minecraft/class_3215;)Ljava/lang/Thread; -> Prepare]`
Server immediately crashed after posting this message, looks like MCMT tries to 
[https://github.com/himekifee/MCMTFabric](url) Here's MCMT for Fabric
[https://github.com/jediminer543/JMT-MCMT](url) And here's MCMT for Forge (With an actual explanation of what it is)

**Comment by 2No2Name** [comment]
Please read the README that you linked. It states

> IMPORTANT NOTICE
> 
> This fecks around with a LOT of minecraft's internal processing loops. If you are using this with any other mods; it may break. If you do something in vanilla, it might still break. It might break simply by you looking at it. It is almost impossible to test every possible interaction that CAN occur; all I can say is that it's worked in every case I've tested.
> 
> DO NOT, under any circumstances, report errors under this mod back to the mod author unless they have EXPLICITLY stated they are attempting to support it. Should mod devs wish to support this in any way, please yell so I can add registration apis.
