### ISSUE TITLE
Comparator reads wrong signal strengh from a hopper minecart

### ISSUE THREAD

**Issue by Chishikii** [jellysquid3/Lithium#244]
### Version Information
> lithium-fabric-mc1.17-0.7.0

### Expected Behavior
> Comparator reads signal strength from a hopper minecart between 0 - 15.

### Actual Behavior
> Comparator reads signal strength between 0 - 2.

### Reproduction Steps
>  1. Place hopper minecart on a detector rail.
>  2. Let comparator read from that hopper minecart.
>  3. Wrong output signal strength.

**Comment by 2No2Name** [comment]
This sounds like a thing that absolutely could happen due to the minecarts having an internal inventory size of 36 slots and me using the wrong size.

**Comment by 2No2Name** [comment]
Fixed by https://github.com/CaffeineMC/lithium-fabric/commit/cb651ff46f0863ece92a7da7db9dc84e8a8ab3b1
