### ISSUE TITLE
Add jitpack.yml to allow jitpack builds

### ISSUE THREAD

**Issue by 2No2Name** [jellysquid3/Lithium#249]
**Is your feature request related to a problem? Please describe.**
Some mods depend on lithium, jitpack is used by some mod authors to automatically get a lithium build with gradle.

**Describe the solution you'd like**
Add a jitpack.yml that makes jitpack builds not crash

**Describe alternatives you've considered**
Not adding a jitpack.yml leaving all the mod authors unhappy

**Comment by Fallen-Breath** [comment]
In case some modders do require lithium 1.17 maven to build their mods now, there is a alternative usable maven [Curse Maven](https://www.cursemaven.com/) which uses lithium's released jar file in curseforge

But still, jitpack support which is directed generated from github source is always better

**Comment by 2No2Name** [comment]
Implemented in the latest release
