### ISSUE TITLE
[1.17 lithium dev branch] Items are not being picked correctly

### ISSUE THREAD

**Issue by aria1th** [jellysquid3/Lithium#253]
------------------------

### Version Information

Lithium-fabric mc 1.17.3 -0.7.3 SNAPSHOT (fcbf706)
Additional mods: fabric-carpet 1.7.40, Carpet TIS Addition 1.20.0

### Expected Behavior
player has empty inventory so should pick up nearby items.
### Actual Behavior

![2021-07-11_02 44 42](https://user-images.githubusercontent.com/35677394/125172323-11183100-e1f4-11eb-98ba-94bb08e2996a.png)
![2021-07-11_02 52 16](https://user-images.githubusercontent.com/35677394/125172324-183f3f00-e1f4-11eb-8523-7fe255ec4491.png)

player is not picking up items, but it 'recognizes' player when player moves and picked up.

### Reproduction Steps

Dragon eggs are sent through portals(duplicated) and goes through water stream. player is also pushed by stream against glass. 

### Other Information

it is not official release, I'll test if official branch can reproduce it ,within 16 hours.
World height change datapack(official cavesandcliffspreview) is ON.

**Comment by 2No2Name** [comment]
Lithium does not modify the player item entity pickup code, so I believe this is coming from another mod or even vanilla

**Comment by aria1th** [comment]
yes, it seems like vanilla bug
