### ISSUE TITLE
Litematica schematic renders don't update after faster y limit access change

### ISSUE THREAD

**Issue by Banzobotic** [jellysquid3/Lithium#254]
### Version Information

> Lithium commit `75d3eda` (faster world y limit access) leads to litematica schematics not updating when I change their position or change the range of y values that it renders at. 

### Expected Behavior

> When I change the range of y values that are displayed or change the location of the schematic, the rendering of it updates

### Actual Behavior

> The schematic render does not update when I change the range of y values or move its location

### Reproduction Steps

> 1. Have lithium from any commit between latest and `75d3eda` in your mods folder as well as malilib and litematica
> 2. Place a schematic
> 3. Try to change the visible y level range of the schematic or move it

### Other Information

> Schematic updates when changing the y level visibility mode

**Comment by 2No2Name** [comment]
Can you try adding `mixin.world.inline_height=false` to the config file and see if it works?

**Comment by Banzobotic** [comment]
Yes this fixes the issue

**Comment by 2No2Name** [comment]
This is confusing as there is no code in litematica that looks like it is incompatible with this

**Comment by Banzobotic** [comment]
Should no longer be dev branch only after the lithium 0.7.4 release. I have not had a chance to test it yet though.

**Comment by 2No2Name** [comment]
likely the same issue https://github.com/maruohon/litematica/issues/403

**Comment by littlebeagle** [comment]
Yep just to say a couple of us that use litematica came across this same issue when testing 0.7.4

**Comment by 2No2Name** [comment]
Talked to masa, it will be fixed in litematica.
