### ISSUE TITLE
When you join the game or load into a new dimension, you fall through the world for a very long time. It can be about 5 seconds - 3 minutes.

### ISSUE THREAD

**Issue by NateTGP** [jellysquid3/Lithium#255]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **bug report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version Information

> Replace this text with the exact version of the mod you are using. Every part of the version is important! If you
> do not know what version you are using, look at the file name in your "mods" folder.
> 
> Example: lithium-fabric-mc1.16.5-0.6.4

### Expected Behavior

> Replace this text with what you expected to happen.
>
> Example: The Piston should extend.

### Actual Behavior

> Replace this text with what actually happened.
>
> Example: The Piston does not extend.

### Reproduction Steps

> Provide information on how to reproduce this bug. You can either fill this section in like the example below
> or do something else -- just make sure your instructions are minimal and clear, as other people will need to be able
> to replicate your issue.
> 
> Example:
> 1. Place a Redstone Lamp in front of a Redstone Repeater
> 2. Use a Lever to activate the Redstone Repeater
> 3. Nothing happens

### Other Information

> Provide a list of any other mods you are using, along with their respective versions. If you have any screenshots,
> videos, or other information that you feel is necessary to explain the issue, feel free to attach them here.

**Comment by fooeyround** [comment]
You did not fill out but report.

**Comment by silversquirl** [comment]
This occurs in vanilla when a client has a weak connection to the server. Are you experiencing this issue more than normal with Lithium installed?

**Comment by 2No2Name** [comment]
If this is still an issue, please fill out the issue template.
