### ISSUE TITLE
Somehow prevents trees in Plant-In-A-Jar from growing

### ISSUE THREAD

**Issue by ruvaldak** [jellysquid3/Lithium#259]
### Version Information

compiled 604795a

### Expected Behavior

Trees in Plant In A Jar mod growing inside the jars

### Actual Behavior

Trees just.. don't grow.

### Reproduction Steps

Install Plant In A Jar on 1.17.1, place a tree and dirt in it, observe.. nothing.

### Other Information

Doesn't happen in the latest Modrinth release, so this is a regression.
Minecraft version: 1.17.1

**Comment by 2No2Name** [comment]
Can you try adding mixin.world.inline_height=false to the config file and see if it works?

**Comment by ruvaldak** [comment]
> Can you try adding mixin.world.inline_height=false to the config file and see if it works?

Missed this reply. I'll give it a try soon

**Comment by rowanthemodder** [comment]
> 
> 
> Can you try adding mixin.world.inline_height=false to the config file and see if it works?

I've tested this and I can confirm this works.
