### ISSUE TITLE
[Bug] Lithium makes carpet feature flippincactus work wrongly

### ISSUE THREAD

**Issue by 401U** [jellysquid3/Lithium#261]
#### Instructions
With lithium installed, carpet feature `flippincactus` works wrongly.
 [Here shows what's  `flippincactus`](https://github.com/gnembon/fabric-carpet/wiki/Current-Available-Settings#flippincactus)

While using cactus to flip the hopper, it shows that the hopper has changed it's pointing block from A to B, but actually it still pointing to A while working to transfer items.

------------------------

### Version Information
Carpet version: 1.4.43-v210714
Lithium: 0.7.3

### Expected Behavior
After flip the hopper should transfer items to block B.

### Actual Behavior
It renders that the block facing has changed, but works as never been flipped, which is confusing.

### Reproduction Steps
[Video of reproduction](https://youtu.be/3Gk77CTVTvQ)
1. Turn on the carpet feature  `flippincactus` by typing `/carpet flipincactus true`
2. Place two container, e.g., dropper.  Let's call it A and B, and place an hopper facing A.
3. Right click the hopper with cactus in your hand to make it facing B (as rendered).
4. Drop item into hopper, which will appear in A (should in B). 

### Other Information
I'm not sure which to blame, but carpet and lithium just cannot work well together.
Without lithium, the carpet feature can work correctly.

And by the way, thank you for your awesome mod!

**Comment by 2No2Name** [comment]
Does this also affect droppers?

**Comment by 2No2Name** [comment]
No longer need that info, found an issue with lithium's caching.
