### ISSUE TITLE
Blocks in Debug Worlds can be broken client-side

### ISSUE THREAD

**Issue by DreenDex** [jellysquid3/Lithium#262]
### Version Information

**Minecraft**: 1.17.1
**Fabric Loader**: 0.11.6
**Lithium**: lithium-fabric-mc1.17.1-0.7.3 (curseforge)

### Expected Behavior

Blocks in Debug World should not break.

### Actual Behavior

Blocks in Debug World can be broken client-side.

### Reproduction Steps

1. Create new world with Debug type and join it. _(Hold Alt while clicking the "World Type" button)_.
2. Switch your gamemode to creative _(/gamemode creative)_.
3. Try to break any blocks.
- Blocks are broken on client side.

### Other Information

The only mod is Lithium.

**Comment by 2No2Name** [comment]
Debug worlds are not supported by lithium. The vanilla implementation of debug worlds slightly reduces performance of all normal worlds, so removing that is a tradeoff we made.

**Comment by DreenDex** [comment]
I really respect lithium, but I think it violates its principles.
![image](https://user-images.githubusercontent.com/6661231/127747133-737ded87-3907-4fde-8154-738ae9473ccd.png)

**Comment by amnotbananaama** [comment]
> I really respect lithium, but I think it violates its principles.

Note that this is possible in vanilla as well, and Mojang [has indicated](https://bugs.mojang.com/browse/MC-184638) it won't be fixed. The debug world is—as the name indicates—a debugging feature to ensure textures render properly. It is not a part of Minecraft gameplay.

Note that the debug world is only intended to be accessed [in spectator gamemode](https://bugs.mojang.com/browse/MC-58898) when it is impossible to break blocks.

Closing this issue given it has already been answered, and pursuing this further won't lead to productive discussion
