### ISSUE TITLE
Continue to update 1.16

### ISSUE THREAD

**Issue by CanRektYou** [jellysquid3/Lithium#265]
Lots of servers aren't yet updated to 1.17. 
1.16 is still used by a variety of servers
So just continue updating 1.16.
For the love of god, Not Every Server Updates Every Day

**Comment by fooeyround** [comment]
The thing is on the dev side the version has changes and you don't want 2 code it twice and you can most likely use the 1.16.5 version or just use multiconnect.you may crash in single player with this and lambdabeterlights.

**Comment by CanRektYou** [comment]
A lot of servers don’t allow multi connect. for example loka and would it really be that hard to continue with 1.16 until a majority of servers switch to 1.17?

**Comment by jellysquid3** [comment]
What is your point? Old versions of Lithium for Minecraft 1.16 will continue to work regardless of any updates. We typically have only ever supported the latest version because it's much easier, but bug fixes sometimes trickle down to older versions if we think it's relevant.
