### ISSUE TITLE
Minecarts with Inventories Prevent Hoppers' Future Access of Block Entities

### ISSUE THREAD

**Issue by koopaboopa** [jellysquid3/Lithium#266]
### Version Information

lithium-fabric-mc1.17.1-0.7.3

### Expected Behavior

Hoppers are able to interact with both entities and block entities with inventories. When these inventories are removed, hoppers can interact with new inventories that are placed next to it.

### Actual Behavior

After interacting with a minecart with inventory, a hopper no longer seems to interact with block entities such as chests or droppers that are placed in that position. It can still push/pull from other minecarts though. Also, the other "end" of the hopper is not affected. 

### Reproduction Steps

1. Place hopper
2. Place or move a chest minecart into either the top of the hopper or the space where it points
3. Insert items into the minecart or hopper so that at least one item transfer occurs
4. Remove the minecart and place a chest in its previous position
5. Add items into the chest or hopper. The hopper appears unable to move them.

### Other Information

Hoppers can still pick up loose item entities in this state (after removing the block entity). Exiting and reopening the world restores hopper functionality.

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/9501e4857fb61ec9673faad80a1fc7922a8142d7 should fix this.
