### ISSUE TITLE
Client-side time repeatedly changes from current-day to day 1 and back.

### ISSUE THREAD

**Issue by InterstellarOne** [jellysquid3/Lithium#268]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **bug report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version Information

Lithium mc1.17.1-0.7.3

### Expected Behavior

Time passes at a normal rate in the world.

### Actual Behavior

The date and time switches once every second from the current server date to day one, 19:00 and back to present day.

### Reproduction Steps

Join a Spigot multiplayer server. 

### Other Information

- fabric-api-0.37.0+1.17
- lazydfu-0.1.2
- logical_zoom-0.0.11
- malilib-fabric-1.17.1-0.10.0-dev.24
- minihud-fabric-1.17.1-0.19.0-dev.20210707.150016
- modmenu-2.0.3
- seamless-loading-screen-1.3.6+1.17.1
- voicechat-fabric-1.17.1-1.1.2
- Xaeros_Minimap_21.14.0_Fabric_1.17.1

I don't know, however if this is just a spigot issue. This doesn't happen reliably, unfortunately, but it has happened a few times.

https://user-images.githubusercontent.com/63889949/128647569-c9a98b71-ec8e-4574-9be1-c330ba3572cc.mp4

**Comment by 2No2Name** [comment]
Does this problem occur when you uninstall lithium?
