### ISSUE TITLE
Forge Version on Curs

### ISSUE THREAD

**Issue by TheUntamed** [jellysquid3/Lithium#27]
Was the Forge Version for Lithium removed from Curse and why? Will it be back soon? I can't upload my pack on curse using the Forge Version of this mod, it gets rejected.

**Comment by Zoutelande** [comment]
Is this what you're looking for? 
https://github.com/jellysquid3/lithium-forge

**Comment by silversquirl** [comment]
Lithium has been split into separate curseforge pages for fabric and forge. You can find the forge one here: https://www.curseforge.com/minecraft/mc-mods/lithium-forge

**Comment by TheUntamed** [comment]
Hm. It's not possible to find that page via search:
![Screenshot_1](https://user-images.githubusercontent.com/48363903/78451447-f87eaa00-7685-11ea-8e93-973075470ab5.jpg)
And also not via Twitch App.

**Comment by TheUntamed** [comment]
ah, because you have no release version
Thats why Curse rejects my upload containing the alpha file.

**Comment by jellysquid3** [comment]
I've changed the Forge releases to use the Beta type.
