### ISSUE TITLE
Hoppers too fast - changed vanilla mechanic breaking item sorters

### ISSUE THREAD

**Issue by JbhStuff** [jellysquid3/Lithium#274]
As said in title, for a traditional item sorter where a hopper pulls items from below before the above hopper can push to the next hopper, the above hopper works too fast and doesn't give the below hopper time to pull items out.
(E.G breaks mechanic where a hopper will pull items out of a hopper above it before the above hopper can move items to another container)

Other mods I have installed:
Sodium
Sodium extra
Indium
Starlight
Hydrogen
Mod Menu
Lambdabettergrass
Lambdynamiclights
indypets
fabric api
cloth config
callleaves
ctm fabric

Stated behavior stops after uninstalling lithium ONLY

**Comment by Kroppeb** [comment]
What version of fabric api are you using?

**Comment by JbhStuff** [comment]
was running 0.37.x
have updated both fab api and lithium to latest now and is fixed. Thx for your reply
