### ISSUE TITLE
Bee duplication/deletion with lithium

### ISSUE THREAD

**Issue by Youmiel** [jellysquid3/Lithium#275]
### Version Information

> Reporduced with lithium-fabric-mc1.17.1-0.7.4 and also lithium-fabric-mc1.17.1-0.7.3

### Expected Behavior

> The number of bees should remain unchanged.

### Actual Behavior

> The number of bees will increase/decrease after certain operations.

### Reproduction Steps

> 1. Choose a place far from the spawn chunks.
> 2. Place some beehives full of bees (or something like this, e.g. a honey farm).
> 3. Switch daytime to night (just let bees come into/out of the beehives at approximately the same time for easier reproduction).
> 4. When bees come into/out of beehives, log off.
> 5. Repeat some times
> 6. Check the total number of bees inside and outside the bee hives, it will be different.

### Other Information

Other mods: None

**Comment by Altirix** [comment]
![image](https://user-images.githubusercontent.com/19439141/131334275-bd1d87b8-8d06-49d6-b7ed-0564b60ff2a7.png)
can confirm duplicated a hive and used /data get block entity to check the hive when 3/6 bees were in the hive. two bees have the same UUID

from my testing, it seems to duplicate you want to relog as bees are coming out of the hive. to destroy them you want to relog as they go into the hive

Edit: this is also possible in vanilla

**Comment by Youmiel** [comment]
> ![image](https://user-images.githubusercontent.com/19439141/131334275-bd1d87b8-8d06-49d6-b7ed-0564b60ff2a7.png)
> can confirm duplicated a hive and used /data get block entity to check the hive when 3/6 bees were in the hive. two bees have the same UUID
> 
> from my testing, it seems to duplicate you want to relog as bees are coming out of the hive. to destroy them you want to relog as they go into the hive
> 
> Edit: this is also possible in vanilla

Before I open this issue, I tried but failed to reporduce the bug in 1.17.1 vanilla server, so I thought it might be a lithium bug. Is it possible that lithium makes the bug easier to reporduce?

**Comment by 2No2Name** [comment]
Closing as invalid due to being a vanilla bug
