### ISSUE TITLE
Incompatibility with Plant in Jar mod

### ISSUE THREAD

**Issue by Shandoo94** [jellysquid3/Lithium#289]
### Version Information

Fabric 0.11.7
Plant in Jar 2.2.2
Lithium-fabric-mc1.17.1-0.7.4

### Expected Behavior

Saplings placed in the jar will grow and produce wood.

### Actual Behavior

The tree wont grow.
No animation occurs and no drops are produced

### Reproduction Steps

1. install above mentioned mods
2. place sapling and grass block in the jar
3. observe

### Other Information

I also opened an issue at https://github.com/CoolMineman/Plant-In-A-Jar/issues/22
The plant in jar mod works fine without Lithium installed so I think it happens because of some changes to entities or block states on Lithiums side.

**Comment by K0-RR** [comment]
https://github.com/CaffeineMC/lithium-fabric/issues/259

**Comment by Shandoo94** [comment]
It works. 
What does this option disable?

**Comment by 2No2Name** [comment]
Disables caching of the height of chunks and worlds. This feature leads to problems with mods that delay the initialization of the height information or keep changing it. I assume plant in a jar is using some kind of fake world with a custom height to simulate the growth behavior.
