### ISSUE TITLE
Lithium breaks stray cat behavior.

### ISSUE THREAD

**Issue by nogutsnoglory69** [jellysquid3/Lithium#29]
With lithium installed, stray cats are afraid of players in creative and even spectator mode.

**Comment by 2No2Name** [comment]
I fixed this in #31

**Comment by aqualxx** [comment]
Yep jelly pulled in 2No2Name's fix, so this should be fixed (hopefully).

**Comment by maityyy** [comment]
Fixed in https://github.com/jellysquid3/lithium-fabric/commit/2d6104b633c999ec0a745fd71e9589370a87b46b
