### ISSUE TITLE
Support MCMTFabric (Minecraft multi-threading mod)

### ISSUE THREAD

**Issue by BurgBoi** [jellysquid3/Lithium#296]
Whenever I start up a server with both MCMT and Lithium installed, I get this error:
https://pastebin.com/P1sChZvd

There is already an issue posted on the MCMT repo, and in the comments, a contributor stated that Lithium is overwriting a function which makes it fail: https://github.com/himekifee/MCMTFabric/issues/1. I would love to see this mod be compatible with MCMT as that would improve the performance of a server much.

**Comment by 2No2Name** [comment]
try `mixin.world.chunk_access=false` in the config
