### ISSUE TITLE
Crash when entering Nether 1.17.1

### ISSUE THREAD

**Issue by itsdinkd** [jellysquid3/Lithium#297]
As title suggests, when players enter the Nether, there servers are crashing. Reported this to BetterNether dev, and they mentioned that it was possibly due to Lithium on getChunkLithium

**Steps to Reproduce:**
1. Download Another Quality Modpack 2 (Server instance, not sure about Single Player. will test)
2. Enter Nether
3. Crash

Crash log: https://mclist.io/paste/bACRVdecwyrHVvpeTlr9XYkq6UgMRiNk5shxIeSnJ3Ue0g

**Comment by jellysquid3** [comment]
> C2ME Compatibility Module Notice: 
> Contact C2ME before reporting to mod authors if you encountered issues with the following mods: 
> - charm@3.3.2
> - betterend@0.12.2
> You can try disabling compatibility modules for these mods in "c2me-compat.toml" and try reproduce again. 
> Or try reproduce without C2ME. 

Per your crash log... Can you reproduce this issue without C2ME installed?

**Comment by 2No2Name** [comment]
And please try to reproduce this without lithium installed as well. Lithium often shows up in the stacktrace without actually being the reason

**Comment by itsdinkd** [comment]
I disabled lithium, players entered nether perfectly. 
![image](https://user-images.githubusercontent.com/35115304/142934921-09985422-a14a-4287-b7e3-36346f3d8da9.png)

**Comment by itsdinkd** [comment]
> 

Highly doubt its c2me, it is not running in compatibility mode for BetterNether, meaning it does not interact with nether/betternether. only BetterEnd and Charm. Disabling lithium allowed players to enter the Nether, but if you really need me to disable C2me, I will.

**Comment by 2No2Name** [comment]
If removing lithium fixes it, try adding `mixin.world.chunk_access=false` to the lithium config file

**Comment by itsdinkd** [comment]
Update;

Player was able to enter nether immediately after starting server with Lithium disabled. 10 minutes later, a player entered a different portal, server crashed. Lithium still off, they built a new portal, and were able to enter. 

![image](https://user-images.githubusercontent.com/35115304/142939693-7ca1b660-7e18-428c-a63b-4720a9af65a6.png)


I am now disabling C2ME, and enabling Lithium.  will let you guys know what happens.

**Comment by itsdinkd** [comment]
Discussed with one of the C2ME devs and after I re-enabled lithium and disabled c2me, it crashed. we both agreed that it is on fault of C2ME. they are going to update.
