### ISSUE TITLE
Using Lithium alongside a vanilla fabulous shader causes ambient occlusion to flicker

### ISSUE THREAD

**Issue by LucilleTea** [jellysquid3/Lithium#298]
### Version Information

Lithium 0.7.5
[V++ 1.8](https://github.com/Godlander/vpp/releases/tag/1.8) (a fabulous shader resource pack)
No other mods - not Sodium!

### Expected Behavior

The game should render as the resource pack usually does.

### Actual Behavior

The ambient occlusion on blocks flickers when you move.

### Reproduction Steps

Enable the resource pack
Enable fabulous graphics
Load a world
Move

### Other Information

Only occurs on fabulous graphics as it relates to the shader.
Occurs regardless of the smooth lighting setting.
First reported by Reaper Lord in a support thread, unknown hardware. https://discord.com/channels/602796788608401408/912671298478538763/912671300793819137
Confirmed by myself on a GTX 1070, windows.

**Comment by TheReaperLord** [comment]
In case my hardware helps, Windows 10, RTX 2070

**Comment by 2No2Name** [comment]
Maybe this is related to the voxel shape optimizations, I don't have another idea.

Trying adding `mixin.shapes=false` to the config. That disables several optimizations, we can narrow it down later if that works.

**Comment by TheReaperLord** [comment]
I'd try that but I have no idea how I could edit that with just the mod file. I'm not sure if it is related, but I am also experiencing a strange white box reaching from the center to the bottom right only when I look around -45 and 45 degrees (South East and South West.)
![2021-12-10_23 04 55](https://user-images.githubusercontent.com/40416591/145575453-25e44893-87eb-47e2-89fe-0a92e0b63fda.png)
Both of these effects appear to be rotation and location dependant, as I have been able to find some precise positions that trigger each change. When I walk backward into a corner I can trigger the AO issue and when I stand still it stops

**Comment by 2No2Name** [comment]
In your game directory (.minecraft) there should be a config directory with a lithium.properties config file inside. Edit that with a text editor

**Comment by TheReaperLord** [comment]
Doesn't seem to make much of a difference. I did notice it mostly happened while walking, flying doesn't seem to affect it as often. Similar to the rotation thing I noticed earlier.

**Comment by 2No2Name** [comment]
Reproduced with Lithium 0.9.0 and latest V++ on intel integrated, linux, dev environment

**Comment by 2No2Name** [comment]
Seems like adding the line
mixin.math.sine_lut=false
to the lithium properties file in the config directory works around this issue

**Comment by 2No2Name** [comment]
Fixed in https://github.com/CaffeineMC/lithium-fabric/commit/46fede14860b56a13bcb8e76ddf0408fa8dcad09
