### ISSUE TITLE
Latest Lithium version breaks Clientcommands enchantment manipulation

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [jellysquid3/Lithium#301]
### Version Information

lithium-fabric-mc1.17.1-0.7.5.jar

### Expected Behavior

 Clientcommands’ /cenchant command works.

### Actual Behavior

Clientcommands’ /cenchant command does not work - it tells you the info on how many bookshelves you need, and which slot the enchantment will be in, but after enchanting, you do not get the enchantment you tried to get.

### Reproduction Steps

1. Install the latest versions of fabric and Earthcomputer/clientcommands.
2. Try to do enchantment manipulation.
3. Notice that it works.
4. Install lithium as well.
5. Notice that enchantment manipulation does not work.

### Other Information

Clientcommands issue reports: /Earthcomputer/clientcommands/issues/327 
/Earthcomputer/clientcommands/issues/336

**Comment by 2No2Name** [comment]
Lithium does not keep parity with the number or order of RNG calls. Not sure whether this is a `won't fix` but I can probably create a list of optimizations that should be disabled when relying on internal RNG state

**Comment by 2No2Name** [comment]
Is this about the player entity rng?

**Comment by DragonEggBedrockBreaking** [comment]
I believe so

**Comment by DragonEggBedrockBreaking** [comment]
disabling `mixin.ai.nearby_entity_tracking` fixes it

**Comment by FxMorin** [comment]
I am not able to replicate this issue. Does it require you to be on a server, I'm going to guess that it requires entities

**Comment by magneticflux-** [comment]
@DragonEggBedrockBreaking Are you absolutely sure that `mixin.ai.nearby_entity_tracking=false` fixes it AND `mixin.ai.nearby_entity_tracking=true` breaks it again?

A lot of things can alter the player RNG:
- Item dropping (which is what it used to manipulate the value)
- Any sounds playing from the player
- Any particles spawning from the player
- Shoulder-mounted entities (parrots)
- Damage taken (thorns, knockback resist)

**Comment by DragonEggBedrockBreaking** [comment]
> @DragonEggBedrockBreaking Are you absolutely sure that `mixin.ai.nearby_entity_tracking=false` fixes it AND `mixin.ai.nearby_entity_tracking=true` breaks it again?
> 
> A lot of things can alter the player RNG:
> 
> * Item dropping (which is what it used to manipulate the value)
> * Any sounds playing from the player
> * Any particles spawning from the player
> * Shoulder-mounted entities (parrots)
> * Damage taken (thorns, knockback resist)

Yes

**Comment by DragonEggBedrockBreaking** [comment]
> I am not able to replicate this issue. Does it require you to be on a server, I'm going to guess that it requires entities

It is a 1.17 issue, seems to be fixed in 1.18
