### ISSUE TITLE
How do I check that Lithium is actually working?

### ISSUE THREAD

**Issue by rybak** [jellysquid3/Lithium#304]
**Is your feature request related to a problem? Please describe.**
When installing Lithium, I sometimes can't tell if Lithium has "kicked in" or not.

**Describe the solution you'd like**
Maybe something similar to what Sodium does in F3 screen:
![Lithium-sodium-F3](https://user-images.githubusercontent.com/624072/144715591-670d5513-a3ac-46d3-a1d4-c16eaa4ded47.png)
And Fabric-loader:
![fabric-loader-f3](https://user-images.githubusercontent.com/624072/144715649-9522e8b4-4786-4157-948d-e8dba4e1570f.png)

Please include the version of the Jar file that is getting used in the text.

**Describe alternatives you've considered**
Comparing FPS when Lithium's jar is or isn't in the `mods` directory works, but not conclusively.

**Additional context**
Thank you so much for developing and maintaining Lithium. In my setup, it doubles and sometimes triples the FPS: from 15-20 to 30-40 and sometimes 50.

**Comment by DragonEggBedrockBreaking** [comment]
Lithium appears in logs if it works.

**Comment by rybak** [comment]
> Lithium appears in logs if it works.

Thank you, that works. However, a more user-friendly solution would be nice.

**Comment by Eiion** [comment]
> Thank you, that works. However, a more user-friendly solution would be nice.

I'd agree with that. Adding the info to the F3 screen would be nice.

**Comment by K0-RR** [comment]
>I'd agree with that. Adding the info to the F3 screen would be nice.

The next thing you will see is every mod adding something there.

**Comment by jellysquid3** [comment]
We could probably add a `/lithium version` command or something to the tune of that. But adding things to the F3 screen should be highly discouraged... We do so in Sodium only because it has useful renderer information to convey there.

**Comment by 2No2Name** [comment]
I think this is an enhancement for the mod loader. Other mod loaders allow users to see the list of loaded mods, I am not aware of such a fabric feature.
If we add a lithium command, we can also use it for editing the config file

**Comment by DragonEggBedrockBreaking** [comment]
> I think this is an enhancement for the mod loader. Other mod loaders allow users to see the list of loaded mods, I am not aware of such a fabric feature.

Well remember that on the client, for fabric, you can also use ModMenu to check what mods are loaded.

**Comment by 2No2Name** [comment]
So check console output / logs or install a mod that displays it in the gui.
