### ISSUE TITLE
Univeral Graves Mod along with lithium causes client crashes and chunks failing to get sent

### ISSUE THREAD

**Issue by adaliea** [jellysquid3/Lithium#306]
### Version
 lithium-fabric-mc1.18-0.7.6-rc1

### Reproduction Steps
1. Install the universal graves mod along with lithium.
2. Place your spawn near-ish to where you will die.
3. Have any item in your inventory (this is so that the grave spawns in)
3. Run /kill
4. Observe client crash (Note: I'm running lithium on a dedicated server)
5. Restart Minecraft and rejoin the world
6. You will notice that a. the chunk with the player skull has not loaded, b. the chunk has loaded, but the player skull is not visible
7. Disconnect/Reconnect and notice that the bug does not go away. If fact it will sometimes switch between the 2 states above.

### Crash Report File
https://gist.github.com/varun7654/d30b429f8ca5afa9b48b02c92eff81a5 (from a client connected to the server)

### Minecraft Save
N/a

### Additional Information
Server Mods:
![image](https://user-images.githubusercontent.com/59785640/145497299-d064a70d-3240-4234-a0a9-2f51ea4a1e12.png)
There are no errors that are printed on the server

Client Mods:
![image](https://user-images.githubusercontent.com/59785640/145497566-4678c25d-b2ae-4f20-827c-2e7442f5e47a.png)

I can confirm that the crash does not happen with lithium uninstalled.

**Comment by 2No2Name** [comment]
You can try adding these to the lithium config file, one at a time, to see which may cause the crash:

`mixin.chunk.no_locking=false`
`mixin.chunk.palette=false`

**Comment by Patbox** [comment]
Universal Graves author here. This can be closed, as issue was fixed long time ago with 1.2.2 update
