### ISSUE TITLE
Lithium crashes in 1.18.1 - "Mixin transformation of net.minecraft.class_3898 failed"

### ISSUE THREAD

**Issue by AViewFromTheTop** [jellysquid3/Lithium#307]
Version: lithium-fabric-mc1.18-0.7.6-SNAPSHOT.jar

How to reproduce: Open the game in 1.18.1, and open a singleplayer world.

Crash report: [crash-2021-12-10_10.07.54-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/7693676/crash-2021-12-10_10.07.54-server.txt)

Save: This happens in any world I create with Lithium, and any world created in Vanilla.

Additional Information: This crash does not happen with Lithium, and no other mods were installed when this crash occured.
The Minecraft Launcher states: "The game crashes whilst exception in server tick loop
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3898 failed
Exit Code: -1"
Newest fabric loader was used.
EDIT: The newest dev build fixed this bug.
"With the newest dev build the game doesn't crash, but now you'll be stuck on the "Saving World" screen when opening a world. The game also becomes unresponsive and must be closed with Task manager."
-Me before I realized it was actually because I was using a dev build of Sodium with Iris

**Comment by Josiadit** [comment]
Here too

**Comment by AViewFromTheTop** [comment]
This issue still persists with the latest dev build, this time it's stuck on the "Saving World" screen when you try to open a world. I'll change the title of the report to match the new issue.
Edit: i was dumb
