### ISSUE TITLE
Lithium mc1.18-0.7.6-rc1 not compatible with Minecraft 1.18.1

### ISSUE THREAD

**Issue by PweSol** [jellysquid3/Lithium#311]

**Comment by AViewFromTheTop** [comment]
I'm pretty sure this is fixed in the latest dev build. Does this version work? [https://github.com/CaffeineMC/lithium-fabric/actions/runs/1565397846](https://github.com/CaffeineMC/lithium-fabric/actions/runs/1565397846)

**Comment by z3roco01** [comment]
It's fixed
