### ISSUE TITLE
[Serious Bug] Black World

### ISSUE THREAD

**Issue by nsde** [jellysquid3/Lithium#312]
![Screenshot](https://user-images.githubusercontent.com/84771149/145710096-07e2273c-3b65-4d65-8201-c09d456f64e4.png)

I'm not the only one facing this issue, I've seen others, take a look here
https://github.com/Fabulously-Optimized/fabulously-optimized/issues/186

### Version Information

> AMD GPU and CPU
> Linux Ubuntu 21 PopOS!
> **0.7.6-rc1**

### Expected Behavior

> Normal world lightning

### Actual Behavior

> World appears black

### Reproduction Steps

> Unknown, comes with installation? Incompatible with Iris/LambdaDynamicLightning?

### Other Information

> Issue from: https://github.com/Fabulously-Optimized/fabulously-optimized/issues/186
> Log 1 https://github.com/Fabulously-Optimized/fabulously-optimized/files/7698622/tlauncher_12_12_2021_16_32_42.log
> Log 2 https://github.com/Fabulously-Optimized/fabulously-optimized/files/7698623/latest.log

**Comment by Ristovski** [comment]
Can this be closed as per https://github.com/Fabulously-Optimized/fabulously-optimized/issues/186#issuecomment-991899555 ?
