### ISSUE TITLE
please upd 1.18.1 Lithium. crash.. fabric loader 0.12.11

### ISSUE THREAD

**Issue by Shelbikk** [jellysquid3/Lithium#313]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **crash report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version

> Replace this text with the exact version of the mod you are using. Every part of the version is important! If you
> do not know what version you are using, look at the file name in your "mods" folder.
>
> Example: lithium-fabric-mc1.16.5-0.6.4
> 
### Reproduction Steps

> Provide information on how to reproduce this game crash. You can either fill this section in like the example below
> or do something else -- just make sure your instructions are minimal and clear, as other people will need to be able
> to replicate your issue.
>
> Example:
> 1. Place a Redstone Lamp in front of a Redstone Repeater
> 2. Use a Lever to activate the Redstone Repeater
> 3. Nothing happens

### Crash Report File

> Upload your crash report file as an attachment to this issue (drag-and-drop) or to a service such as GitHub
> Gist (paste a link) and replace this section. This information is critical in resolving your issue!
> 
> Tip: Messages like "Exit code 0" from your launcher are not what you're looking for. If your launcher does not
> provide a button to view the most recent crash report, check your game's "crash-reports" folder for the most recent
> crash report file.

### Minecraft Save

> If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

### Additional Information

> Provide any additional information or context which may be relevant to the issue. If you have none to add,
> you can remove this section. If possible, please confirm that the crash does not happen when Lithium is not installed.

**Comment by 2No2Name** [comment]
Please fill in the issue template
