### ISSUE TITLE
Minecraft fails to start with Lithium installed

### ISSUE THREAD

**Issue by Pectacular** [jellysquid3/Lithium#316]
Version: lithium-fabric-mc1.18.1-0.7.6

Reproduction Steps

1. Install Fabric
2. Install Lithium
3. Launch Minecraft
4. Minecraft crashes

Crash Report File

https://paste.ee/d/afJMj

Additional Information

This does not happen with Lithium 0.7.6 rc-1 on Minecraft version 1.18

**Comment by 2No2Name** [comment]
You can try adding `mixin.entity.inactive_navigations=false` to the lithium config.

**Comment by Pectacular** [comment]
thanks Minecraft is now able to launch
