### ISSUE TITLE
Critical Injection Failure on startup

### ISSUE THREAD

**Issue by atyshka** [jellysquid3/Lithium#323]
### Version

lithium-fabric-mc1.18.1-0.7.6

### Reproduction Steps

Launching a clean server, no datapacks, no mods other than lithium. The game crashes, things work fine if I remove lithium. Looking at the crash backtrace, it seems like there is a mismatch in where it's trying to inject code?
`
[17:15:34] [main/ERROR]: Mixin apply for mod lithium failed lithium.mixins.json:entity.inactive_navigations.EntityNavigationMixin -> net.minecraft.class_1408: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on updateListeningState could not find any targets matching 'Lnet/minecraft/class_1408;method_6356()V' in net.minecraft.class_1408. Using refmap mixins.lithium.refmap.json [PREINJECT Applicator Phase -> lithium.mixins.json:entity.inactive_navigations.EntityNavigationMixin -> Prepare Injections -> -> handler$zda000$updateListeningState(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]`

### Crash Report File

[latest.log](https://github.com/CaffeineMC/lithium-fabric/files/7741253/latest.log)

### Minecraft Save

This issue happens on a clean world, not save specific

### Additional Information

Here is my launch command

`java -Xms128M -Xmx3072M -Dterminal.jline=false -Dterminal.ansi=true -jar fabric-server-launch.jar`

**Comment by 2No2Name** [comment]
Try adding
mixin.entity.inactive_navigations=false
to the lithium config file

**Comment by atyshka** [comment]
Where should that file be?

**Comment by atyshka** [comment]
> Try adding
> mixin.entity.inactive_navigations=false
> to the lithium config file

This works! But why? And what effects does it have?

**Comment by atyshka** [comment]
Actually, after a few seconds of joining the world as a player I get this error: 

[19:27:31] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'boolean net.minecraft.class_3898.method_39975(int, int, int, int, int)'

Again there seems to be some mismatch of what Lithium is expecting vs my java binary

**Comment by 2No2Name** [comment]
It looks like you are starting the game with 1.18 minecraft instead of 1.18.1 . I suggest to reinstall your server

**Comment by atyshka** [comment]
Fabric is using 1.18.1:

Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[19:30:53] [INFO] [FabricLoader/GameProvider]: Loading Minecraft 1.18.1 with Fabric Loader 0.12.9

I am downloading the server jar from this page: 
https://fabricmc.net/use/server/

**Comment by 2No2Name** [comment]
Can you try updating fabric loader?

**Comment by atyshka** [comment]
Ahh, replacing it seems to work? Even though the old one was also 1.18.1 with loader 0.12.9? Weird. Sorry about that

**Comment by atyshka** [comment]
Nope, still crashing with the same error after playing a bit

**Comment by atyshka** [comment]
Should I try just zipping the whole server directory and seeing if you can reproduce that way?

**Comment by 2No2Name** [comment]
Can you first get me a full crash report (should be in crash-reports directory), not the latest.log?

**Comment by atyshka** [comment]
Interesting. Now it finally works if I use the old installer method for fabric (running the jar and generating files) rather than the drop-in jar method that they are newly promoting. I wonder why?
