### ISSUE TITLE
Incorrect Dispenser/Hopper Behavior (disregard please)

### ISSUE THREAD

**Issue by Waterman1776** [jellysquid3/Lithium#328]
### Version Information

lithium-fabric-mc1.18.1-0.7.6

### Expected Behavior

Built a honey farm that dispenses bottle through behives.  Expect the bottle to be dispensed, collect the honey, and then be collected by the hopper below the hive.

This behavior can be replicated in a minecraft instance with no mods.

### Actual Behavior

The harvest honey bottle is not collected by the hopper, but is placed back into the dispenser.

### Reproduction Steps

1. Place Dispenser facing down in to beehive with a honey level of 5.
2. Place hopper below beehive.
3. Add glass bottles to one slot of the dispenser.
4. Place redstone torche next to dispenser.

### Other Information

.............................

**Comment by FxMorin** [comment]
Just tried it in vanilla. The bottle goes back into the dispenser. It does not go into the hopper, so this is just vanilla behavior.
The bottle will only drop if there are no spaces available in the dispenser. Such as if every slot has 64 glass bottles.

**Comment by Waterman1776** [comment]
> 

I tried it again in vanilla.  It did just as you're saying.  Now I've seen it go both ways.  Thanks for your time.

**Comment by Pectacular** [comment]
Shouldn't this issue be closed?
