### ISSUE TITLE
java.lang.ClassCastException I Ticking entity

### ISSUE THREAD

**Issue by TheButterbrotMan** [jellysquid3/Lithium#330]
### Version

> Lithium 0.7.6
### Reproduction Steps

> Random

### Crash Report File
https://pastebin.com/JAwqZ4um

### Additional Information

https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment]
Probably linked to #329

**Comment by 2No2Name** [comment]
Duplicate of #329
