### ISSUE TITLE
Mixin apply for mod lithium failed

### ISSUE THREAD

**Issue by ChristopherTheBoss** [jellysquid3/Lithium#331]
### Version
lithium-fabric-mc1.18.1-0.7.6

### Reproduction Steps

1. Update to Fabric Loader 1.12.12 with MultiMC
2. Launch & Crash
3. Revert to 1.12.11 with MultiMC
4. Launch successful, but LambdaBetterGrass requires 1.12.12

### Crash Report File

[Paste](https://paste.ee/p/3uOap)

### Additional Information

See #323 for similar issue with server, unclear resolution.

**Comment by ChristopherTheBoss** [comment]
This is probably an issue with @FabricMC but I'm helpless and figured you all wouldn't blame me for asking here.

**Comment by 2No2Name** [comment]
No, it is a C2ME mixin
