### ISSUE TITLE
1.18.1 Hopper not inserting items into Botania's Crafty Crate when more than 1 item is in the stack with Lithium

### ISSUE THREAD

**Issue by jezzballin** [jellysquid3/Lithium#333]
------------------------

### Version Information

Minecraft 1.18.1
Fabric Loader 0.12.12
Lithium 0.7.6
Botania 1.18.1-427-FABRIC

Modlist:
        - additionaladditions 3.0.1
	- adorn 3.0.0+1.18.1
	- advanced_runtime_resource_pack 0.3.7 via chisel
	- appleskin mc1.18-2.2.0
	- architectury 3.2.51
	- balm-fabric 2.3.0+0
	- bewitchment 1.18-4
	- blue_endless_jankson 1.2.1 via jankson
	- botania 1.18.1-427-FABRIC
	- cardinal-components-base 4.0.1 via polymorph
	- cardinal-components-block 4.0.1 via botania
	- cardinal-components-entity 4.0.1 via polymorph
	- cardinal-components-item 4.0.1 via polymorph
	- chisel 1.4.4
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.1.48
	- clumps 8.0.4
	- collective-fabric 3.14
	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- comforts 1.0.0-1.18
	- controllermod 1.18.1-6.0.2-Fabric
	- doubledoors-fabric 3.1
	- dungeons_arise 2.1.49b-fabric
	- fabric 0.45.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cd65 via fabric
	- fabric-api-lookup-api-v1 1.5.0+17be577f65 via fabric
	- fabric-biome-api-v1 6.0.1+ded849a965 via fabric
	- fabric-command-api-v1 1.1.6+3ac43d9565 via fabric
	- fabric-commands-v0 0.2.5+b4f4f6cd65 via fabric
	- fabric-containers-v0 0.1.18+d154e2c665 via fabric
	- fabric-content-registries-v0 0.4.5+6f53a73d65 via fabric
	- fabric-crash-report-info-v1 0.1.8+3ac43d9565 via fabric
	- fabric-dimensions-v1 2.1.7+43d2957165 via fabric
	- fabric-entity-events-v1 1.4.5+6b21378a65 via fabric
	- fabric-events-interaction-v0 0.4.16+bfa23f1765 via fabric
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cd65 via fabric
	- fabric-game-rule-api-v1 1.0.10+3ac43d9565 via fabric
	- fabric-item-api-v1 1.3.0+691a79b565 via fabric
	- fabric-item-groups-v0 0.3.3+3ac43d9565 via fabric
	- fabric-language-kotlin 1.7.1+kotlin.1.6.10
	- fabric-lifecycle-events-v1 1.4.10+c15ca33565 via fabric
	- fabric-loot-tables-v1 1.0.8+3ac43d9565 via fabric
	- fabric-mining-level-api-v1 1.0.3+3ac43d9565 via fabric
	- fabric-mining-levels-v0 0.1.7+b4f4f6cd65 via fabric
	- fabric-networking-api-v1 1.0.18+3ac43d9565 via fabric
	- fabric-networking-v0 0.3.5+b4f4f6cd65 via fabric
	- fabric-object-builder-api-v1 1.11.0+3b82842e65 via fabric
	- fabric-object-builders-v0 0.7.8+3ac43d9565 via fabric
	- fabric-particles-v1 0.2.9+526dc1ac65 via fabric
	- fabric-permissions-api-v0 0.1-SNAPSHOT via bewitchment
	- fabric-registry-sync-v0 0.8.6+533be9ba65 via fabric
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d765 via fabric
	- fabric-rendering-fluids-v1 0.1.18+3ac43d9565 via fabric
	- fabric-resource-loader-v0 0.4.11+3ac43d9565 via fabric
	- fabric-screen-handler-api-v1 1.1.11+3ac43d9565 via fabric
	- fabric-structure-api-v1 2.0.8+295197a765 via fabric
	- fabric-tag-extensions-v0 1.2.5+3ac43d9565 via fabric
	- fabric-tool-attribute-api-v1 1.3.4+7de09f5565 via fabric
	- fabric-transfer-api-v1 1.5.6+b4f4f6cd65 via fabric
	- fabricloader 0.12.12
	- farmersdelight 1.18.1-0.2.0
	- fastfurnace 1.18-4
	- fiber 0.23.0-2 via botania
	- forgeconfigapiport 3.1.0
	- goosik-config 0.2.0 via winterly
	- hologram-api 0.2.1+1.18-pre5 via universal-graves
	- impersonate 2.4.0 via bewitchment
	- jankson 4.0.0+j1.2.0 via adorn
	- java 17
	- kanos_config 0.1.4+1.14.4-1.17.1 via pehkui
	- krypton 0.1.6
	- libcd 3.0.3+1.16.3 via adorn
	- libgui 5.1.0+1.18 via additionaladditions
	- libninepatch 1.1.0 via libgui
	- lithium 0.7.6
	- minecraft 1.18.1
	- omega-config 1.0.8 via repurposed_structures
	- org_jetbrains_kotlin_kotlin-reflect 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.5.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.1 via fabric-language-kotlin
	- owo 0.3.10+1.18
	- packet_tweaker 0.2.0+1.18-pre1 via polymer
	- patchouli 1.18.1-61-FABRIC
	- pehkui 3.1.0+1.14.4-1.18.1
	- phosphor 0.8.1
	- placeholder-api 1.1.3+1.17.1 via universal-graves
	- playerabilitylib 1.5.0 via bewitchment
	- polymer 0.2.0-beta.8+1.18 via universal-graves
	- polymer-legacy 0.1.9+0.2.0-beta.8+1.18 via polymer
	- polymorph 0.0.16-1.18.1
	- reach-entity-attributes 2.1.1 via bewitchment
	- repurposed_structures 3.1.12+1.18.1
	- roughlyenoughitems 7.1.357
	- seedfix 1.0.0 via terralith
	- server_translations_api 1.4.8+1.18-pre1 via universal-graves
	- sgui 1.0.0-rc6+1.18-pre5 via universal-graves
	- simple_backpack 1.2.27
	- small_artifacts 0.1.0-1.18
	- staffofbuilding 1.4.1-1.18.1
	- step-height-entity-attribute 1.0.0 via bewitchment
	- terraform-wood-api-v1 2.0.2 via bewitchment
	- terralith 2.0_b0.1.8
	- trinkets 3.1.0
	- unionlib 1.18.1-6.1.3-Fabric
	- universal-graves 1.2.2+1.18
	- waystones 9.0.1
	- winterly 0.3.1
	- wthit 4.4.0
	- xaerominimap 21.22.5
	- xaeroworldmap 1.18.7

(https://www.curseforge.com/minecraft/modpacks/fabric-fun-pack) Curseforge link for testing. 

### Expected Behavior

Hopper facing into Botania's Crafty Crate should insert items from stacks in hopper, one at a time into the slots in its inventory, outputting the recipe when completed. 

### Actual Behavior

Hopper Facing into Botania's Crafty Crate will not insert items unless they are a single item in a stack (ie, 1 wheat vs any more than 1 wheat

### Reproduction Steps

1.Hopper>Crafty Crate in any orientation
2. Add 2+ items to the first hopper slot
3. The Crafty Crate will not accept items from the Hopper

### Other Information

If items are inserted into the Hopper one at a time, the Crafty Crate accepts the items/the Hopper pushes the items, I can't tell which. 

### Latest log file
https://gist.github.com/jezzballin/d744d7a9177f2eb0b9c4d7702c5634cc

###

**Comment by 2No2Name** [comment]
Fixed on Botania's side
