### ISSUE TITLE
Azalea Tree generation differs from vanilla.

### ISSUE THREAD

**Issue by Sup2303** [jellysquid3/Lithium#334]
### Version Information

lithium-fabric-mc1.18.1-0.7.7.jar

### Expected Behavior

2 Azalea Trees in the given seed at the given coords always generate.

### Actual Behavior

Sometimes only one or the other or neither generate.

### Reproduction Steps

1. Create new world with seed -1975672861532093637
2. Teleport to X:85 Y:80 Z:-20
3. Sometimes both trees do not generate.

### Other Information

No other mods.
Fabric Loader 0.12.12

**Comment by 2No2Name** [comment]
How many times did you try this in vanilla?

**Comment by 2No2Name** [comment]
I got a single tree in vanilla

**Comment by Sup2303** [comment]
I tried it 15-20 times in both vanilla and with lithium, guess its more common with lithium or just got lucky with vanilla.
