### ISSUE TITLE
Suffocation Optimization incompatible with origins mod

### ISSUE THREAD

**Issue by WigglePig** [jellysquid3/Lithium#336]
I understand this is not a problem with vanilla Minecraft, and thus this should not be a high-priority issue.  However, I would assume other mods that deal with being inside blocks would experience similar problems when used with Lithium.

### Version Information
lithium-fabric-mc1.18.1-0.7.7.jar

### Expected Behavior
Players using the Phantom origin from the Origins mod should be able to phase through the ground without suffocating.

### Actual Behavior
Players using the Phantom origin from the Origins mod take suffocation damage while phasing through blocks.

### Reproduction Steps
Install Origins for 1.18.1, as well as Lithium for 1.18.1.  Go into a singleplayer world, and select the Phantom origin.  Try to phase through blocks in survival or adventure.

### Other Information
Other mods being used:
Farmer's Delight
Medieval Weapons
Extra Origins
Medieval Origins
Mob Origins
Simple Voice Chat

**Comment by 2No2Name** [comment]
I think we had this exact same issue before. Adding `mixin.entity.collisions.suffocation=false` to the lithium properties file to disable the optimization might work around it

**Comment by WigglePig** [comment]
Hey, thanks!  It reverted suffocation to vanilla.  This will be a good solution for now.

**Comment by RelaxAdrian** [comment]
Instructions on  how to locate the file? I would also like to resolve this issue. Thank you in advance.

**Comment by 2No2Name** [comment]
.minecraft/config/lithium.properties (open with a text editor)

**Comment by NetheriteNinja10** [comment]
This did not work for me.  I am using the same mods as the original poster.  The lithium conf file will not save or load.  I tried stopping and starting the server I tried /reload.  It doesnt work.  What do I do?
