### ISSUE TITLE
Make menus use minecraft widgets

### ISSUE THREAD

**Issue by Shadowblitz16** [jellysquid3/Lithium#337]
**Is your feature request related to a problem? Please describe.**
Instead of a menu like this...
![image](https://user-images.githubusercontent.com/2453707/148493801-f82c1caf-19c3-4674-8bc4-a740ffe552c0.png)

make the menu look more like this...
![image](https://user-images.githubusercontent.com/2453707/148493829-5c8f95b1-729f-4e05-8dfb-cd8142642974.png)

**Comment by 2No2Name** [comment]
Lithium does not have to do anything with the above UI

**Comment by Shadowblitz16** [comment]
wait then what mod does? its either lithium, sodium, or phosphor

**Comment by Pectacular** [comment]
Sodium changes the UI, not Lithium. If you want the vanilla video settings menu with Sodium, take a look at [this](https://www.curseforge.com/minecraft/mc-mods/better-sodium-video-settings-button) mod.

**Comment by Shadowblitz16** [comment]
ok ty
