### ISSUE TITLE
Vanilla "/data merge" Command Breaks Furnace & Hopper Interactions

### ISSUE THREAD

**Issue by jpeterik12** [jellysquid3/Lithium#338]
### Version Information

Lithium: lithium-fabric-mc1.18.1-0.7.7
Fabric Loader: 0.12.12
Minecraft: 1.18.1
### Expected Behavior
Hoppers pointed into and drawing from a furnace should be able to push and pull after the furnace is modified with commands.

### Actual Behavior

The hoppers attached to the furnace no longer function.

### Reproduction Steps

1. Have a furnace with hoppers pointing into the top and drawing from the bottom
2. Fill the top hopper
3. Fuel the furnace with coal
4. Run `data merge block [Furnace Coords] {CookTime:0}`
5. Notice that the hoppers stop functioning

### Other Information

N/A

**Comment by 2No2Name** [comment]
Should be fixed in https://github.com/CaffeineMC/lithium-fabric/actions/runs/1674390266
