### ISSUE TITLE
Latest commit "expand alloc patches" crashes when paired with krypton 

### ISSUE THREAD

**Issue by NotADinosaur** [jellysquid3/Lithium#339]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **bug report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version Information

>  latest commit 0.7.7-snapshot ( https://github.com/CaffeineMC/lithium-fabric/actions/runs/1699376632 )

### Expected Behavior

> world should load

### Actual Behavior

> when joining world, the game will crash

### Reproduction Steps

> 1: attempt to join a singleplayer world (game works as expected when joining a multiplayer server)
> 2: the game will crash

### Other Information

> crash report here: [crash-2022-01-16_16.58.21-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/7878379/crash-2022-01-16_16.58.21-server.txt)

**Comment by DragonEggBedrockBreaking** [comment]
That’s not an official lithium commit, that’s a pull request (#314)
