### ISSUE TITLE
[1.18.1] Crash in singleplayer

### ISSUE THREAD

**Issue by Flemmli97** [jellysquid3/Lithium#342]
### Version

mc: 1.18.1
lithium: lithium-fabric-mc1.18.1-0.7.7
fabric loader version is 0.12.12

### Reproduction Steps

Launch game with lithium and create/join a single player world.
No other mods are installed.

### Crash Report File

[https://gist.github.com/Flemmli97/80b4f722372f42ca16b54cb260a85008](https://gist.github.com/Flemmli97/80b4f722372f42ca16b54cb260a85008)

### Additional Information

This does not happen on a server. Created a server with lithium installed just fine.

**Comment by 2No2Name** [comment]
If there are really no other mods installed, try reinstalling fabric
