### ISSUE TITLE
Tried to fix the Phantom origin from suffocating in walls but now my server is crashing

### ISSUE THREAD

**Issue by Pipsissewa** [jellysquid3/Lithium#343]
### Version

>  lithium-fabric-mc1.18.1-0.7.6.jar

I'm playing and running an origins Minecraft server through shockbyte and the Phantom mob keeps suffocating to death in walls when i try to phase through. I configured the file with mixin.entity.collisions.suffocation=false and now my server is just crashing.
### Crash Report File

https://paste.shockbyte.com/uceqihakelohotupomuc

**Comment by LucilleTea** [comment]
Support issue handled in discord, no bug
