### ISSUE TITLE
Potential Lithium hanging on chunk load [1.18.1 crash]

### ISSUE THREAD

**Issue by itsdinkd** [jellysquid3/Lithium#346]
I was told that this might be due to Lithium causing stalls on chunk load and making watchdog crash

in case this person is correct, here is the crash log

https://gist.github.com/itsdinkd/ffbabd815c9d954616ea96ff87571da8

**Comment by 2No2Name** [comment]
There is not reason to believe this is caused by lithium in the crash log. Lithium modifies getChunk and appears in the stacktrace, but the modifications are minor and not able to cause a deadlock.
