### ISSUE TITLE
Lithium freezes client when used on server with Immersive Cursedness

### ISSUE THREAD

**Issue by secondfry** [jellysquid3/Lithium#347]
### Version Information

Clientside (M1, aarch64 java via ManyMC, but probably is unrelated, because in #173 there are same actual behaviour):
Lithium config (tl;dr everything is disabled, except `mixin.entity.collisions.suffocation`) – https://pastebin.com/xk7Gzumv
Client log – https://pastebin.com/jvqbd363, tl;dr:
```
[18:32:22] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.2
[18:32:22] [main/INFO]: Loading 4 mods:
	- fabricloader 0.13.2
	- java 17
	- lithium 0.7.7
	- minecraft 1.18.1
```

Serverside:
Mods list – https://pastebin.com/5XZrnrEM, tl;dr:
```
[18:30:56] [main/INFO]: Loading Minecraft 1.18.1 with Fabric Loader 0.13.2
[18:30:56] [main/INFO]: Loading 40 mods:
        - autoconfig1u 3.3.1 via immersive-cursedness
        - fabric 0.46.4+1.18
... all fabric api little mods ...
        - fabricloader 0.13.2
        - immersive-cursedness 1.4.5
        - java 17
        - minecraft 1.18.1
```

### Expected Behavior
Ability to look at nether portal and not freeze.

### Actual Behavior
Looking at nether portal causes client to freeze without crashing.

### Reproduction Steps
1. Setup server with Immersive Cursedness.
2. Setup client and disable all optimizations except `mixin.entity.collisions.suffocation`.
3. Look at portal and freeze.
4. Enable all optimizations and disable `mixin.entity.collisions.suffocation`.
5. Look at portal and do not freeze.

### Other Information
IDK, probably everything is provided above already.

**Comment by secondfry** [comment]
Eh, as it always happens, after opening the issue, I've noticed that I forgot to prefix all configuration options with `mixin.`. Adding that actually stops freeze from happening. BRB with option which freezes client.

**Comment by secondfry** [comment]
Updated info in first post to reflect that `mixin.entity.collisions.suffocation` is causing the issue.

**Comment by 2No2Name** [comment]
Set mixin.chunk.block_counting=false in the config, you disabled an optimization that that depends on

**Comment by secondfry** [comment]
@2No2Name, I'm terribly sorry for not double checking everything before submitting the issue, but are you sure that is related? I'm currently observing no freezes with just `mixin.entity.collisions.suffocation=false` in otherwise empty config file, while removing it or setting it to `true` makes game freeze.

**Comment by 2No2Name** [comment]
The block counting dependency was accidental, but it caused a crash

**Comment by 2No2Name** [comment]
If it works for you now, I would keep it that way. I do not see how the suffocation optimization is supposed to cause a freeze,

**Comment by JosueGalRe** [comment]
I can confirm that setting `mixin.entity.collisions.suffocation=false` will prevent the client to crash.

**Comment by davidalb97** [comment]
I could reproduce the issue and I can confirm that setting ```mixin.entity.collisions.suffocation=false``` fixes the freeze.

**Comment by TheEpicBlock** [comment]
Just tested it, it seems it has been fixed. Probably due to e3c952d
