### ISSUE TITLE
[1.18.1] Mixin crash

### ISSUE THREAD

**Issue by Flemmli97** [jellysquid3/Lithium#349]
### Version

mc: 1.18.1
lithium: lithium-fabric-mc1.18.1-0.7.7
fabric loader version is 0.13.3

### Reproduction Steps

Enable -Dmixin.debug=true via jvm args
Launch game with lithium and create/join a world.
No other mods are installed.

### Crash Report File

[https://gist.github.com/Flemmli97/80b4f722372f42ca16b54cb260a85008](https://gist.github.com/Flemmli97/80b4f722372f42ca16b54cb260a85008)

### Additional Information

Update and related to #342
If -Dmixin.debug=true is not enabled it doesnt crash
Since its related to debugging not too sure on the importance of this but ill report it anyway

**Comment by 2No2Name** [comment]
Added a missing remap=false, maybe this fixes this issue
