### ISSUE TITLE
Crashes with gravity changer mod

### ISSUE THREAD

**Issue by RoguSpanish** [jellysquid3/Lithium#350]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **crash report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version

>lithium-fabric-mc1.18.1-0.7.7
>GravityChanger-0,3.0-1.18.1

### Reproduction Steps

>just run the game with these 2 mods on fabric and it will happen

### Crash Report File

>
[2022-02-22-1.log.gz](https://github.com/CaffeineMC/lithium-fabric/files/8127198/2022-02-22-1.log.gz)

### Minecraft Save

> If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

### Additional Information

> Provide any additional information or context which may be relevant to the issue. If you have none to add,
> you can remove this section. If possible, please confirm that the crash does not happen when Lithium is not installed.

**Comment by 2No2Name** [comment]
Try adding 
mixin.entity.collisions.movement=false
to the lithium.properties file in the config folder

**Comment by RoguSpanish** [comment]
> 

i added it but it didnt seem to work unless i added it wrong 
![image](https://user-images.githubusercontent.com/96929033/155413856-ac0641f6-9723-4567-8ab0-53f9aef1ecb8.png)

**Comment by 2No2Name** [comment]
You added it correctly, but you need to post another crash report

**Comment by ToyotaMatchstickCollective** [comment]
> You added it correctly, but you need to post another crash report

I'd give one but it doesn't generate one for me, which is strange (this is after added the line to the config)
this is all it gives.
![image](https://user-images.githubusercontent.com/102612648/160657512-f8d949dd-8453-476e-aad5-1c012ebb9425.png)

**Comment by 2No2Name** [comment]
Can you test whether this issue occurs when you change nothing besides removing lithium from the mods folder?

**Comment by ToyotaMatchstickCollective** [comment]
Yep, with lithium removed, there is no crashes, only issue is, this modpack I'm using is dependent on lithium (I have no idea how it didn't crash)

**Comment by ToyotaMatchstickCollective** [comment]
(except it does crash when loading a world, so yes, it is dependent)
Nevermind, it doesnt crash

**Comment by ToyotaMatchstickCollective** [comment]
> (except it does crash when loading a world, so yes, it is dependent)
> Nevermind, it doesnt crash

Okay so it wasn't a dependent but the server owner still wishes to keep lithium,
Ive tested around fully and yes the crash is only with lithium and with the gravity mod in.

**Comment by ItsPoisonRed** [comment]
I have this same problem, and I tried to use the config fix, but it didn't work. Here is the log.
[latest.log](https://github.com/CaffeineMC/lithium-fabric/files/11132241/latest.log)
I only ran Gravity Changer, Fabric API, Cloth Config, and Lithium, all the latest versions in Minecraft 1.18.1.

**Comment by 2No2Name** [comment]
Add mixin.entity.collisions.suffocation=false to the lithium config.

Mod authors can automatically disable this mixin as well. https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json
