### ISSUE TITLE
Hopperminecart dont drop items into hopper under it

### ISSUE THREAD

**Issue by f0kx** [jellysquid3/Lithium#351]
### Version Information

lithium-fabric-mc1.18.1-0.7.8

### Expected Behavior

Hoppercart should drop items to hoppers under it.

### Actual Behavior

Hopperminecarts dont drops items into hopper under it

### Reproduction Steps

i place a chest a hopper facing into chest on the hopper a rail and on the rail a hopperminecart. i put items into the minecart and it should drop items under it into the hopper and than into the chest ... but it wont work!

**Comment by 2No2Name** [comment]
Hopper minecarts do not transfer items out, but the hopper below it can pull items from it. Make sure that the hopper is able to transfer items (it is not disabled by redstone, including a detector rail).

**Comment by f0kx** [comment]
https://imgur.com/a/Mb30Xxr

this picture show what i meant!
if i dont have your mod installed it will work but with it wont pull out items

**Comment by 2No2Name** [comment]
Still cannot reproduce it. Maybe it is an incompatibility with another mod that you are using

**Comment by f0kx** [comment]
yeah maybe what you say ...maybe its a combination of mod and datapack what causes this issue!

**Comment by f0kx** [comment]
okay i add this datapack and it stops working https://www.planetminecraft.com/data-pack/enchantment-1-16/ but only if i place a new ---> https://imgur.com/a/Mb30Xxr
when your mod isnt installed all is working fine also with the datapack

**Comment by 2No2Name** [comment]
In the comments on the datapack site there are people talking about crashes with certain mods. It is mentioned that empty stacks are modified, which might be a problem for lithium as well.

**Comment by 2No2Name** [comment]
The datapack seems to be replacing the inventory stacklist in every gametick. This is fundamentally incompatible with lithium.

**Comment by 2No2Name** [comment]
I suggest you add the line
mixin.block.hopper = false
to the config/lithium.properties file.

**Comment by f0kx** [comment]
like so ?

This is the configuration file for Lithium.
 This file exists for debugging purposes and should not be configured otherwise.

You can find information on editing this file and all the available options here:
https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File

By default, this file will be empty except for this notice.
mixin.block.hopper = false

**Comment by FlashyReese** [comment]
Yes

**Comment by f0kx** [comment]
okay seems to work again..thx you!

**Comment by 2No2Name** [comment]
Might also have fixed it on the main branch now. The behavior is still not compatible with the optimizations, but the behavior should no longer be incorrect
