### ISSUE TITLE
[1.18.2]Crash/Memory leaking on the entity cramming check 

### ISSUE THREAD

**Issue by CCSCovenant** [jellysquid3/Lithium#362]
**Submitter:**

CCS_Covenant

**Bug Name:**

Crash/Memory leaking on the entity cramming check

**Description**

In version 1.18.2. while raid farm is running overtime, its memory usage and MSPT increasing and not going done until reboot server.
The server will crash at the end that out of memory error happens.
with the investigation of the spark profile data, the major issue is caused by the raider entity ticking cramming.

seems like some data structure that lithium implemented caused this problem
spark profile:
1. server that just reboots and runs raid farm at full speed:
https://spark.lucko.me/uazMQNiNGq
3. server that running raid farm at full speed for a while:
https://spark.lucko.me/7A7DkHdyO5

**Version:**

lithium version: lithium-fabric-mc1.18.2-0.7.9.jar

**Platform**

Windows 10 1809
Java 17
Minecraft 1.18.2
mods:
[mods.zip](https://github.com/CaffeineMC/lithium-fabric/files/8614043/mods.zip)

**Bug Reproduction**

1. run this raid farm:
http://www.mediafire.com/file/cmgkux8x861y35i/CCS_1_18_raid_gen4.zip
1.1 click the button in the command block to summon carpet bot
1.2 click the button in the command block to start the raid farm.
1.3 remember to close spawn protection while you using it in server
2. run it forever until out of memory happens.
 in my machine with R5 3600, 8GB memory, it crashed after tick warp around 8 hours real-time.
crash report:
[hs_err_pid14288.log](https://github.com/CaffeineMC/lithium-fabric/files/8614098/hs_err_pid14288.log)

**Expected outcome**
MSPT stays at a stable value forever. as well as memory usage

**Actual outcome**

MSPT and memory usage increase, and finally crash the server

**Comment by itsdinkd** [comment]
https://spark.lucko.me/DubQlYKl1M?hl=5482 mine as well

**Comment by 2No2Name** [comment]
Seems like some mod is creating duplicate entities or somehow removes them from the world in a custom way

**Comment by 2No2Name** [comment]
Is this issue still relevant or has it been resolved somehow?
