### ISSUE TITLE
Trying to find cause of incorrect data-type in chunks

### ISSUE THREAD

**Issue by Zevac-ZSF** [jellysquid3/Lithium#364]
Hello, I am researching an issue with rendering my world with Overviewer. Please do not stop reading yet :-)

After lots of help I found out that certain values in de .mca files have an incorrect data-type. and I was wondering if that is related to the datafixer issues that were mentioned in your update [Lithium mc1.17.1-0.7.5](https://www.curseforge.com/minecraft/mc-mods/lithium/files/3516367)

Or if you are maybe able to write a fix into Lithium for that.

Here is a screenshot by the creator of Mineways about the incorrect data-types:
![Chunk_withIncorrectValueTypes](https://user-images.githubusercontent.com/32144042/169162157-ad88c100-54ec-4ade-935f-ed03347b069c.png)

I know it is a long shot, but the development of overviewer seems a bit stagnated. And while there are plenty of people who are still able to render their worlds, there are quite some who haven't been able to do so since 1.18. So I kindly ask if you can/want to look into this chunk thing.

Thank you in advance

Z.

**Comment by 2No2Name** [comment]
The issue in lithium was that the block palette size and chunk section block data size did not match. I don't think this is related to lithium.

**Comment by Zevac-ZSF** [comment]
Mmm... okay, thank you for the information, now I just need to continue digging I guess :-)

Z.

ps I do not commonly add issues on github, am I supposed to close this one myself or is that done by a moderator?

**Comment by 2No2Name** [comment]
If there is no reason to keep it open, I am fine with anyone closing the issue.
