### ISSUE TITLE
Origins and Lithium

### ISSUE THREAD

**Issue by Disketaa** [jellysquid3/Lithium#366]
------------------------

### Version Information

> lithium-fabric-mc1.18.2-0.7.10.jar

### Expected Behavior

> **Phantom Origin** from **Origins** able to move through / into blocks

### Actual Behavior

> You taking damage while in blocks. 

### Reproduction Steps

> 1. Choose Phantom Origin
> 2. Activate ability (G key)
> 3. Go in blocks

### Other Information

> Lithium
> Origins

**Comment by SmatMan** [comment]
I fixed this issue by adding this into my `lithium.properties` file:
```
mixin.entity.gravity_check_block_below=false
mixin.entity.fast_suffocation_check=false
mixin.entity.stream_entity_collisions_lazily=false
mixin.entity.collisions=false
```

I'm pretty sure you only need the last line to fix it but I disabled all the collision detections just in case. 
Not sure where this file is located on the client side, but its in the "config" folder on the server side

Hope this helps!

**Comment by 2No2Name** [comment]
Now tracked at https://github.com/CaffeineMC/lithium-fabric/issues/382
