### ISSUE TITLE
Game Crashing on World Creation: MixinTransformerError

### ISSUE THREAD

**Issue by seanimusprime** [jellysquid3/Lithium#367]
### Version

lithium-fabric-mc1.18.2-0.7.10

### Reproduction Steps

1. Create a new world.
2. Game crashes while generating the world.

### Crash Report File

https://crashy.net/wAveVjJcHAYugPARp3a0

[crash-2022-06-05_11.54.43-client.txt](https://github.com/CaffeineMC/lithium-fabric/files/8840305/crash-2022-06-05_11.54.43-client.txt)

### Minecraft Save

Not able to provide a save. Game crashes before world is generated.

**Comment by 2No2Name** [comment]
I think this is not caused by lithium but by dramaticdoors
