### ISSUE TITLE
Newer version of Lithium 1.19 crashed my server

### ISSUE THREAD

**Issue by YumatanGames** [jellysquid3/Lithium#371]
### Version

> Version number mc1.19-0.8.0
> Example: lithium-fabric-mc1.16.5-0.6.4
> 
### Reproduction Steps

> I just installed the mod (I.E. placed the jar file into the mod's folder) and restarted the server. The server then crashed on restart.

### Crash Report File

[Crash - Lithium.txt](https://github.com/CaffeineMC/lithium-fabric/files/8874047/Crash.-.Lithium.txt)
e most recent crash report, check your game's "crash-reports" folder for the most recent
> crash report file.

### Minecraft Save

> If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

### Additional Information

Let me know if I can provide anything else that could help find out what is happening.

**Comment by 2No2Name** [comment]
Are you sure that it works if you remove lithium? ~This looks like an issue of the horsebuff mod~

**Comment by YumatanGames** [comment]
Yeah! The server was running perfectly without Lithium and it did restarted normally after removing it.

**Comment by YumatanGames** [comment]
But I'll try disabling Horse buff and see if that works

**Comment by 2No2Name** [comment]
I misread the crash, it seems to be a compatibility issue with carpet-tis-addition . I will link them here

**Comment by 2No2Name** [comment]
https://github.com/TISUnion/Carpet-TIS-Addition/issues/64

**Comment by YumatanGames** [comment]
Ah, ok. I'll prioritize Lithium over carpet for now. Thank you for the quick reply, I love CaffeineMC mods, by the way! Thank you for all your work! ;D

**Comment by 2No2Name** [comment]
If you need both, you can disable the hopper optimization by adding the line
mixin.block.hopper=false
to the lithium.properties file in the config folder

**Comment by YumatanGames** [comment]
Oh, ok! Thank you for helping me out. 😃
