### ISSUE TITLE
My 1.19 server with Lithium crashed

### ISSUE THREAD

**Issue by CTCS5** [jellysquid3/Lithium#372]
### Version

> minecraft 1.19
> lithium-fabric-mc1.19-0.8.0

### Reproduction Steps

> My server runs normally most of the time, but it often crashes. 
> I found lithium in the crash report and submitted this issue.

### Crash Report File

[crash-2022-06-15_20.09.23-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/8909261/crash-2022-06-15_20.09.23-server.txt)

### Additional Information

> Sometimes there is nothing unusual in crash reports, but this time it contained Lithium.

**Comment by 2No2Name** [comment]
I don't see anything in the crash report that suggests that Lithium is causing the crash
