### ISSUE TITLE
1.19 Server crashes randomly

### ISSUE THREAD

**Issue by KevinCCucumber** [jellysquid3/Lithium#373]
### Version

> lithium-fabric-mc1.19-0.8.0

### Reproduction Steps

1. Let the Server run.
2. Server gets crashed by Watchdog from time to time

### Crash Report File
[crash-2022-06-17_18.13.46-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/8929254/crash-2022-06-17_18.13.46-server.txt)

**Comment by AngelofWoe** [comment]
I've had two of these. Both were also while running Dynmap renders and a Chunky pregen.

[crash-2022-06-24_18.06.34-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/9077849/crash-2022-06-24_18.06.34-server.txt)
[crash-2022-06-26_01.32.33-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/9077851/crash-2022-06-26_01.32.33-server.txt)

**Comment by 2No2Name** [comment]
None of these crash reports hint at lithium being the cause
