### ISSUE TITLE
Nether portals in a perimeter unlink even though linked previously.

### ISSUE THREAD

**Issue by coderguy1777** [jellysquid3/Lithium#374]
#### Instructions

------------------------

### Version Information
> Minecraft 1.19

> fabric-api-0.55.3+1.19, continuity-2.0.0+1.19, fabric-carpet-1.19-1.4.79+v220607, fast-chest-1.3+1.19, indium-1.0.4+mc1.19, iris-mc1.19-1.2.5, itemscroller-fabric-1.19-0.16.0, litematica-fabric-1.19-0.11.2, malilib-fabric-1.19-0.12.1, minihud-fabric-1.19-0.22.0, reeses_sodium_options-1.4.3+mc1.19-build.43, servux-fabric-1.19-0.1.0, sodium-fabric-mc1.19-0.4.2+build.16, starlight-1.1.0+fabric.eb9df34, tweakeroo-fabric-1.19-0.13.1. Xaeros_Minimap_22.9.2_Fabric_1.19, XaerosWorldMap_1.23.2_Fabric_1.19, lithium-fabric-mc1.19-0.8.0

### Expected Behavior

> All nether portals in a 17x17 chunk perimeter previously linked in 1.18 link to the same portal on the nether side.

### Actual Behavior

> Half of the nether portals in the 17x17 chunk perimeter unlinked, sliced and un-sliced portal towers and only upon building a new portal in the nether 3 blocks away from the previous portal fixed the issue.

### Reproduction Steps

> To replicate, a slime farm perimeter of 17x17 chunks is where this issue occurred, so basically, make all the portals around the perimeter from the center, and almost all of the portals in the center should unlink, or the portals closest to the nether side portal don't unlink and all around it unlink.

**Comment by 2No2Name** [comment]
This should be fixed in 0.8.1+
