### ISSUE TITLE
ianxofour's wither skeleton farm is broken with lithium.

### ISSUE THREAD

**Issue by Phenomenali** [jellysquid3/Lithium#375]
https://www.youtube.com/watch?v=ixGwh1pJb9o

this is the farm im using, the problem is that the wither skeletons don't come through the portal in the killing area.

the reason may be that when they travel to the overworld. Any idea how to fix it without removing the mod?

And yes the farm works fine without lithium.

EDIT:  Lithium 0.8.1 fixed the issue. <3

**Comment by silversquirl** [comment]
Would you be able to provide a world download showing this issue?

**Comment by Phenomenali** [comment]
https://www.mediafire.com/file/ybu4hjvgdschikl/Wither_skull_farm_-_ianxofour.zip/file

this world has the farm built already from Shulkercraft

**Comment by OpenBagTwo** [comment]
Can confirm. Was prototyping in Creative mode, and even waiting a full Minecraft day I'd get few-to-no skeletons. Just tried disabling Lithium and my inventory is already overflowing.

Some observations:
- Wither Skeletons inside Nether Portals don't flee from tamed wolves
- Wither Skeletons inside Nether Portals don't rush towards iron golems (a trick I picked up from [this video](https://youtu.be/W8X5gW0GQDs) 
- Firing a projectile into the portal was sometimes enough to trigger some Wither Skeletons to travel into the Nether-side killing chamber
- Wither Skeletons would become glitched in place standing on a trap door placed to aid in pathfinding to the Iron Golem. 

My Lithium version is only 0.8.0, and I see recent commits regarding improvements to AI management, so when I have the time I'll try upgrading to see if that solves the issue.

**Comment by 2No2Name** [comment]
Can you try using Lithium 0.8.1?

**Comment by Phenomenali** [comment]
> Can you try using Lithium 0.8.1?

I can confirm it fixed the problem and the farm works again, Thank you for the update <3
