### ISSUE TITLE
Watchdog

### ISSUE THREAD

**Issue by TheButterbrotMan** [jellysquid3/Lithium#376]
### Version
lithium-fabric-mc1.18.2-0.7.10.jar

### Crash Report File
https://bytebin.lucko.me/K2ijWFtTME

### Additional Information
https://www.curseforge.com/minecraft/modpacks/deathdusk (2.0.12)

**Comment by toutlamer** [comment]
Can you
- upload the file on github
- explain what is the issue
We can't help you with 1 word
