### ISSUE TITLE
Remove the `SINE_TABLE` array in `MathHelper`

### ISSUE THREAD

**Issue by altrisi** [jellysquid3/Lithium#381]
Lithium replaces the `sin` and `cos` methods in `MathHelper`, the only two places that access its `SINE_TABLE` array. That means that the array is unused after that, however it is still kept in memory.

Suggestion to remove it or at least make it an empty array.

**Comment by 2No2Name** [comment]
This might cause issues with mods that directly access the field, but I think it is unlikely that any mod does this.

It should be fine to do this
