### ISSUE TITLE
Compatibility with origins phasing ability

### ISSUE THREAD

**Issue by Hallowedz** [jellysquid3/Lithium#382]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **bug report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version Information

> lithium-fabric-mc1.19.1-0.8.3

### Expected Behavior

> when phasing should not take suffocation damage

### Actual Behavior

> When phasing you take suffocation damage

### Reproduction Steps

> choose the phantom origin and use the phasing ability to traverse through blocks.

### Other Information

> Provide a list of any other mods you are using, along with their respective versions. If you have any screenshots,
> videos, or other information that you feel is necessary to explain the issue, feel free to attach them here.

**Comment by 2No2Name** [comment]
Same issue as https://github.com/apace100/origins-fabric/issues/473
Latest commit might improve the situation.

**Comment by piepneus** [comment]
thanks i have been trouble shoothing al day long and is just found out it was lithium. big thankyou

**Comment by 2No2Name** [comment]
Workaround: Add the line
mixin.entity.collisions.suffocation=false
to lithium.properties in config folder.
