### ISSUE TITLE
Commit 9aa897e is incompatible with architectury api

### ISSUE THREAD

**Issue by Wudji** [jellysquid3/Lithium#383]
### Version

> [Commit 9aa897e](https://github.com/CaffeineMC/lithium-fabric/commit/9aa897e7df46f1209a0c1696953126b5b22151fc)
### Reproduction Steps

> 1. Enter a world
> 2. Game Crashed

### Crash Report File

> [crash-2022-08-03_22.29.36-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/9252382/crash-2022-08-03_22.29.36-server.txt)

### Minecraft Save

> -

### Additional Information

> -

**Comment by 2No2Name** [comment]
I pushed a fix. Can you check whether it works the latest commit?

**Comment by Wudji** [comment]
The latest commit works! Thanks~
