### ISSUE TITLE
Crash on opening in 1.19.2

### ISSUE THREAD

**Issue by Issacozzman** [jellysquid3/Lithium#384]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Lithium' (lithium) 0.8.0 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Lithium' (lithium) 0.8.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

13:23:20.631
launcher
main
Preparing to launch minecraft client for fabric-loader-0.14.9-1.19.2
13:23:23.610
launcher
main
Minecraft client fabric-loader-0.14.9-1.19.2 is ready to start.
13:23:23.610
launcher
main
Starting!
13:23:23.792
launcher
main
Using default game log configuration client-1.12.xml (outputs XML)
13:23:24.791
FabricLoader/GameProvider
main
Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
13:23:24.961
FabricLoader/Resolution
main
Mod resolution failed
13:23:24.961
FabricLoader/Resolution
main
Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED lithium 0.8.0 {depends minecraft @ [1.19]}, ROOT_FORCELOAD_SINGLE lithium 0.8.0]
13:23:24.962
FabricLoader/Resolution
main
Reason: [HARD_DEP lithium 0.8.0 {depends minecraft @ [1.19]}]
13:23:24.962
FabricLoader/Resolution
main
Fix: add [], remove [], replace [[lithium 0.8.0] -> add:lithium 1 ([(-∞,∞)])]
13:23:24.969
FabricLoader
main
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Lithium' (lithium) 0.8.0 with any version that is compatible with:
		 - minecraft 1.19.2
Unmet dependency listing:
	 - Mod 'Lithium' (lithium) 0.8.0 requires version 1.19 of 'Minecraft' (minecraft), but only the wrong version is present: 1.19.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by ipatix** [comment]
Well I was looking into this too and I found out that the release says it's 1.19.1 comptaible only.
