### ISSUE TITLE
Disable client side entity collision checks (Fix MC-228976)

### ISSUE THREAD

**Issue by HyprGirl** [jellysquid3/Lithium#387]
**Is your feature request related to a problem? Please describe.**
I'm not quite sure if lithium's already doing this (I apologize if it is and I'm just wasting everyone's time), but if it isn't I think it would be an easy and effective way to improve performance. It's related to this Minecraft bug ([MC-228976](https://bugs.mojang.com/browse/MC-228976)). In short, Minecraft calculates entity collisions both on the server and the client, which is not ideal.

**Describe the solution you'd like**
If you disable client side entity collision nothing should changes for the user, except a nice performance boost.

**Describe alternatives you've considered**
There's already a mod doing this. Their [Github](https://github.com/CorgiTaco/No-Client-Side-Entity-Collision-Checks), [Modrinth](https://modrinth.com/mod/entity-collision-fps-fix), [CurseForge](https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix). You could perhaps incorporate the mod or use parts of it or something similar. The author's tests show a jump from 10-16 fps to 24-29 fps when looking at a large number of entities.

**Comment by MOOOOs** [comment]
I was about to ask this question really waiting for answer if this is implemented because i seen this in log that it was disabled and this bug is serious performance hog and will make xp farms obsolete

**Comment by Felix14-v2** [comment]
> If you disable client side entity collision nothing should changes for the user, except a nice performance boost

... and broken collision with some entities like [shulkers](https://github.com/CorgiTaco/No-Client-Side-Entity-Collision-Checks/issues/6).

**Comment by 2No2Name** [comment]
I don't think there is a way to implement this without causing issues. Therefore it won't be added to lithium
