### ISSUE TITLE
Bees don't exit their hive in the nether

### ISSUE THREAD

**Issue by sloaner** [jellysquid3/Lithium#39]
Game version: `1.15.2`
Lithium version: `lithium-mc1.15.2-fabric-0.4.6-mod`
Fabric version: `0.5.2.39`

I have a honey farm on top of the nether bedrock. It was working fine, but after adding lithium the bees no longer exit their hive even after an hour of AFK. After disabling lithium and restarting the server, all 3 bees from each hive immediately exited and started pollinating.

Screenshot and logs below
<details>
  <summary>Screenshot</summary>
![2020-05-08_23 30 13](https://user-images.githubusercontent.com/446084/81462955-068f8100-9184-11ea-8121-03b84dfa7a6b.png)
</details>

[2020-05-08-2.log](https://github.com/jellysquid3/lithium-fabric/files/4602570/2020-05-08-2.log)

**Comment by jellysquid3** [comment]
Possibly related to #35.

**Comment by LucilleTea** [comment]
Seems to work in the 1.16 branch (built from https://github.com/jellysquid3/lithium-fabric/commit/5aac5dea0cea4f2e87fa3270ba2ba1665a257d51)

**Comment by sloaner** [comment]
Is there a config I'm able to disable or do I just have to disable the whole mod until the next build?

**Comment by LucilleTea** [comment]
You can disable patches using the [config file](https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File).
I'm not sure which is the offending patch, so you may need to try a few.
