### ISSUE TITLE
Something is making lithium load mixins too early

### ISSUE THREAD

**Issue by Sunconure11** [jellysquid3/Lithium#393]
#### Instructions

This is a template for the issue you are about to open! It will help you provide the information necessary
to complete your **crash report**. Before you open an issue, ensure you've completed every step on the checklist below.

- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.

All good? Please read through the sections below, and fill out any lines starting with an arrow. Then, remove
everything above this dashed line (including the line itself.)

------------------------

### Version

lithium-fabric-mc1.19.2-0.8.3

### Reproduction Steps

> Provide information on how to reproduce this game crash. You can either fill this section in like the example below
> or do something else -- just make sure your instructions are minimal and clear, as other people will need to be able
> to replicate your issue.
>
> Example:
1. Attempt to boot up MC
2. https://pastebin.com/DdEmazdw

### Crash Report File

https://pastebin.com/DdEmazdw

### Minecraft Save

> N/A

### Additional Information

Will include a mod list tomorrow

I am also on Quilt

**Comment by 2No2Name** [comment]
You can work around this by adding
mixin.math.sine_lut=false
to the lithium.properties file in the config directory

**Comment by Sunconure11** [comment]
I think it was a shit mod that I could not identify, as I redid this order entirely and it has not come back. I did try that, though, and it did nothing.
