### ISSUE TITLE
Incompatibility with Open Parties and Claims 0.13 using Quilt

### ISSUE THREAD

**Issue by mati865** [jellysquid3/Lithium#394]
### Version

lithium-fabric-mc1.19.2-0.8.3

### Reproduction Steps

1. Setup MC 1.19.2 with Quilt
2. Install `Quilted Fabric API`, `Forge Config API`, `Lithium` and `Open Parties and Claims`
3. Launch single player game
4. It will crash during world generation or world loading

### Crash Report File

https://mclo.gs/oXhUOtB

### Minecraft Save

Unnecessary

### Additional Information

First reported to `Open Parties and Claims` but its author suggests Lithium could be misusing the API but is not sure about it: https://github.com/thexaero/open-parties-and-claims/issues/93
Hence moving the issue here, let me know if I should report it to Quilt instead.

**Comment by 2No2Name** [comment]
I changed the ModifyVariable to an Inject in the latest commit. If this is still relevant to you, please test it again with the latest build from the build artifacts at https://github.com/CaffeineMC/lithium-fabric/actions/runs/3199866036

**Comment by mati865** [comment]
Works great, thank you!
