### ISSUE TITLE
Visual bug: Mob crossbows do not have an arrow

### ISSUE THREAD

**Issue by maityyy** [jellysquid3/Lithium#396]
Mobs with crossbows do not have an arrow, although they can still shoot. Bug occurs on the latest version of lithium on Modrinth.

Lithium only: https://user-images.githubusercontent.com/47220489/194306270-85420a1b-6a85-48c4-ba9d-15450285af7a.mp4
Pure vanilla: https://user-images.githubusercontent.com/47220489/194306476-17c5521d-13ed-4ee9-ae3d-4ce2f9326ea5.mp4

**Comment by maityyy** [comment]
`mixin.entity.skip_equipment_change_check=false` fixes this bug

**Comment by 2No2Name** [comment]
Related to a previous issue about foxes still showing the item after they ate it
