### ISSUE TITLE
AE2 block machines fail to receive/send items from hoppers with Lithium is installed

### ISSUE THREAD

**Issue by purejosh** [jellysquid3/Lithium#399]
### Version Information

lithium-fabric-mc1.19.2-0.9.1

### Expected Behavior

AE2 blocks should be able to pull/push items from hoppers. 

### Actual Behavior

AE2 block updates hopper once, pulls/pushes one item, and seizes. 

### Reproduction Steps

Install the following two mods:
AE2 12.8.2-beta [FABRIC]
Lithium mc1.19.2-0.9.1

Observe that hoppers do not continuously pull or push items into the charger block. It will work once, and that's it.

### Other Information

AE2 github ticket, should you need to communicate with them. 
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6699

**Comment by 2No2Name** [comment]
Should be fixed by the new build here:
https://github.com/CaffeineMC/lithium-fabric/actions/runs/3252653989

**Comment by purejosh** [comment]
Thanks so much!!

**Comment by purejosh** [comment]
Will this fix be available in the next release, 0.9.2 presumably?
