### ISSUE TITLE
Lithium 0.9.0 hopper optimization may cause NPE with other mods

### ISSUE THREAD

**Issue by Fallen-Breath** [jellysquid3/Lithium#400]
#### Instructions

The following `@ModifyVariable` sets the `booleanSupplier` variable to null, causing mods accessing this variable throwing NPE after this `@ModifyVariable`

https://github.com/CaffeineMC/lithium-fabric/blob/5511cedec922e1e69746cb60cc2ec17d778b2458/src/main/java/me/jellysquid/mods/lithium/mixin/world/block_entity_ticking/sleeping/hopper/HopperBlockEntityMixin.java#L60-L68

And the variable being null is only used in the following injection

https://github.com/CaffeineMC/lithium-fabric/blob/5511cedec922e1e69746cb60cc2ec17d778b2458/src/main/java/me/jellysquid/mods/lithium/mixin/world/block_entity_ticking/sleeping/hopper/HopperBlockEntityMixin.java#L70-L79

### Example

Example compatibility issue with Carpet-TIS-Addition mod

https://github.com/TISUnion/Carpet-TIS-Addition/issues/81

Reproduced by 
- Minecraft version: `1.19.2`
- Fabric Carpet version: `1.4.83`
- Carpet TIS Addition version: `1.40.1`
- Lithium version: `0.9.1`

Mixined classes:

```java
// net.minecraft.block.entity.HopperBlockEntity#insertAndExtract

    // ....

    booleanSupplier = localvar$bod000$rememberBranch(booleanSupplier);  // <-- lithium sets booleanSupplier to null
    if (bl) {
        blockEntity.setTransferCooldown(8);
        handler$bdd000$doHopperCountersUnlimitedSpeed(world, pos, state, blockEntity, booleanSupplier, (CallbackInfoReturnable)null);   // <-- NPE
        markDirty(world, pos, state);
        return true;
    }
}

handler$bod000$sleepIfBranchNotRemembered(world, pos, state, blockEntity, booleanSupplier, (CallbackInfoReturnable)null);
return false;
```

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/64078c5544cfdd93907ad0756f0822e0ce761f65 should fix this
