### ISSUE TITLE
Double chest does not wake up hopper in some situations

### ISSUE THREAD

**Issue by Pentasim** [jellysquid3/Lithium#403]
### Version Information

lithium-fabric-mc1.19.2-0.10.0

### Expected Behavior

Both hoppers should wake up if items are put in the chest

### Actual Behavior

Only the hopper with the initial chest wakes up

### Reproduction Steps

Place two hoppers next to each other (in such a way that they don't wake up each other, e.g. pointing down/away)
Place a chest on top of one
Shift-place the second chest on the side of the first chest
Put item in the chest
-> only the hopper with the first chest draws items

This is "fixed" if the second hopper wakes up by some other means

This does not occur, if the single chest already contains some items

![image](https://user-images.githubusercontent.com/96294412/197632067-85274329-cab3-438e-bc5b-41149b972d0c.png)

**Comment by 2No2Name** [comment]
Can work around it by adding the line
mixin.block.hopper=false
to the lithium.properties file in the config directory or by
using the latest dev branch build instead
https://github.com/CaffeineMC/lithium-fabric/actions/runs/3321229327
