### ISSUE TITLE
Not compatible with Fabric API 0.64.0!

### ISSUE THREAD

**Issue by QianMuu** [jellysquid3/Lithium#404]
This is a good optimization module.

However, it is not compatible with the latest version of the fabric api,

Failure to generate a world directly leads to a crash.

Please repair it as soon as possible.

**Comment by 2No2Name** [comment]
Can you post the crash report?

**Comment by 2No2Name** [comment]
Possible duplicate of https://github.com/CaffeineMC/lithium-fabric/issues/401
