### ISSUE TITLE
Inventories are completely empty after setting `mixin.block.hopper=false`

### ISSUE THREAD

**Issue by 2No2Name** [jellysquid3/Lithium#410]
### Version Information

lithium-fabric-mc1.19.2-0.10.1

### Expected Behavior

Chests should not lose their inventory

### Actual Behavior

All chests are empty

### Reproduction Steps

Add the line `mixin.block.hopper=false` to the lithium.properties file. Restart the game.

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/492c16a7e5fb81f53c01b588ec0169aa53356cf7 fixes the issue.

Workaround for Lithium 0.10.1:
Add the line
`mixin.util.inventory_change_listening=false`
to the lithium.properties file in the config folder.

**Comment by pllot** [comment]
Anything I can do after losing my items to this?

**Comment by 2No2Name** [comment]
If you have a backup, you will need to load it. Otherwise I believe your items are lost
