### ISSUE TITLE
Lithium incompatible with Copper Hopper

### ISSUE THREAD

**Issue by 2No2Name** [jellysquid3/Lithium#411]
### Version Information

lithium-fabric-mc1.19.2-0.10.1 (guessed)

### Expected Behavior

Features from Copper Hopper are unaffected by Lithium

### Actual Behavior

Features from Copper Hopper (e.g. SidedInventory behavior of a HopperBlockEntity subclass) do not work correct with lithium

### Reproduction Steps

Install both mods and use hoppers

### Other Information

The issue can probably be fixed on lithium's side very easily.

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/e2cc33960b1ac20707e86b3aaabcdedf31771745 fixes the issue

**Comment by asteven** [comment]
It seems this fix has been included since 0.10.2. Is this correct?

**Comment by 2No2Name** [comment]
Yes
