### ISSUE TITLE
Some chunks don't load after updating to 0.10.1

### ISSUE THREAD

**Issue by ChristopherHaws** [jellysquid3/Lithium#412]
### Version Information
lithium-fabric-mc1.19.2-0.10.1

### Expected Behavior
All of the chunks should be visible in game.

### Actual Behavior
Some chunks are not visible in game.

### Reproduction Steps
Upgrade from 0.10.0 to 0.10.1 and login to a purpur server (not sure if the server part is important).

### Other Information
Logs; https://mclo.gs/AMU8kFq

Pictures:
![image](https://user-images.githubusercontent.com/5934505/199640886-010a8bc2-7444-4ee0-95e6-7de60e8ad3d5.png)
![image](https://user-images.githubusercontent.com/5934505/199640913-38648c65-180f-473d-99c0-f54b085d2354.png)

**Comment by 2No2Name** [comment]
Probably the same reason as https://github.com/CaffeineMC/lithium-fabric/issues/410

Can you try adding the line
mixin.util.inventory_change_listening=false
to the lithium.properties file in the config folder and restart the game?

**Comment by ChristopherHaws** [comment]
@2No2Name Now that 0.10.2 is released, should we be able to turn `mixin.util.inventory_change_listening` back to `true` and not have this issue?

Thanks! :)

**Comment by 2No2Name** [comment]
I think so. I still suggest to take a backup before any config changes
