### ISSUE TITLE
Game crashing upon joining server and looking around little bit

### ISSUE THREAD

**Issue by devendrapoonia** [jellysquid3/Lithium#413]
### Version

> Example: Latest

### Reproduction Steps

> 1. Open Minecraft
> 2. Join a server
> 3. Just look around little bit and game will crash

### Crash Report File

> Crash Report - https://crashy.net/p42IVWH7oa92N9AzcTZO

### Minecraft Save

> It was a Minecraft server.

**Comment by devendrapoonia** [comment]
The issue was resource pack.

**Comment by devendrapoonia** [comment]
Still you should take a look.

**Comment by 2No2Name** [comment]
Which resource pack caused the issue?

**Comment by devendrapoonia** [comment]
Faithful 32x, 1.19.2
https://resourcepack.net/faithful-32x32-resource-pack/

**Comment by 2No2Name** [comment]
Were you using any mods or other resource packs as well?

**Comment by devendrapoonia** [comment]
Two resource packs, of Better beds mod.

**Comment by 2No2Name** [comment]
The issue seems to be caused by a block not having a collision shape, which is highly unusual. We can include a fix to not crash, but this might just hide the actual reason of the issue.
Relates to PR https://github.com/CaffeineMC/lithium-fabric/pull/409
and Issue https://github.com/CaffeineMC/lithium-fabric/issues/272

**Comment by devendrapoonia** [comment]
![image](https://user-images.githubusercontent.com/50015986/200185528-d4d3650e-a496-457d-88a7-9e4801fc00ce.png)
For more info if you need.

**Comment by 2No2Name** [comment]
Thank you for this detailed mod list

**Comment by 2No2Name** [comment]
Both occurences of this issue have those mods installed alongside lithium:

cloth-config
fabric-api
meteor-client
modmenu
sodium

I think it is worth checking whether meteor-client makes any blocks behave in this unusual way

**Comment by devendrapoonia** [comment]
I should report it there. Thank you for assisting me with this :))

**Comment by 2No2Name** [comment]
Should not happen in future releases anymore. Null shapes are treated like empty shapes now
