### ISSUE TITLE
latest 0.10.2 crashes with BetterNether on 1.18.2 Fabric

### ISSUE THREAD

**Issue by Abalieno** [jellysquid3/Lithium#414]
lithium-fabric-mc1.18.2-0.10.2
bclib-1.4.7
better-nether-6.1.2

Simple crash on launch.

net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: me/jellysquid/mods/lithium/api/pathing/BlockPathingBehavior

[latest.log](https://github.com/CaffeineMC/lithium-fabric/files/9994644/latest.log)

**Comment by 2No2Name** [comment]
For now you can use Lithum 0.7.10 instead

**Comment by Abalieno** [comment]
I'm using 0.8.1 actually, but for some reason it was never added on CF.

**Comment by 2No2Name** [comment]
For future backports I will remember to not backport breaking API changes
