### ISSUE TITLE
Holograms don't show up on servers

### ISSUE THREAD

**Issue by Harsh1625** [jellysquid3/Lithium#418]
There are a lot of servers that use holograms and it is very annoying when it doesn't show up, you might be wondering what holograms are, basically they are text that hover in the air that can show a lot of good information which can be added using plugins(if you don't know what plugins are or how they work, they are basically server-side mods that change existing data instead of creating it. eg. plugins can create a mob by changing an existing mod instead of just creating a new mob.). I know it won't help much only by the word "holograms" but I don't know how the plugin manages to show floating text and I tried finding out how it shows the text but I couldn't figure it out, though I hope you should be able to figure it out. Another thing I wanted to say that when I tried removing lithium and checking if the holograms show up, they did show up but it decreased the amount of fps I had with lithium which is obvious but it was quite a lot of difference.

**Comment by silversquirl** [comment]
Are you using Lithium server-side or client-side?
If it's client-side, Lithium alone shouldn't affect this. Are you using any other mods?

**Comment by 2No2Name** [comment]
I will assume Lithium is used on the client.

Can you give a name of a public server with those holograms and how to get to a location to see them?

**Comment by Harsh1625** [comment]
> I will assume Lithium is used on the client.
> 
> Can you give a name of a public server with those holograms and how to get to a location to see them?

hypixel.net , you can find holograms after walking a few blocks straight where you're facing, you might find them over npcs.
yes, lithium is used on client, I am sorry I didn't mention that because I really didn't know it can also be used on server-side.

This is an hologram.
![image](https://user-images.githubusercontent.com/89334211/202846159-4a748053-a0ce-43e0-b466-da643c5aa748.png)

**Comment by Harsh1625** [comment]
> Are you using Lithium server-side or client-side? If it's client-side, Lithium alone shouldn't affect this. Are you using any other mods?

I am using a lot of other mods like sodium, starlight etc. but when I removed lithium, the holograms were back.

**Comment by Harsh1625** [comment]
uh, it's been a week since the last message in this report so I just wanted to confirm if my issue is being looked at or not.

**Comment by 2No2Name** [comment]
Not looking at it right now and I doubt that lithium is causing the issue, but I will test it.

**Comment by 2No2Name** [comment]
![2022-11-26_14 21 11](https://user-images.githubusercontent.com/50278648/204091089-31776ecb-cf29-4e8b-a263-346b524ff2d3.png)

Cannot reproduce the issue. The text seems to render just fine.

**Comment by Harsh1625** [comment]
hmm, this is weird, the holograms weren't rendering when I had lithium and when I removed lithium, they were being rendered. I am sorry for wasting your time, the issue is fixed now. Thanks for helping me out.

**Comment by Harsh1625** [comment]
I just found out that it was fixed in the latest release of lithium, but it wasn't fixed when I created this report. This might be why it couldn't be reproduced.

**Comment by 2No2Name** [comment]
In which version does the issue occur?

**Comment by Harsh1625** [comment]
> In which version does the issue occur?

I am not sure but the latest version for 1.19.2 was 1.19.2-0.10.1 at the time I created this post.
