### ISSUE TITLE
Hopper doesn't push items in specific situations

### ISSUE THREAD

**Issue by Pentasim** [jellysquid3/Lithium#419]
### Version Information

Minecraft 1.19.2
lithium-fabric-mc1.19.2-0.10.2

### Reproduction Steps

Place a barrel
Hopper on top
Hopper below
Fill all inventories with items
Lock bottom hopper
Place comparator reading from barrel
Take out items from barrel
=> Top hopper does not push

### Expected Behavior

Top hopper should wake up

### Actual Behavior

Top hopper does not wake up

This is “fixed” if the top hopper wakes up by some other means (and cannot be reproduced without replacing both barrel and hoppers)

### Other Information

Mod list:
fabric-api-0.62.0+1.19.2
lithium-fabric-mc1.19.2-0.10.2
sodium-fabric-mc1.19.2-0.4.4+build.18
phosphor-fabric-mc1.19.x-0.8.1

![2022-11-19_16 06 24](https://user-images.githubusercontent.com/96294412/202858529-a7c9fe5c-5ab5-40fa-b45c-8f8becef6d99.png)

**Comment by 2No2Name** [comment]
Confirmed, bottom hopper not required

**Comment by 2No2Name** [comment]
Fixed in this action build. https://github.com/CaffeineMC/lithium-fabric/actions/runs/3504930287
Will be included in the next release
