### ISSUE TITLE
Crash with latest Nvidia Driver

### ISSUE THREAD

**Issue by AssassinTee** [jellysquid3/Lithium#421]
### Version

lithium-fabric-mc1.19.2-0.10.0

### Reproduction Steps

I updated to the latest NVidia driver and now my game keeps crashing on server changes. This doesn't happen with default minecraft. Looks like a nullpointer exception. This didn't happen before the driver update.

### Crash Report File

Uploaded file

[hs_err_pid21424.log](https://github.com/CaffeineMC/lithium-fabric/files/10095388/hs_err_pid21424.log)

I used phosphor and sodium, too, but this error log looks totally like a lithium problem! GL!

**Comment by 2No2Name** [comment]
Please try this without lithium or with only lithium.

**Comment by AssassinTee** [comment]
Thanks for the feedback! I couldn't reproduce the same bug without the other mods, so the culprid must be somewhere different.
