### ISSUE TITLE
Hoppers maybe not working with Farmer's Delight Fabric port inventories

### ISSUE THREAD

**Issue by 2No2Name** [jellysquid3/Lithium#423]
Same issue on Farmer's Delight Fabric port, without Lithium, the cooking pot is working well, but if last version of Lithium is installed (I've not yet tested with older version), hoppers cannot pull or push items in the cooking pot until they are updated themself.

My first guess is that I'm doing something wrong in the code that break the interaction, but it work well without Lithium, and the code is the same than a furnace block.

If you need any information to understand what's wrong, I'm available.

This will maybe fixed by this action https://github.com/CaffeineMC/lithium-fabric/actions/runs/3504930287, so in next release, but I prefered notify that the bug.

_Originally posted by @Zifiv in https://github.com/CaffeineMC/lithium-fabric/issues/417#issuecomment-1328018627_

**Comment by 2No2Name** [comment]
https://github.com/Zifiv
https://github.com/newhoryzon/farmers-delight-fabric/blob/master/src/main/java/com/nhoryzon/mc/farmersdelight/entity/block/CookingPotBlockEntity.java

It looks like the mod doesn't support vanilla hopper item transfer logic. I assume that you must be using fabric-transfer-api.
Can you explain how hoppers are supposed to interact with the inventory if you are not using transfer-api?

**Comment by Zifiv** [comment]
> It looks like the mod doesn't support vanilla hopper item transfer logic. I assume that you must be using fabric-transfer-api.
> Can you explain how hoppers are supposed to interact with the inventory if you are not using transfer-api?

Ok maybe, but why is it working well without Lithium so ?

Indeed you're right, I must use fabric-transfert-api (to enhance compatiblity with others mods), it should fix the issue for Farmer's Delight. I will let you know.
FD ticket : https://github.com/newhoryzon/farmers-delight-fabric/issues/104

**Comment by Zifiv** [comment]
So.. I'm just a dumb... for sure it cannot work if my entity didn't implement `SidedInventory`, but I don't know why without Lithium it works well...

**Comment by 2No2Name** [comment]
Lithium does support fabric-transfer-api under the certain conditions:
The inventory appears only together with a block update being sent to the hopper or before the hopper ticks after the chunk is loaded

So I assume you might be adding the inventory to the transfer api way later than it is normal.

**Comment by 2No2Name** [comment]
Closing as your comment sounds like you are fixing it on your side
