### ISSUE TITLE
Not compatible with Terramine+ *any mod adding accessory* - accessory duplication bug

### ISSUE THREAD

**Issue by Rad586** [jellysquid3/Lithium#424]
Describe the bug: 
Accessory duplicates itself after put into the slot.

To Reproduce:
Put any accessory into their slot.

Game Environment:
Minecraft: 1.18.2
Fabric API: 0.59.1
TerraMine: 1.6.0
Trinkets: 3.3.1
lithium 0.10.2
simplehats 0.1.6 (replaceable)

Lithium works fine with Terramine, it also works fine with other accessory adding mod, but when these three things combine together, boom. (C2ME also has that problem)

**Comment by 2No2Name** [comment]
Can you test whether the other mods without lithium have the issue when used together?

**Comment by Rad586** [comment]
> Can you test whether the other mods without lithium have the issue when used together?

 I tested terramine+simplehats+runes, the slots work properly(but issue appears after adding lithium).

**Comment by 2No2Name** [comment]
What kind of slot is that and how do you put it in? Is it a player inventory click or is it a hopper transfer or similar?

There was a hopper interaction related bugfix in the latest build, so if it is hopper related, you can retest. https://github.com/CaffeineMC/lithium-fabric/actions/runs/3615282106

**Comment by Rad586** [comment]
> What kind of slot is that and how do you put it in? Is it a player inventory click or is it a hopper transfer or similar?
> 
> There was a hopper interaction related bugfix in the latest build, so if it is hopper related, you can retest. https://github.com/CaffeineMC/lithium-fabric/actions/runs/3615282106

 It's a player inventory click, and it's the ring slot added by terramine via trinket.

**Comment by 2No2Name** [comment]
I don't know what could cause this to happen. You can bisect the lithium options if you want to find out which lithium setting is causing the issue. 

List of mixin rules is here:
https://github.com/CaffeineMC/lithium-fabric/blob/1.19.x/dev/lithium-mixin-config.md

Can disable an option e.g. by adding the line `mixin.ai=false` to the lithium.properties file in the config folder. The example disables all settings in the `ai` category

**Comment by 2No2Name** [comment]
Work on a fix will only be done if someone figures out which mixin is causing the issue (e.g. using the technique mentioned above)
