### ISSUE TITLE
Mobs turn invisible,

### ISSUE THREAD

**Issue by Zhado8** [jellysquid3/Lithium#428]
### Read me before you open an issue! ###

Mobs turn invisible!!

im trying to run lithium but for what ever reason mobs just dont exist on my screen when i use it, i cant even hit em even tho a skeleton can shoot me,Fx mobs seem allmost like ghosts.

------------------------

### Version Information

>lithium-fabric-mc1.19.2-0.9.0

### Specs.

> Cpu 11th Gen Intel, i7 11800h.
>Gpu rtx 3070.
> Ram, 16Gb, speed 3200MHz, form factor SODIMM.
> windoes 11

**Comment by silversquirl** [comment]
Please check if this happens with the latest version of Lithium.

If it still happens, please list any other mods you're using, and upload a log file.
