### ISSUE TITLE
latest lithium crashing (missing class)

### ISSUE THREAD

**Issue by StockiesLad** [jellysquid3/Lithium#429]
### Version
lithium-fabric-mc1.18.2-0.10.3

### Reproduction Steps
install the given version in https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659 modpack

### Crash Report File
https://gist.github.com/FluffyBumblebees/3dd97d62dbcae88a3752561ccfa7efd5

### Minecraft Save
N/A

### Additional Information
N/A

**Comment by 2No2Name** [comment]
Update io.ix0rai.bodacious_berries and if the issue persists, report this to the author of io.ix0rai.bodacious_berries

The BlockPathingBehavior compat is no longer needed

**Comment by 2No2Name** [comment]
Another alternative is to downgrade your lithium version

**Comment by StockiesLad** [comment]
alright

**Comment by StockiesLad** [comment]
I manually removed the redundant code and it seems to be working, the dev is also working on a fix. which means this issue is resolved
