### ISSUE TITLE
Bedrock breaking failure

### ISSUE THREAD

**Issue by Minepig** [jellysquid3/Lithium#435]
### Version Information

minecraft 1.18.2
fabric loader 0.14.12 (up to date)
lithium-fabric-mc1.18.2-0.10.3

### Expected Behavior

Use the trick in following video to break bedrock:
https://www.bilibili.com/video/BV1KJ411b73z/
https://youtu.be/o3JBaioeIpc
(Both links are the same video)

### Actual Behavior

Bedrock does not break.

### Reproduction Steps

1. install Lithium and Tweakeroo
2. follow the above video
3. note that you may need more than 2 pistons in hand

### Other Information

Disabling `mixin.block.moving_block_shapes` can fix this issue.
The trick requires a retracting block event to be scheduled by the piston before it is blowed up, so that the newly placed piston can "retract" in bedrock. For some reason this mixin breaks the trick.

If you need my modlist (though i think other mods do not affect it since i've succeeded after disabling the mixin):
![image](https://user-images.githubusercontent.com/30530115/209525387-4ed65e8d-0fdd-45cd-8922-17fa1f524d16.png)

**Comment by 2No2Name** [comment]
Are you able to place the piston? If you are able to do this, it might be lag related, which this particular lithium patch reduces.

**Comment by Minepig** [comment]
Recently I did a more extensive test and I found that bedrock breaking sometimes works after i enable this mixin.
It might be lag related.
