### ISSUE TITLE
[1.19.2 fabric] getChunkBlocking causing crash? too many times

### ISSUE THREAD

**Issue by itsdinkd** [jellysquid3/Lithium#438]
### Version
Fabric Lithium 0.10.4

### Reproduction Steps

No idea, I keep seeing players go into a specific chunk and this crash occurs in our modpacks official server. 

### Crash Report File

https://gist.github.com/itsdinkd/09bf1f9eefe8b7c2dafcd802db456c53

**Comment by 2No2Name** [comment]
Can you try removing lithium for a long enough time to see whether that works around the issue and report back about the results?

**Comment by itsdinkd** [comment]
looks like it doesnt happen when lithium is not in. is it possible its Lithium and Carpet conflicting?

**Comment by 2No2Name** [comment]
It is totally unclear what is causing this issue and due to the long list of mods it is hard to work on this. Treating as won't fix until the reason is more clear or a lot of users with different mods have this issue
