### ISSUE TITLE
Lithium's Sleeping Shulkers breaks Charm mod Functionality

### ISSUE THREAD

**Issue by MoonliteDelight** [jellysquid3/Lithium#439]
### Version Information

lithium-fabric-mc1.19.2-0.10.4
Charm-fabric-1.19.2.-4.4.4

One of Charm's added tweaks is the ability to right click a shulker over an item in the inventory to store the item(s) away in the shullker without having to place it. Unfortunately, it appears Lithium's sleeping shulkers mixin disables this functionality as well as the ability to see the inventory of the shulker. 

There's a possibility it does the same with mods with similar features/tweaks. 
Current workaround is to just disable the sleeping shulkers mixin in the config file.

**Comment by 2No2Name** [comment]
The charm mod authors can work around this permanently if it still in an issue: https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric.mod.json-or-neoforge.mods.toml
