### ISSUE TITLE
Modpack incompatibility

### ISSUE THREAD

**Issue by Punch43** [jellysquid3/Lithium#441]
### Version

> Lithium-fabric-mc1.19.2-0.10.4

### Reproduction Steps

>Starting the game with my personnal modpack

### Crash Report File

[2023-01-15-1.log.gz](https://github.com/CaffeineMC/lithium-fabric/files/10420300/2023-01-15-1.log.gz)

### Additional Information

Lithium works perfectly fine when used alone with sodium and iris.
My modpack also works well alone.
It's only when i add lithium to my modpack that the launcher crashes before being able to start the game (exit code: 1).

**Comment by mrjasonn** [comment]
This might happen due to incompatibility and the changes Lithium makes.

**Comment by 2No2Name** [comment]
It is unclear which other mod lithium is incompatible with. Setting
mixin.world.block_entity_ticking.sleeping.campfire=false
in the lithium config might work around this.

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json

**Comment by 2No2Name** [comment]
Closing as the workaround probably resolves this
