### ISSUE TITLE
[1.15~1.17] Inconsistent tnt movement behavior with vanilla, if tnt moves and collides with a block with <1E-7 intersection

### ISSUE THREAD

**Issue by Fallen-Breath** [jellysquid3/Lithium#442]
#### Instructions

Yeah, some fun 1E-7 thing I guess

In vanilla, tnt is able to move and slightly collide without a block without considered being blocked by the block. Here slightly means < 1E-7 block. With lithium in specific mc version range, that behavior is changed

![image](https://user-images.githubusercontent.com/28978806/214312221-166a3258-8646-450c-bbe0-3d419948ffe5.png)

------------------------

### Reproduction Steps

1. Place the following blocks in the correct direction. Command block command: `summon tnt ~1 ~-0.5 ~ {Motion: [0d, 0d, 0.01000005d], Fuse:80}`

  ![image](https://user-images.githubusercontent.com/28978806/214313790-e6dc2668-f793-4f1e-9668-9b0bc14ff936.png)

2. Press the button, watch the summoned tnt

**Vanilla** behavior: TNT gets launched by the slime block

**Lithium** behavior: TNT falls straight down

![image](https://user-images.githubusercontent.com/28978806/214314781-cd3d3eab-3a0b-42c3-bf9a-95e7c91ed42e.png)

### Version Information

Tested with

| MC version | lithium version | matches vanilla?   |
| ---------- | --------------- | ------------------ |
| 1.15.2     | 0.4.6           | :x:                |
| 1.16.4/5   | 0.6.4           | :x:                |
| 1.17.1     | 0.7.5           | :x:                |
| 1.18.2     | 0.10.3          | :x:                |
| 1.19       | 0.8.0           | :heavy_check_mark: |
| 1.19.3     | 0.10.4          | :heavy_check_mark: |

Edited: this table contains incorrect result. See https://github.com/CaffeineMC/lithium/issues/442#issuecomment-1403067754 for updated result

### Other Information

This issue might affect other kinds of entity as well, tnt is just an example

There might be some unfound issues which are also related to this 1E-7 thing, e.g. if the piston extends slower and the tnt collides with the slimeblock, what tnt's z coord will be, sill .51000005, or another adjusted value

Potential vanilla bug exposed, cuz tnt being launched doesn't make any sense. This vanilla behavior happens in 1.14+, and lithium covers this vanilla issue until 1.19

Some research of this issue can be found in https://docs.qq.com/doc/DU0N0elZsTVN0TXNo (in Chinese tho)

Minecraft bug report: https://bugs.mojang.com/browse/MC-259354

**Comment by 2No2Name** [comment]
Tested with

| MC version | lithium version | matches vanilla?   |
| ---------- | --------------- | ------------------ |
| 1.18.2     | 0.7.10           | :heavy_check_mark: |
| 1.18.2     | 0.10.3          | :heavy_check_mark: |

**Comment by 2No2Name** [comment]
I think this commit fixed the issue:

https://github.com/CaffeineMC/lithium-fabric/commit/dfc828b98d71ba9d63ed1f29a86c183b9708c3ce

**Comment by 2No2Name** [comment]
For 1.17.x you can disable the suspected mixin by adding the following line to the lithium config file

`mixin.shapes.specialized_shapes=false`

**Comment by Fallen-Breath** [comment]
Ah I know why I marked 1.18.2 as affected. There's another setup (tnt duper) that we used to test at the beginning. It behaves differently in 1.18.2 so I just assmued the simple setup (shown in this issue) works the same

**The tnt duper setup**

![image](https://user-images.githubusercontent.com/28978806/214468851-491092c8-645a-465c-a2ab-851bdec8b111.png)

Requires [fabric-carpet](https://github.com/gnembon/fabric-carpet) mod to override tnt initial velocity. Use command `/carpet hardcodeTNTangle 4.457099494579702` before activate

**Behavior**

![image](https://user-images.githubusercontent.com/28978806/214468720-6c5487e6-5cd2-4313-b503-1f102117054c.png)

**Reproduced with**

- mc1.18.2
- lithium 0.10.3
- fabric-carpet 1.4.66

Also it should be reproduce-able with only lithium, if you test it long enough

I might need to find another simple setup for this

**Comment by Fallen-Breath** [comment]
Updated table (update 2)

| MC version | lithium version | matches vanilla? (simple) | matches vanilla? (duper) |
| ---------- | --------------- | ------------------------- | ------------------------ |
| 1.15.2     | 0.4.6           | :x:                       | :x:                      |
| 1.16.4/5   | 0.6.4           | :x:                       | :x:                      |
| 1.17.1     | 0.7.5           | :x:                       | :x:                      |
| 1.18.2     | 0.10.3          | :heavy_check_mark:        | :warning:                |
| 1.19       | 0.8.1           | :heavy_check_mark:        | :warning:                |
| 1.19.3     | 0.10.4          | :heavy_check_mark:        | :warning:                |

Assuming fabric-carpet doesn't changed related entity movement logic

I'm a bit not sure if the simple setup and the duper setup are the same issue now

**Updated**

The behavior in mc1.18.2 ~ mc1.19.3 lithium is even locational

![image](https://user-images.githubusercontent.com/28978806/214500528-ddd67237-e18d-4375-b583-3afe46b8e318.png)

Example behavior mismatch location: piston coordinate = `-2 -58 59`

**Comment by Fallen-Breath** [comment]
> Ah I know why I marked 1.18.2 as affected. There's another setup (tnt duper) that we used to test at the beginning. It behaves differently in 1.18.2 so I just assmued the simple setup (shown in this issue) works the same

Migrated this into a separated issue (#443). Now this issue focuses more on the 1e-7 margin thing

**Comment by 2No2Name** [comment]
If this issue only applies to versions up to 1.17 there won't be a fix as there are currently no backports to 1.17 and earlier planned
