### ISSUE TITLE
Entity movement behavior different from vanilla when last collision shape reduces movement to less than 1e-7

### ISSUE THREAD

**Issue by Fallen-Breath** [jellysquid3/Lithium#443]
The issue is splitted from #442

#### Instructions

The following tnt duper behavior changes when the tnt entity is nearby a chunk border

#### Reproduction Steps

1. Install [fabric-carpet](https://github.com/gnembon/fabric-carpet) mod
2. Build 2 of the tnt duper in the following image in a correct direction
    - The coordinate of the sticky piston are `-2 -58 59` and `-12 -58 59`

   ![image](https://user-images.githubusercontent.com/28978806/214572408-adb670d2-0743-458e-845b-83e9c8dc0418.png)

    ![image](https://user-images.githubusercontent.com/28978806/214572056-7f884f63-04bf-4936-bd11-3f426924cfe9.png)

3. Use fabric-carpet's command `/carpet hardcodeTNTangle 4.457099494579702` to override tnt initial velocity
4. Activate the tnt duper with 4gt pulse every 8gt

#### Behavior

![image](https://user-images.githubusercontent.com/28978806/214571460-af1401fe-14fd-465d-bc7b-7f7f2332ec3f.png)

**Expected** behavior: Both of these 2 tnt dupers launch tnt on retract (this is also the vanilla behavior)

**Actual** behavior: The left duper in the image doesn't launch tnt, which behavior wrongly. Only the right one launch tnt

### Version Information

Reproduced with

| MC version | lithium version | carpet version |
| ---------- | --------------- | -------------- |
| 1.18.2     | 0.10.3          | 1.4.66         |
| 1.19       | 0.8.1           | 1.4.79         |
| 1.19.3     | 0.10.4          | 1.4.93         |

### Other Information

The behavior is locational. The wrong behavior only happens nearby chunk border

The wrong behavior should be reproduce-able with only lithium, if you test it long enough and wait for a tnt to be created with the special velocity

Example wdl (1.18.2):  [void.zip](https://github.com/CaffeineMC/lithium-fabric/files/10499556/void.zip)

**Comment by Fallen-Breath** [comment]
Tested with older mc versions after applied the fix (https://github.com/CaffeineMC/lithium-fabric/issues/442#issuecomment-1402417016) of #442. This issue still affect the following versions

| MC version | lithium version | carpet version |
| ---------- | --------------- | -------------- |
| 1.16.4/5   | 0.6.4           | 1.4.44         |
| 1.17.1     | 0.7.5           | 1.4.56         |

**Comment by 2No2Name** [comment]
For block collisions this is fixed by https://github.com/CaffeineMC/lithium-fabric/commit/61f1471b321367a5e470964a6d51daa41aa71221

For entity collisions (boats & shulkers) this is still an issue

**Comment by 2No2Name** [comment]
Should also be fixed for entity collisions now, but not 100% sure

**Comment by 2No2Name** [comment]
Will reopen if any new issues surface
