### ISSUE TITLE
Crash with gigeresque

### ISSUE THREAD

**Issue by benio1394** [jellysquid3/Lithium#447]
### Version
1.19.2 0.10.4

### Reproduction Steps

Launching game with every version of gigeresque mod causes game crash. Unfortunably without crash log. I have only logs from console

### Crash Report File

https://pastebin.com/6t8sxrnL

**Comment by 2No2Name** [comment]
Add
mixin.ai.task.memory_change_counting=false
to the lithium.properties file in the config folder to work around it.
If you report to the gigeresque mod, you can link https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json to them.

**Comment by AzureDoom** [comment]
> Add mixin.ai.task.memory_change_counting=false to the lithium.properties file in the config folder to work around it. If you report to the gigeresque mod, you can link https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json to them.

This likely is due to the AI library we use, SmartBrainLib that extends the Minecraft Brain AI.

**Comment by AzureDoom** [comment]
I have sent a PR to SmartBrainLib now for this!
