### ISSUE TITLE
Crash on 1.19.2 FABRIC

### ISSUE THREAD

**Issue by pokesmells** [jellysquid3/Lithium#448]
### Version

> Fabric Loader 0.14.4 - Fabric API fabric-api-0.73.2+1.19.2
> lithium-fabric-mc1.19.2-0.10.4

### Reproduction Steps

> 1. Load into brand new world/and or already made world.
> 2. Load in new chunks and simply move around.
> 3. Crash will occur.

### Crash Report File

[crash-2023-02-21_11.43.45-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/10796420/crash-2023-02-21_11.43.45-server.txt)

Exit Code: -805306369.

### Additional Information

This crash does not occur when Lithium is uninstalled.

**Comment by 2No2Name** [comment]
This is probably caused by some mod that introduces unsafe multithreading into chunk loading.
