### ISSUE TITLE
Seperate alloc.enum_values mixins

### ISSUE THREAD

**Issue by CalvinMT** [jellysquid3/Lithium#450]
**Is your feature request related to a problem? Please describe.**
In order to disable `mixin/alloc/enum_values/RedstoneWireBlockMixin`, I need to add `"mixin.alloc.enum_values": false` inside my mod's `fabric.mod.json` file. However, doing so also disables all other mixins in the same `enum_values` folder. Because of this, I find myself required to disable AI mixins (`mixin.ai.task.launch` and `mixin.ai.task.replace_streams`) which have nothing to do with my mod. Not disabling these AI mixins gives errors pointing towards `mixin.ai.task.launch` and `mixin.ai.task.replace_streams`.

**Describe the solution you'd like**
Place each file in the `mixin/alloc/enum_values` folder into their own folder so that users can disable them individually.

**Comment by 2No2Name** [comment]
Your proposed solution is good, I will do that.
Additionally the dependency of the `ai.task` mixins will be explicitly stated.

**Comment by 2No2Name** [comment]
Can you show the error message regarding `mixin.ai.task...`?

**Comment by CalvinMT** [comment]
I should have added it in my initial post, sorry.
Here is a log file with the below lines added to the `fabric.mod.json` file: [powerstones_lithium_ai_task_launch.log](https://github.com/CaffeineMC/lithium-fabric/files/10890452/powerstones_lithium_ai_task_launch.log)
```json
"custom": {
    "lithium:options": {
        "mixin.alloc.enum_values": false,
        "mixin.block.redstone_wire": false
    }
}
```
These errors appeared after trying to load a single player world, right before entering the world.
The errors disappear after adding `mixin.ai.task.launch` and `mixin.ai.task.replace_streams`.

Here is the list of mods I had installed when those errors showed up:
- fabric-api-0.75.1+1.19.3
- ferritecore-5.1.0-fabric
- lithium-fabric-mc1.19.3-0.10.4
- powerstones-2.0.0+1.19.3 (my mod)

**Comment by 2No2Name** [comment]
I think this might be related to ferritecore, not sure
