### ISSUE TITLE
Crash on latest version 1.19.2 Fabric

### ISSUE THREAD

**Issue by pokesmells** [jellysquid3/Lithium#452]
### Version

lithium-fabric-mc1.19.2-0.11.0
Fabric Loader 0.14.17 MC 1.19.2

### Reproduction Steps

> 1. Update Lithium
> 2. Open MC
> 3. Crash!

### Crash Report File

https://mclo.gs/kPbLNUu

### Additional Information

> it may be due to BCLib? I have no clear idea but here's the report!

**Comment by OroArmor** [comment]
Also crashes on quilt. The log isnt as in depth: https://forum.quiltmc.org/t/quilt-wont-load-anymore-after-installing-the-missing-depending-mods-giving-me-an-internal-error-now/737/4

**Comment by SooarynAC** [comment]
I have the same error after updating, previous version works fine.

**Comment by fggfh** [comment]
Same, also with BCLib.

**Comment by KB-Q** [comment]
I'm also getting the same error: https://mclo.gs/o3rpZYb

"Mixin apply for mod lithium failed lithium.mixins.json:world.temperature_cache.BiomeMixin from mod lithium -> net.minecraft.class_1959: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException PRIVATE @Overwrite method method_21740 in lithium.mixins.json:world.temperature_cache.BiomeMixin from mod lithium cannot reduce visibiliy of PUBLIC target method"

**Comment by pokesmells** [comment]
For anyone else having this error, you can try adding 

**mixin.world.temperature_cache=false**

Add this to the config file of Lithium, which would be located in your config folder.

**Comment by KB-Q** [comment]
> For anyone else having this error, you can try adding
> 
> **mixin.world.temperature_cache=false**
> 
> Add this to the config file of Lithium, which would be located in your config folder.

I only see a lithium.properties in the config folder, is that the config file?

**Comment by 2No2Name** [comment]
Yes

**Comment by NLMulti** [comment]
This workaround works!
