### ISSUE TITLE
Crash with Create when pondering due to unsafe cast

### ISSUE THREAD

**Issue by TropheusJ** [jellysquid3/Lithium#455]
### Version Information

0.11.0 (1.19.2)

### Expected Behavior

Not crashing

### Actual Behavior

Crashing

### Reproduction Steps

According to the [original issue](https://github.com/Fabricators-of-Create/Create/issues/839):
> 1. Ponder an item
> 2. During animation it will crash

### Other Information

[This comment](https://github.com/CaffeineMC/lithium-fabric/blob/eaaa75622f67d71065f39839706eac84c6884c20/src/main/java/me/jellysquid/mods/lithium/common/entity/movement/ChunkAwareBlockCollisionSweeper.java#L131) is correct. That cast fails with Ponder's simulated worlds.
report: https://gist.github.com/aunrea/6275a8588337789329477732f1d1ad72

**Comment by caoimhebyrne** [comment]
It appears @2No2Name was aware of this possibility back in 2020 according to the git blame:
https://github.com/CaffeineMC/lithium-fabric/blob/eaaa75622f67d71065f39839706eac84c6884c20/src/main/java/me/jellysquid/mods/lithium/common/entity/movement/ChunkAwareBlockCollisionSweeper.java#L131

**Comment by 2No2Name** [comment]
Can anyone test this with the a newer github action build that includes the above commit?

**Comment by ereese99** [comment]
[message (2).txt](https://github.com/CaffeineMC/lithium-fabric/files/11003035/message.2.txt)

Got this crash as well

**Comment by 2No2Name** [comment]
Please test with Lithium 0.11.1

**Comment by Parilia** [comment]
Can confirm 0.11.1 fixes issue
