### ISSUE TITLE
Separate config for ticking lit/unlit campfires

### ISSUE THREAD

**Issue by No3371** [jellysquid3/Lithium#459]
**Is your feature request related to a problem? Please describe.**
Mods like Survival Campfires and Totally Lit track campfires' burn time with NBT data, sleeping lit campfires break these mods.

**Describe the solution you'd like**
Split `mixin.world.block_entity_ticking.sleeping.campfire` into `mixin.world.block_entity_ticking.sleeping.campfire.lit` and `mixin.world.block_entity_ticking.sleeping.campfire.unlit`

**Describe alternatives you've considered**
Or maybe it's possible to provide a way (nbt tag?) for modders to prevent campfires/block entities from sleeping? This could be even better because most of the time only player-placed campfires need to be ticked.

**Comment by No3371** [comment]
The reason why separate it instead of let players just turn off campfire sleeping all together is there are modders/builders use campfires as roofs or something, there could be hundreds of unlit campfire in a single village.

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/commit/9d50f7db1bcdaa6128fd2da614074a7a81e76e12
