### ISSUE TITLE
Ticking entity [Crash]

### ISSUE THREAD

**Issue by lojokey** [jellysquid3/Lithium#461]
------------------------
### Version
lithium-fabric-mc1.18.2-0.10.3

### Reproduction Steps

1. Create a new world or load some new chunks
2. Game freezes and crashes (ticking entitiy) 

### Crash Report File
[crash-2022-08-09_14.43.33-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/11061455/crash-2022-08-09_14.43.33-server.txt)

### Additional Information

The crash does not happen without Lithium installed

**Comment by 2No2Name** [comment]
Crash report lithium and minecraft version do not match the description

Probably an issue with the origins mod

You can try updating lithium.

**Comment by lojokey** [comment]
Oh I am sorry! Its wrong crash report
Here is the correct one.
[crash-2023-03-24_14.04.45-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/11065563/crash-2023-03-24_14.04.45-server.txt)

**Comment by 2No2Name** [comment]
Might be an incompatibility with Memory Leak Fix

**Comment by pajicadvance** [comment]
> Might be an incompatibility with Memory Leak Fix

I thought this as well and tried reproducing the issue with only Lithium and Memory Leak Fix, but it seems to work fine.

**Comment by lojokey** [comment]
By the way, all of the optimiztion mods i use are from the Fabolous Optimiztion modpack with the same configs for them

**Comment by chamychu** [comment]
i have the same issue here

[crash-2023-03-23_22.32.04-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/11067813/crash-2023-03-23_22.32.04-server.txt)

**Comment by Jorma17** [comment]
> Might be an incompatibility with Memory Leak Fix

I have the same issue. Disabling `Memory Leak Fix` seems to fix it.

**Comment by chamychu** [comment]
> > Might be an incompatibility with Memory Leak Fix
> 
> I have the same issue. Disabling `Memory Leak Fix` seems to fix it.

That seemed to be the issue thanks
