### ISSUE TITLE
Crashing 1.19.2 Mod Compatibility 

### ISSUE THREAD

**Issue by CantWeAllDisagree** [jellysquid3/Lithium#462]
### Version

lithium-fabric-mc1.19.2-0.11.1

### Reproduction Steps

1. Have [HWG](https://modrinth.com/mod/happiness-is-a-warm-gun) [SmartBrainLib](https://modrinth.com/mod/smartbrainlib/version/1.19.2-1.8) and [Azurelib](https://modrinth.com/mod/azurelib/version/1.0.12) installed.

2. Launch Minecraft

3. Crash

### Crash Report File

https://paste.atlauncher.com/view/55acd359-33b2-4a43-b660-676e7924c677

**Comment by pajicadvance** [comment]
Adding the line `mixin.ai.task.memory_change_counting=false` to the Lithium config file located at `.minecraft/config/lithium.properties` should let you use both mods together. This will disable one of Lithium's optimizations, however.

**Comment by CantWeAllDisagree** [comment]
Works thanks!

**Comment by 2No2Name** [comment]
Mod authors can also disable lithium's mixins automatically: https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json
