### ISSUE TITLE
Move NearbyEntityListener::forEachChunkInRangeChange call to after Fabric Api's ServerEntityEvents#ENTITY_LOAD runs

### ISSUE THREAD

**Issue by Fuzss** [jellysquid3/Lithium#465]
Hey there, so I have a couple mods that add additional goals to some vanilla entities which are of type `AvoidEntityGoal`, e.g. make villagers avoid/flee from skeletons. I do this using Fabric Api's `ServerEntityEvents#ENTITY_LOAD` callback, since this seems to be the best place for such a thing without having to resort to custom mixins.

When doing this with Lithium installed, the game crashes when my new goals are trying to be added in `ServerEntityEvents#ENTITY_LOAD` with the following exception:
`java.lang.IllegalStateException: Cannot add sublisteners after listening range was set!` ([full crash-report](https://gist.github.com/Fuzss/9fde0233fa9ee34c4e44d29e53af2c44))

This happens since `NearbyEntityListenerMulti#range` is set in [`NearbyEntityListenerMulti::getChunkRange`](https://github.com/CaffeineMC/lithium-fabric/blob/740ffc7a77894c4b3e394ffca0e43e8594e3e364/src/main/java/me/jellysquid/mods/lithium/common/entity/nearby_tracker/NearbyEntityListenerMulti.java#L29) which runs before the Fabric Api callback.

Would it be possible to set the range field after Fabric Api's callback has run, either by moving the injection in [`ServerEntityManagerMixin`](https://github.com/CaffeineMC/lithium-fabric/blob/740ffc7a77894c4b3e394ffca0e43e8594e3e364/src/main/java/me/jellysquid/mods/lithium/mixin/ai/nearby_entity_tracking/ServerEntityManagerMixin.java#L33) or by migrating to the Fabric Api callback at a phase that runs after `fabric:default`?

**Comment by 2No2Name** [comment]
Your request is not possible, but instead I replaced the IllegalStateException with code that handles the situation correctly. This should fix the issue without futher action from your side.
