### ISSUE TITLE
Conflicts with "carpet-tis-addition-mc1.18.2-v1.32.0.jar",It's true!

### ISSUE THREAD

**Issue by FANXING-0710** [jellysquid3/Lithium#467]
### Version

lithium-fabric-mc1.18.2-0.14.19

### Reproduction Steps

Conflicts with "carpet-tis-addition-mc1.18.2-v1.32.0.jar",It's true!

### Crash Report File

[latest.log](https://github.com/CaffeineMC/lithium-fabric/files/11184548/latest.log)

**Comment by 2No2Name** [comment]
Update your carpet-tis-addition https://github.com/TISUnion/Carpet-TIS-Addition/releases
