### ISSUE TITLE
Server timing out and crashing (ChunkAwareBlockCollisionSweeper)

### ISSUE THREAD

**Issue by soupcraft** [jellysquid3/Lithium#468]
### Version

>lithium-fabric-mc1.19.2-0.11.1

### Reproduction Steps

> Use C2ME and Lithium in server

### Crash Report File

> https://mclo.gs/w1REyY8

### Additional Information

> This could be C2ME and lithium conflicting, a bug with lithium, or a bug with C2ME from what I see
> I get this error from C2ME too "C2ME worker #2: Retried waiting for GCLocker too often allocating 524288 words" before the crash happens

**Comment by itsdinkd** [comment]
C2ME is experimental, however, so is lithium for 1.19.2 when using a decent amount of mods it has tons of issues.

**Comment by itsdinkd** [comment]
i however have the same issue, i am not using C2me though

![image](https://github.com/CaffeineMC/lithium-fabric/assets/35115304/61a00196-3bde-4361-8242-e074cca925c6)

https://gist.github.com/itsdinkd/aacfeafb792f6069b647d93dab07a2cf

**Comment by 2No2Name** [comment]
First issue is with C2ME. The issue without C2ME doesn't show that Lithium causes the watchdog crash.
