### ISSUE TITLE
Server Install Docs

### ISSUE THREAD

**Issue by The-Code-Monkey** [jellysquid3/Lithium#47]
Just came across your mod but how do I install this server side the docs say you can do but theres no instructions on how to.

**Comment by AMereBagatelle** [comment]
You will need the Fabric Loader, gotten at [https://fabricmc.net/use/](https://fabricmc.net/use/).
Installation instructions are on that same page.
Then, once you have installed Fabric, you can simply put Lithium in the `mods` folder that is generated.

**Comment by jellysquid3** [comment]
Lithium is installed like any other Fabric mod... we don't have special installations instructions. I can add a link to Fabric's installation page on CurseForge, but I can't provide support for installing Fabric itself.

**Comment by The-Code-Monkey** [comment]
Cheers didn't know what fabric was, cheers
