### ISSUE TITLE
posible issue with mob spawning on skyblock maps

### ISSUE THREAD

**Issue by wilebaldo** [jellysquid3/Lithium#470]
I have and issue with a specific skyblock map (https://www.planetminecraft.com/project/skyblock-4/)

and I'm playing on minecraft 1.19.4

everthing is ok, except the pacific mob spawning. lookin for and answer on the oficial discord for that skyblock they said is an issue with this mod, I have the most new, and unistall but I still have the same issue is no spawn the mobs.

**Comment by 2No2Name** [comment]
A previously released lithium version corrupted heightmaps. You can fix this by
1. Update Lithium
2. Edit World -> Optimize World -> Erase Cached Data
