### ISSUE TITLE
Game crashes when using with SubTick

### ISSUE THREAD

**Issue by xwillq** [jellysquid3/Lithium#473]
### Version

Minecraft: 1.19.4
Lithium: lithium-fabric-mc1.19.4-0.11.1
SubTick: 1.0.11

### Reproduction Steps

1. Place hopper
2. Run `/tick freeze`
3. Run `/queueStep blockEntity`
4. Game crashes or freezes

`mixin.world.block_entity_ticking.sleeping.hopper` must be set to `true`.

I believe can be reproduced anywhere, I tested this in fresh superflat world with void template.

### Crash Report File

[crash.log](https://github.com/CaffeineMC/lithium-fabric/files/11472563/crash.log)

### Additional Information

When performing `queueStep blockEntity`, SubTick gets positions of block from `net.minecraft.server.level.ServerLevel::blockEntityTickers` and for some reason hoppers return position `null`. I'm not sure if this is intended behavior or bug, since Lithium config disables this. If this is a bug, it might break a lot more mods than just SubTick.

Here is the issue in SubTick repo I opened before looking into Lithium configs and source:  https://github.com/lntricate1/SubTick/issues/7

**Comment by 2No2Name** [comment]
Even though this issue is clearly caused by lithium's special behavior, it is a lot easier to fix this on the side of the other mods. I submitted a PR to them.
