### ISSUE TITLE
Extremely high ping times with certain mixin enabled

### ISSUE THREAD

**Issue by jaapieaapie1** [jellysquid3/Lithium#475]
### Version Information

lithium-fabric-mc1.19.4-0.11.1

### Expected Behavior

To have normal ping times.

### Actual Behavior

Some players, it seems like players running vanilla minecraft or only optifine have extremely high ping times up to 2000ms.

### Reproduction Steps

(I could not reproduce this by myself but multiple players on my server had this issue)
1. Run vanilla minecraft
2. Play normal survival minecraft. (it appears to happen more in the nether dimension but it also happens in the overworld from time to time)
3. check your ping (you'll notice)

### Other Information

I used the following mods (but this still occured without them):
1. ledged
2. luckperms
3. phosphor
4. spark

The issue was resolved by disabling the following mixin: `mixin.world.player_chunk_tick`

**Comment by jaapieaapie1** [comment]
Discord support thread: https://discord.com/channels/602796788608401408/1111355913853476916

**Comment by 2No2Name** [comment]
Mixin was removed during update to 1.20.2
