### ISSUE TITLE
Randomised (seed undepended!!!) trees, flowers and watermelon generation if Fabric API installed

### ISSUE THREAD

**Issue by VanilaWay** [jellysquid3/Lithium#477]
### Version Information
Java 17.0.6 from Debian 12 repository
Lithium Fabric 0.11.2 (affected both 1.20 and 1.20.1 versions)
Fabric loader 0.14.21
Fabric API 0.83
No other mods

### Expected Behavior
Two worlds with single seed should be absolutely indentical, but they other

### Reproduction Steps
- Load MC 1.20 / 1.20.1 with Fabric API and Lithium
- Create world with any seed (work in any biomes and seeds)
- Take screenshots to easier make compare easier
- Quit and recreate this world
- Done!

Random seed and cords (sorry, not saved):
![2023-06-13_17 41 37](https://github.com/CaffeineMC/lithium-fabric/assets/122021430/22a08470-fc02-4a9e-ac08-c6fc38babf68)
![2023-06-13_17 47 14](https://github.com/CaffeineMC/lithium-fabric/assets/122021430/f71ac652-3989-4374-b1ae-80a13da5b79d)

Seed 1743770523999351415. XYZ: -909 77 -2623
![2023-06-13_15 59 37](https://github.com/CaffeineMC/lithium-fabric/assets/122021430/8e1993a3-b9ef-4188-acc5-d992e2384f6b)
![2023-06-12_23 35 19](https://github.com/CaffeineMC/lithium-fabric/assets/122021430/2633a16d-9d4e-4ced-ba73-a30e6f642b51)
![2023-06-13_16 14 21](https://github.com/CaffeineMC/lithium-fabric/assets/122021430/b83d2e0e-9662-4277-9fc7-d49b63c5966e)
![2023-06-13_16 37 29](https://github.com/CaffeineMC/lithium-fabric/assets/122021430/1a1e0b84-26b7-450d-a8e3-3949493d8d18)

Without Fabric API it work as Vanilla, how this location should look:
![2023-06-13_16 53 54](https://github.com/CaffeineMC/lithium-fabric/assets/122021430/7a368470-ef2d-48be-8bc2-c2dc259ce069)

**Comment by DragonEggBedrockBreaking** [comment]
Does this also occur with only Fabric API, without Lithium?

**Comment by pajicadvance** [comment]
Just tested by myself, the generation seems randomized with just Fabric API installed without Lithium.

**Comment by pajicadvance** [comment]
This should probably be reported to the developers of Fabric API.

**Comment by Lolothepro** [comment]
Vanilla bug: https://bugs.mojang.com/browse/MC-55596

**Comment by VanilaWay** [comment]
Vanilla work normally (generation indentical with lithium-only screenshot). Its realy FAPI bug
