### ISSUE TITLE
server crash caused by lithium(?)

### ISSUE THREAD

**Issue by GitUser14975** [jellysquid3/Lithium#479]
My minecraft server running on 1.20.1 (fabric 0.14.21) crashed and from what i could tell by looking at the crash log it could be caused by lithium (lithium-fabric-mc1.20.1-0.11.2.jar). I don't know how to reproduce the bug, I had minecraft in the background and when I returned to it I saw that the server has crashed. I don't know how did that happen, but I was alone on the server and nobody was doing anything.

Here's the crash log:
https://gist.github.com/TenKotowsky/a6d2169f0c814d9bfcc2046806296bca

**Comment by GitUser14975** [comment]
The crash occured once again. I was standing in one place, not moving or doing anything and it happened out of nowhere

**Comment by 2No2Name** [comment]
The crash report does not hint at lithium causing or being involved in this crash. I cannot tell from the crash report what the cause is, so you probably need to remove half of the mods at a time to find the mod that is causing this.

**Comment by 2No2Name** [comment]
Maybe this mod helps find the issue https://www.curseforge.com/minecraft/mc-mods/uwrad/files

**Comment by GitUser14975** [comment]
Oh alright, I thought there was a chance it could be lithium because it's the only mod name I could see there, sorry for wasting your time. And also thanks for this detector mod!
