### ISSUE TITLE
Overworld is removed from world_gen_settings when used with WilderWild and custom ChunkGenerator class

### ISSUE THREAD

**Issue by quiqueck** [jellysquid3/Lithium#480]
The base issue came up in this report: quiqueck/BCLib#113

I am still not sure what is happening, but I figured out some things while testing. The crash happens when BClib, Lithium and WilderWild are installed. But I think the issue is not with WilderWild, but instead with QuiltDataFixes in general.

Let me explain the setting:
BCLib is defining a custom ChunkGenerator class, that is registered as `bclib:betterx` to the builtin [ChunkGenerator Registry](https://github.com/quiqueck/BCLib/blob/2e42a06d8af8907e066d9c053a073e0c7a05846f/src/main/java/org/betterx/bclib/mixin/common/ChunkGeneratorsMixin.java#L23). I checked, and the registry contains the codec reference. We use this Generator for the Nether and the End. The overworld is using the vanilla ChunkGenerator.

Then there is [`QuiltDataFixes.updateWithAllFixers`](https://github.com/QuiltMC/quilt-standard-libraries/blob/1.20/library/misc/datafixerupper/src/main/java/org/quiltmc/qsl/datafixerupper/impl/QuiltDataFixesInternalsImpl.java#L70), which is used by the Mod [WilderWild](https://github.com/FrozenBlock/WilderWild/blob/1.20/src/main/java/net/frozenblock/wilderwild/WilderWild.java#L135). It just registers some simple fixes, as far as I can tell, nothing that is messing with the dimensions of a world.

Using BCLib and WilderWild will not cause any issues. When I add Lithium to the mix, the Overworld (remember the only dimension that does not use the custom ChunkGenerator) is deleted when the DataFixerers for `DataFixTypes.WORLD_GEN_SETTINGS` are executed in `LevelStorage.readGeneratorProperties`.

With and without Lithium, the DataFixer will issue an error:
> Unsupported key: bclib:betterx; Unsupported key: bclib:betterx

(which indicates, that there is a problem reading the custom ChunkGenerator, which is caused by a Vanilla DataFixer called `MissingDimensionFix`). When I create a new world with BCLib that does not include the custom ChunkGenerators, the error is not produced (as expected) and the overworld is not deleted. But as I said, without Lithium the missing generator type does not cause any issues, except for the error message.

Which leads me to suspect, that there is an interior problem between Lithium and QuiltDataFixes? However, I am not sure if this is caused by Lithium or QSL...

To confirm that the root cause of the problem is `MissingDimensionFix` (which is hard coded to the vanilla generator types), I went and added some Mixins, that add the custom type to the Vanilla DataFixers. This indeed solves the issue. However that feels quite intrusive. 

Since there are other mods out there that intruduce custom ChunkGenerators as well, this might be an issue worth looking into?

**Comment by TheGlitch76** [comment]
WilderWilds is using its own port of Quilt DFU API; it is disabled on our (QSL)'s end and not usable by mods through QSL or QFAPI.

**Comment by EthanRStokes** [comment]
Fixed on Wilder Wild's side. can close
