### ISSUE TITLE
Server crash during Textile Backup

### ISSUE THREAD

**Issue by archangel5432** [jellysquid3/Lithium#481]
### Version

lithium-fabric-mc1.19.2-0.11.1

### Reproduction Steps
1. Textile backup starts
2. Server crash

### Additional Information
The crash started after entering The End for the first time, before that everything worked fine. 

[crash-2023-07-21_20.41.15-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/12131193/crash-2023-07-21_20.41.15-server.txt)

**Comment by 2No2Name** [comment]
Does anything hint at Lithium causing this issue?
