### ISSUE TITLE
lithium wants a older version of sodium 

### ISSUE THREAD

**Issue by elijah100** [jellysquid3/Lithium#483]
im using the newest versions of both mods

**Comment by pajicadvance** [comment]
Provide your client log

**Comment by elijah100** [comment]
[latest.log](https://github.com/CaffeineMC/lithium-fabric/files/12265338/latest.log)

**Comment by pajicadvance** [comment]
The log barely contains any info, can you provide a crash report, or a log that contains your mod list?

**Comment by elijah100** [comment]
ok

**Comment by elijah100** [comment]
[crash-2023-08-04_18.35.24.3727-quilt_loader.txt](https://github.com/CaffeineMC/lithium-fabric/files/12265350/crash-2023-08-04_18.35.24.3727-quilt_loader.txt)

**Comment by pajicadvance** [comment]
You have several mod incompatibilities, and some of your mods have not been updated to support Sodium 0.5 yet. Use 0.4.10 for now.

**Comment by elijah100** [comment]
ok
