### ISSUE TITLE
Biomes don't update

### ISSUE THREAD

**Issue by LinkZeldasGuard** [jellysquid3/Lithium#484]
### Version Information

lithium-fabric-mc1.20.1-0.11.2

### Expected Behavior

Biomes changed using the /fillbiome command should be instantly visually changed.

### Actual Behavior

The changed biome only appears after fully rejoining the world.

### Reproduction Steps

Change any biome in a world using /fillbiome

### Other Information

No other mods in use, using Quilt loader

**Comment by 2No2Name** [comment]
Cannot reproduce
