### ISSUE TITLE
quilt official compatible?

### ISSUE THREAD

**Issue by Emil2010** [jellysquid3/Lithium#486]

**Comment by astridellensdottir** [comment]
no need. it works under quilt already.

**Comment by 2No2Name** [comment]
I can set it to quilt compatible in modrinth

**Comment by Emil2010** [comment]
ok, i knowled

**Comment by Feliks-WR** [comment]
Yes, do set to quilt compatible officially, so that quilt users can use it modrinth app.

**Comment by ragsmaroon** [comment]
> Yes, do set to quilt compatible officially, so that quilt users can use it modrinth app.

When adding content to an instance, select "override loaders"  in the top left hand corner and then select "fabric" in addition to the default selection of quilt in the menu it opened below.
