### ISSUE TITLE
[1.19.2] [Crash] Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by SlayerTheChikken** [jellysquid3/Lithium#487]
### Version
lithium-fabric-mc1.19.2-0.11.1

### Reproduction Steps
Unknown at this time, if a pattern is found I will modify this issue.

### Crash Report File
[crash-2023-09-06_19.00.09-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/12543125/crash-2023-09-06_19.00.09-server.txt)

### Additional Information
Open to LAN at the time, 2 other players.

**Comment by 2No2Name** [comment]
This is not caused by lithium. The stacktrace includes lithium due to an optimization to BlockPos allocations

**Comment by SlayerTheChikken** [comment]
Ah yea I later figured that out and forgot to close this issue, sorry about that..
