### ISSUE TITLE
1.20.2 support

### ISSUE THREAD

**Issue by PukPukov** [jellysquid3/Lithium#488]

**Comment by douira** [comment]
Sodium already supports 1.20.2. https://modrinth.com/mod/sodium

**Comment by douira** [comment]
my bad I was looking at the wrong repo. You'll just have to wait for lithium to get an update. Be rest assured, the maintainer is well aware that it's not yet updated and will get to it eventually.

**Comment by 2No2Name** [comment]
Please use the issue templates
