### ISSUE TITLE
Recipe button in Roughly Enough Items stops working with Lithium installed. Fabric 1.19.2

### ISSUE THREAD

**Issue by Halex000** [jellysquid3/Lithium#490]
### Version Information

lithium-fabric-mc1.19.2-0.11.1

### Expected Behavior

The + button should copy the recipe from the Roughly Enough Items recipe menu to the crafting table.
![Capture](https://github.com/CaffeineMC/lithium-fabric/assets/95841600/eda72387-fd4d-498c-b173-803b5d728560)
![1](https://github.com/CaffeineMC/lithium-fabric/assets/95841600/6e5f4d5c-f1d5-4748-8579-e5b7f9943041)

### Actual Behavior

The + button copies the recipe over to the crafting table incorrectly. This occurs for all vanilla and modded recipes.
![2](https://github.com/CaffeineMC/lithium-fabric/assets/95841600/3edee902-7dd4-474a-abf6-5119824bca02)

### Reproduction Steps

1. Install Roughly Enough Items, I am using RoughlyEnoughItems-9.1.657. I am also using the mods found below. 
I performed a binary search on my mod list until I identified Lithium as the cause for this bug.
![Capture](https://github.com/CaffeineMC/lithium-fabric/assets/95841600/d292544b-ad09-4287-819f-dce89c20ab02)

2. Place a crafting table and get the materials for a crafting recipe in your inventory, it can be any recipe.

3. Search for the recipe in Roughly Enough Items and click the plus button in the GUI to load it into the crafting table.

The recipe should be loaded incorrectly with Lithium installed.

### Other Information

Bug performed in fabric for 1.19.2

Mods used to recreate bug:
![Capture](https://github.com/CaffeineMC/lithium-fabric/assets/95841600/a975249f-712d-4bd5-83c4-5cf00778a78f)

**Comment by shedaniel** [comment]
This is now resolved on REI's side with https://github.com/shedaniel/RoughlyEnoughItems/issues/1492.
