### ISSUE TITLE
The nether wont load properly

### ISSUE THREAD

**Issue by AE53** [jellysquid3/Lithium#492]
------------------------

### Version Information
16.5-0.6.4
> lithium-fabric-mc1.19.4-0.11.1

### Expected Behavior
i expected the nether to fully load with no issues
### Actual Behavior
the top layer of blocks did not load unless i right clicked and the game knew they where there basically sticking me in place when walking inside an invisible block

### Reproduction Steps

i walked or spawned in the nether (i did both to make sure) and got bugged and right clicked the floor and saw blocks spawn
### Other Information
it was because i had other mods i will try to list them all. (all of them are on 1.19.4)

Essential (also the launcher i use)

cullleaves-fabric-3.0.3

phosphor-fabric-mc1.19.x-0.8.1

entityculling-fabric-1.6.2-mc1.19.4

[1.19.4-fabric]-Epic-Knights-8.2

appleskin-fabric-mc1.19.4-2.5.1

architectury-8.2.89-fabric

biomemakeover-FABRIC-1.19.4-1.9.5

Bookshelf-Fabric-1.19.4-18.0.6

cloth-config-10.1.105-fabric

CorgiLib-fabric-1.19.4-3.0.0.0

do-a-barrel-roll-3.2.0+1.19.4-fabric

eldritch-mobs-1.14.0

entityculling-fabric-1.6.2-mc1.19.4

fabric-api-0.87.0+1.19.4

geckolib-fabric-1.19.4-4.2

iris-mc1.19.4-1.6.9

jei-1.19.4-fabric-13.1.0.16

journeymap-1.19.4-5.9.7-fabric

mostructures-1.4.31.19.4

Oh_The_Biomes_You'll_Go-fabric-1.19.4-4.0.0.2

OptiFine_1.19.4_HD_U_I4

Origins-1.19.4-1.9.0

origins-plus-plus-2.2

Pehkui-3.7.8+1.14.4-1.20.1

phosphor-fabric-mc1.19.x-0.8.1

puffish_skills-0.9.0-1.19.4-fabric

reeses_sodium_options-1.6.4+mc1.19.2-build.93

SimpleVeinminer-1.4.0-beta3

sodium-extra-0.4.18+mc1.19.4-build.100

sodium-fabric-mc1.19.4-0.4.10+build.24

TerraBlender-fabric-1.19.4-2.2.0.168

ToolStats-Fabric-1.19.4-14.1.5

yet-another-config-lib-fabric-3.1.1+1.19.4

its more than likely one of them that just messes it up but i really dont want to do that but the mod you  guys made worked great for my frame rate which is nice.

**Comment by Phoenix-Starlight** [comment]
Do not use optifine with lithium.

**Comment by Boobies** [comment]
I'm not sure what that list of mods is supposed to be. There's Sodium, Iris, and OptiFine. I doubt they try loading all of these at once.
