### ISSUE TITLE
Watchdog crash (getChunkBlocking)

### ISSUE THREAD

**Issue by vanutp** [jellysquid3/Lithium#493]
### Version Information

Minecraft 1.20.1
Fabric API 0.89.3+1.20.1
Lithium 0.11.2
Moonlight 1.20-2.8.42
Supplementaries 1.20-2.6.7
Wilder Wild 2.1.6-Fabric+1.20.1

### Actual Behavior

The game hangs and gets killed by a watchdog when loading certain chunks

### Crash report

https://mclo.gs/DsBkTlE
With MixinTrace: https://mclo.gs/Vjs3ct6

### Reproduction Steps

1. Install the specified mods
2. Create a world with the seed 1879298942292900201
3. Teleport to -12720 100 12800

### Other Information

The issue was reported before: #456 and #438. In the latter case neither Supplementaries nor Wilder Wild were installed so this issue happens with multiple mods.

**Comment by embeddedt** [comment]
Can you try to get a log/crash report with https://legacy.curseforge.com/minecraft/mc-mods/fullstack-watchdog added?

**Comment by vanutp** [comment]
> Can you try to get a log/crash report with https://legacy.curseforge.com/minecraft/mc-mods/fullstack-watchdog added?

Sure: https://mclo.gs/e5zFnhU

**Comment by Zontyk** [comment]
i have a same problem

**Comment by 2No2Name** [comment]
I think this was fixed in the linked frozenlib issue
