### ISSUE TITLE
Data tracker crash?

### ISSUE THREAD

**Issue by SlayerTheChikken** [jellysquid3/Lithium#494]
### Version
lithium-fabric-mc1.19.2-0.11.1

### Reproduction Steps
Crash while fighting Warden

### Crash Report File
[crash-2023-11-01_12.05.53-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/13250103/crash-2023-11-01_12.05.53-server.txt)
[crash-2023-11-01_14.37.59-server.txt](https://github.com/CaffeineMC/lithium-fabric/files/13250104/crash-2023-11-01_14.37.59-server.txt)
[latest.log](https://github.com/CaffeineMC/lithium-fabric/files/13250106/latest.log)

### Additional Information
Could also be soul shards I guess https://github.com/0x00002a/Soul-Shards-Despawn/issues/6 , the issue was reported by some users... spawning in a warden and attacking it did not produce a crash nor did killing it in my game, however I was unable to find an ancient city, not sure if that has anything to do with it.

**Comment by 2No2Name** [comment]
This is probably due to the inject priorities in the data tracker mixin. Lithium should change the priority to inject even later than the At("RETURN")

**Comment by 2No2Name** [comment]
The data tracker mixin no longer exists in the latest version, due to the optimization now being in vanilla
