### ISSUE TITLE
Stuttering while walking on top 

### ISSUE THREAD

**Issue by ChildishGiant** [jellysquid3/Lithium#50]
It's hard to see in the preview but if you click the link you can see.
[hideousmenacingindri](https://gfycat.com/hideousmenacingindri)
![hideousmenacingindri](https://thumbs.gfycat.com/HideousMenacingIndri-size_restricted.gif)

**Comment by jellysquid3** [comment]
Are you able to reproduce this without Optifine installed?

**Comment by amnotbananaama** [comment]
This occurs in vanilla without any mods installed, and is not caused by Lithium. See https://bugs.mojang.com/browse/MC-156980

**Comment by jellysquid3** [comment]
[The other semi-relevant Discord discussion on this.](https://discord.com/channels/602796788608401408/648967810139029505/711993343629852713)

**Comment by ChildishGiant** [comment]
Ah, sorry about that
