### ISSUE TITLE
Crash at startup possibly due to conflict with Pehkui mod

### ISSUE THREAD

**Issue by AH139** [jellysquid3/Lithium#504]
Version:
lithium-fabric-mc1.20.4-0.12.1

Reproduction Steps:
1. Download Simply Optimized Modpack (I use Prism Launcher)
2. Disable all mods except for Lithium
3. Add Pehkui mod (Pehkui-3.7.12+1.14.4-1.20.4, most recent version as of this post's date), including recent fabric-loader mod
4. Start Minecraft
5. crash

Crash Report File:
[crash-2024-01-25_00.05.13-client.txt](https://github.com/CaffeineMC/lithium-fabric/files/14048770/crash-2024-01-25_00.05.13-client.txt)

When I disable Lithium, Pehkui works just fine.

**Comment by sheikh1233** [comment]
ive been having the same issue, im basically in the exact same situation (added mods to simply optimized on prism launcher, pehkui and lithium crash when together)

**Comment by sheikh1233** [comment]
it's a simply optimized thing, i tested your steps on a different modpack (Fabulously Optimized) and it worked fine

**Comment by sheikh1233** [comment]
@AH139 I got a solution- I deleted 2 mixins in the lithium properties file: **_mixin.experimental_** & **_mixin.experimental.chunk_tickets_**

**Comment by AH139** [comment]
Hello, I apologize for not replying sooner! I was able to fix the problem by deleting lithium's config file (lithium.properties) and starting Minecraft again so it regenerates with a fresh config and it didn't crash again after that. I still greatly appreciate your suggestions, thanks!
