### ISSUE TITLE
1.14? Not an issue, just a request

### ISSUE THREAD

**Issue by drzoidberg666** [jellysquid3/Lithium#51]
Hey I play on 1.14.4 and I do not wish to update my server, can you make a 1.14 version if it is easy? If it is, I would be very grateful although I do understand if you do not want to.

**Comment by Heitzenberg** [comment]
Why are you not updating to 1.15? 1.14 is not supported and won't be, no matter how many people ask for it.

**Comment by TheMadHau5** [comment]
Exactly. 1.15 is just 1.14 with bees and bugfixes. Almost nobody uses a 1.14 client anymore anyways so upgrading should be fine.

**Comment by AMereBagatelle** [comment]
You may compile the 1,14,4 branch of lithium, but it is no longer supported.  1.15 is better in nearly every way, however, so you may want to switch.

**Comment by jellysquid3** [comment]
Minecraft 1.14 is not supported any longer.
