### ISSUE TITLE
Wolf Armor Is Almost Unusable

### ISSUE THREAD

**Issue by LordEnder-Kitty** [jellysquid3/Lithium#515]
### Version Information

mc1.20.6-0.12.3 on fabric 1.20.6-0.15.11

### Expected Behavior

Wolf armor should absorb damage and crack as it loses durability. You should be able to repair it by right clicking with armadillo scute and remove it from the dog with shears.

### Actual Behavior

Wolf armor, when lithium is on the server, does not render cracking at low durability. When lithium is on the client, you are unable to heal or remove it in any way. at least most of the time. i've noticed it's a little inconsistent depending on what's happened to the armor. it's weird.

### Reproduction Steps

Just create a new world with lithium on and try messing with the dog armor. equip it, damage it, try healing or removing it, etc....

### Other Information

This was discovered on my friend group smp which we recently updated to 1.20.6 and the wolf armor was broken. i then later tested on a singleplayer world to see if it was just an issue with our server but i got it too. i then opened a fresh fabric instance with no mods and it worked as expected. then i tried adding some of the mods i was using and lithium was causing all the issues. i then removed it from my packed and rejoined our smp and the only thing not working was the cracking, however i could heal and remove it again.

that's pretty much it. didn't see any other reports of this yet so thought i'd mention it.

**Comment by 2No2Name** [comment]
Thank you very much for this report. Until this is fixed you can add the line

`mixin.entity.skip_equipment_change_check=false`

to the lithium.properties file in the config folder in the .minecraft folder.

**Comment by 2No2Name** [comment]
Should be fixed in latest lithium releases
