### ISSUE TITLE
1.21 Sculk sensors not triggering after reload

### ISSUE THREAD

**Issue by caek08** [jellysquid3/Lithium#522]
### Version Information

> lithium-fabric-mc1.21-0.12.5

### Expected Behavior

> Player noise don't seem to be triggering skulk sensors

### Actual Behavior

> Player noises should trigger skulk ssensors

### Reproduction Steps

> Load a chunk with a sculk sensor. `tp ~ ~ ~1000` followed by `tp ~ ~ ~-1000`
> Walk near a skulk sensor and see if the noise triggers a sensor.

### Other Information

> Try with naturally spawning skulk sensors
> Putting "mixin.world.game_events=false" in the config file and then setting it back to true seems to fix the issue

**Comment by 2No2Name** [comment]
Needs testing together with ferrite core, doesn't seem to occur with just lithium

**Comment by 2No2Name** [comment]
Confirmed with ferrite core on dedicated server, after reloading the world or with manually placed sensors

**Comment by 2No2Name** [comment]
Confirmed without ferritecore

**Comment by 2No2Name** [comment]
Fixed by https://github.com/CaffeineMC/lithium-fabric/commit/8536b72ed5723e7a73a9845e46b4af78530dbdb1
