### ISSUE TITLE
1.21 no chickens from eggs

### ISSUE THREAD

**Issue by Coding-Kiwi** [jellysquid3/Lithium#525]
### Version Information

lithium-fabric-mc1.21-0.12.5

### Expected Behavior

Chicken should spawn from thrown eggs

### Actual Behavior

No chicken spawn, or very very very rarely one spawns (see video)

### Reproduction Steps

Throw eggs

### Other Information

- I tested it with and without lithium, without lithium the chicken spawn normally
- I think it has something to do with an entity limit / mob cap? but it is not quite transparent what the limit is set to and what influences it

https://imgur.com/a/6Mc5x0r

**Comment by 2No2Name** [comment]
Thanks a lot for the report.
Vanilla's check for chicken spawning changed, includes collisions in a special way now. But lithium's new optimization for that was broken.

From my testing the above commit fixes the issue.

**Comment by 2No2Name** [comment]
Workaround: Add line to config/lithium.properties file:
`mixin.minimal_nonvanilla.collisions.empty_space=false`

**Comment by Coding-Kiwi** [comment]
Thank you for the quick analysis and workaround, can confirm `mixin.minimal_nonvanilla.collisions.empty_space=false` works
