### ISSUE TITLE
Water flows incorrectly

### ISSUE THREAD

**Issue by 2No2Name** [jellysquid3/Lithium#526]
Version Information

0.12.5

### Actual Behavior
![2024-06-19_20 08 36](https://github.com/CaffeineMC/lithium-fabric/assets/50278648/78a83b1f-84cc-49c9-af1b-07fb4d274a71)

### Expected Behavior

![2024-06-19_20 04 19](https://github.com/CaffeineMC/lithium-fabric/assets/50278648/8b546ac6-b161-4200-b277-afbea6e867fd)

### Reproduction Steps

See images

**Comment by LucZZ** [comment]
Same problem, but different scenario:
![image](https://github.com/CaffeineMC/lithium-fabric/assets/23156612/4772d212-0e22-45b3-9699-0ad8081c933a)

Problem appears in north-west and south-east

**Comment by 2No2Name** [comment]
Workaround: Add line to config/lithium.properties file:
`mixin.block.fluid.flow=false`
