### ISSUE TITLE
- Game crashed randomly

### ISSUE THREAD

**Issue by Fesuoy1** [jellysquid3/Lithium#527]
### Version
lithium-fabric-mc1.21-0.12.7

### Reproduction Steps
I don't know how to reproduce, it just happened

### Crash Report File

[crash-2024-06-21_05.48.44-server.txt](https://github.com/user-attachments/files/15922197/crash-2024-06-21_05.48.44-server.txt)

**Comment by Fesuoy1** [comment]
To clarify: the game crashed randomly while I was just playing modded survival minecraft

Edit: sorry if i didn't provide enough information, crash report file could help investigating the crash anyways

**Comment by wicivo** [comment]
I encountered this error as well
https://mclo.gs/cFCqyEV
https://mclo.gs/ffwxa4m

**Comment by wicivo** [comment]
![image](https://github.com/CaffeineMC/lithium-fabric/assets/116191734/de7f2997-47b5-49b1-9bf7-47cd02c5989f)
I understand it was because of the sheep

**Comment by wicivo** [comment]
There's also this https://mclo.gs/tTXv67z

**Comment by akbe2020** [comment]
I also had this

**Comment by akbe2020** [comment]
https://mclo.gs/WWoUeNj

**Comment by 2No2Name** [comment]
Can you test with this updated version (Unzip build-artifacts and replace your lithium-fabric-mc1.21-0.12.7.jar with the lithium-fabric-mc1.21-0.12.7+git.a063311.jar) https://github.com/CaffeineMC/lithium-fabric/actions/runs/9615646668

**Comment by Fesuoy1** [comment]
Sure I'll test it

**Comment by Fesuoy1** [comment]
> Sure I'll test it



> Can you test with this updated version (Unzip build-artifacts and replace your lithium-fabric-mc1.21-0.12.7.jar with the lithium-fabric-mc1.21-0.12.7+git.a063311.jar) https://github.com/CaffeineMC/lithium-fabric/actions/runs/9615646668

Well it seems to work now

**Comment by wicivo** [comment]
> > Sure I'll test it
> 
> > Can you test with this updated version (Unzip build-artifacts and replace your lithium-fabric-mc1.21-0.12.7.jar with the lithium-fabric-mc1.21-0.12.7+git.a063311.jar) https://github.com/CaffeineMC/lithium-fabric/actions/runs/9615646668
> 
> Well it seems to work now

Affirmative

**Comment by SNZ2X** [comment]
Had this issue too, seemed like a simple condition check, will test too.

**Comment by 2No2Name** [comment]
Other workaround is to disable experimental optimizations

**Comment by 2No2Name** [comment]
Assuming this is fixed by the fix
