### ISSUE TITLE
don't teleport with pearl to nether on 1.21

### ISSUE THREAD

**Issue by Linaryx** [jellysquid3/Lithium#528]
### Version Information

lithium-fabric-mc1.21-0.12.7

### Expected Behavior

teleport to another world with perl to portal (from overworld to nether)

### Active Behavior

don't teleport with pearl

### Reproduction Steps

> Example:
> 1. Place a portal to nether
> 2. Use a ender pearl
> 3. don't teleport to nether

**Comment by 2No2Name** [comment]
Tested by placing a nether portal, shooting an enderpearl slightly downards through it. Works
