### ISSUE TITLE
Lighting Bug

### ISSUE THREAD

**Issue by DrakePHOSE** [jellysquid3/Lithium#53]
Light seems to go through top slabs between bottom slabs when they are connected. An example video: https://gfycat.com/spottedjubilantindianringneckparakeet

Tested on:
Lithium Version: lithium-mc1.15.2-fabric-0.4.6-mod
Fabric Version: fabric-loader-0.8.2+build.194-1.15.2

**Comment by jellysquid3** [comment]
This issue has already been fixed in a snapshot build, but until that is back-ported to 1.15.x, you can install [Phosphor](https://www.curseforge.com/minecraft/mc-mods/phosphor-fabric) to work around it.

**Comment by DrakePHOSE** [comment]
I guess I missed it when I went thru your issue list. Thanks for the response, and thanks for making this mod. Cheers.
