### ISSUE TITLE
Unable to load Lithium - zip END header not found

### ISSUE THREAD

**Issue by mrmcderm** [jellysquid3/Lithium#530]
### Version

1.21-0.12.7

### Reproduction Steps

With the Fabric API, GeyserMC, and Floodgate mods, attempt to start Minecraft server with 7G of RAM, received an error: Incompatible mods found!

Mod discovery failed!

java.util.zip.ZipException: zip END header not found

See logs linked below for detailed stack trace

### Crash Report File

[https://mclo.gs/nhn0ZTk](https://mclo.gs/nhn0ZTk)

### Additional Information

OS: Ubuntu 20.04.6 LTS
Java: OpenJDK 21.0.3 2024-04-16
Minecraft: 1.21
Fabric Loader: 0.15.11
Fabric API: 0.100.4+1.21
GeyserMC: 2.4.0
Floodgate: 2.2.3

Additionally, I removed all jar files from the mods folder except Lithium and received the same error.

**Comment by jellysquid3** [comment]
The JAR file is corrupt. This is not a problem with Lithium. Download the mod from [Modrinth](https://modrinth.com/mod/lithium) again and make sure it's downloaded completely.

**Comment by mrmcderm** [comment]
Getting it from modrinth did the trick.  I was originally grabbing it from curseforge.
