### ISSUE TITLE
1.21 Boat stacking glitch

### ISSUE THREAD

**Issue by jackie4289** [jellysquid3/Lithium#532]
### Version Information
lithium-fabric-mc1.21-0.12.7 - INSTALLED ON SERVER ONLY

### Expected Behavior
Top boat should stay on top of the hitbox of bottom boat

### Actual Behavior
Top boat slides off bottom boat 

### Reproduction Steps
After server restart or when server inactive for a while. (Tested with only lithium mod in server and other mods in server below)
Issue is solved after deleting the mod from server. Also tried with vanilla fabric server. 
update: tried using ModernFix mod. SAME ISSUE. For now, only ferritecore mod does not affect the issue. 

### Other Information
other mods in server: 
![image](https://github.com/user-attachments/assets/bd538e15-fcd9-46d3-829a-e453b4ce17de)

How boats are stacked: 
![image](https://github.com/user-attachments/assets/50a32234-103d-4e03-baf8-bfb65621664b)

Based on this farm: https://www.youtube.com/watch?v=sT4noYO1xUE

**Comment by 2No2Name** [comment]
Cannot reproduce (without other mods). Can you give more detailed steps?

**Comment by 2No2Name** [comment]
Any testing / providing more info would be helpful

**Comment by jackie4289** [comment]
> Any testing / providing more info would be helpful

Hi, this is probably a fabric issue. But heres a video of what i mean by how it slides off the boat. https://cdn.discordapp.com/attachments/699511817696706642/1262918035682103296/Untitled.mov?ex=66985793&is=66970613&hm=2b249e800312199f8fe5bd85bb3efa7cf871d4773b05dda76c5bb4341fe4dfde&
