### ISSUE TITLE
Crash caused by Lithium passing invalid value to method.

### ISSUE THREAD

**Issue by Gamemassa** [jellysquid3/Lithium#533]
### Version

> Minecraft 1.21
> Fabric Loader 0.16.0
> Fabric API 0.100.6
> Example: lithium-fabric-mc1.21-0.12.7

### Reproduction Steps

> Load up an existing SP world or try to create a new one with both Lithium and Fuzs' Permanent Sponges mod (other mods may also be causing Lithium to do this but I experienced it with Permanent Sponges). I sent the crash report and latest.log to Fuzs (link to that thread below), and he looked and said it appears that Lithium is passing a `null` block position value to a method that is expecting a non-null value.

### Crash Report File

> Crash Report:
> https://mclo.gs/ECZZ0NK

> Latest.log
> https://mclo.gs/HbYdUCr

### Additional Information

> https://github.com/Fuzss/permanentsponges/issues/5

**Comment by 2No2Name** [comment]
Add the line `mixin.block.fluid.flow = false` to lithium.properties in the config folder as a workaround. This is a mod incompatibility issue with permanentsponges

**Comment by 2No2Name** [comment]
Recommend to use this https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json to disable the fluid flow optimization from the permanentsponges mod

**Comment by 2No2Name** [comment]
Should be fixed since the latest release
