### ISSUE TITLE
Hopper optimization support for Gloppers!

### ISSUE THREAD

**Issue by sternschnaube** [jellysquid3/Lithium#539]
https://modrinth.com/mod/gloppers

Would it be possible to keep "mixin.block.hopper=true" to have the best of both worlds?

**Comment by 2No2Name** [comment]
I don't think it is feasible, maybe I will look into it eventually.

But you can give this link https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json to the author

**Comment by sternschnaube** [comment]
Thanks, I will let her know 😊
