### ISSUE TITLE
Lithium causes elytra flight take off to fail.

### ISSUE THREAD

**Issue by MarkHarrisMedia** [jellysquid3/Lithium#540]
Issue with easy elytra take off. Elytra fight fails on both mobile and pc after installing lithium.
------------------------

### Version Information

[lithium-fabric-mc1.21-0.12.7.jar](https://cdn.modrinth.com/data/gvQqBUqZ/versions/my7uONjU/lithium-fabric-mc1.21-0.12.7.jar)

### Expected Behavior

Easy elytra take off

### Actual Behavior

The character just gets thrown from fireworks without elytra engaging. Lithium caused elytra to not start and fail a take off.

### Reproduction Steps

Elytra take off using fireworks

### Other Information

Testing this in both my suvival and creative server, the same issue presented itself, caused by Lithium. It was fixed after removing the mod.

**Comment by 2No2Name** [comment]
Closing as this cannot be reproduced. If this is a mod compatibility issue, please post the list of mods
