### ISSUE TITLE
Wilder Wild Mesoglea Incompatibility

### ISSUE THREAD

**Issue by AViewFromTheTop** [jellysquid3/Lithium#541]
In Wilder Wild, there is a block called Mesoglea that acts as a static block of Water when waterlogged. When inside, there is a mixin to make "clipping" ignore other waterlogged Mesoglea blocks.
Lithium gets rid of this behavior, making the player target the Mesoglea block they're inside instead of whatever block they'd usually target.

Any help on how to fix this on our side (if possible) would be greatly appreciated as well.

Mixin: https://github.com/FrozenBlock/WilderWild/blob/master/src/main/java/net/frozenblock/wilderwild/mixin/block/mesoglea/BlockGetterMixin.java

**Comment by AViewFromTheTop** [comment]
Hey, have there been any updates on this?

**Comment by 2No2Name** [comment]
Possible workaround: Try adding the `mixin.world.raycast=false` to the lithium.properties file in the config folder.

**Comment by AViewFromTheTop** [comment]
> Possible workaround: Try adding the `mixin.world.raycast=false` to the lithium.properties file in the config folder.

Is there a way to disable this from Wilder Wild itself? I’d really prefer if it were working for everyone who downloaded it

**Comment by 2No2Name** [comment]
There is this https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json but the wiki page has not yet been updated for neoforge

**Comment by 2No2Name** [comment]
One of these two should work (add to the toml), I haven't tested which one. Please report back if you try, so I can update the wiki. @AViewFromTheTop 
[mods."lithium:options"]
"mixin.world.raycast" = false

["lithium:options"]
"mixin.world.raycast" = false

**Comment by JaceTheGrayOne** [comment]
> One of these two should work (add to the toml), I haven't tested which one. Please report back if you try, so I can update the wiki. @AViewFromTheTop [mods."lithium:options"] "mixin.world.raycast" = false
> 
> ["lithium:options"] "mixin.world.raycast" = false

Well the first one doesn't work. Same for the second one.

`[14:35:37] [main/WARN]: No configuration key exists with name '[mods."lithium', ignoring
[14:35:37] [main/WARN]: No configuration key exists with name '"mixin.world.raycast"', ignoring`

**Comment by AViewFromTheTop** [comment]
> There is this https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric-mod.json but the wiki page has not yet been updated for neoforge

WW's still Fabric-only at the moment, so that one should work
Thank you so much!!
