### ISSUE TITLE
Game crashes with Bootstrap error

### ISSUE THREAD

**Issue by JesseHoydonckx** [jellysquid3/Lithium#544]
### Latest lithium and carpet version causing a crash on startup ###

------------------------

### Version

- lithium-fabric-mc1.21-0.13.0
- fabric-carpet-1.21-1.4.147+v240613

### Reproduction Steps

Start the game with  both mods in the mods folder.

### Crash Report File

[crash-2024-08-12_12.57.33-client.txt](https://github.com/user-attachments/files/16580748/crash-2024-08-12_12.57.33-client.txt)

### Additional Information

Either mod works fine without the other, but when both are in the mods folder the game refuses to start.
Works fine with older 1,21 lithium version (lithium-fabric-mc1.21-0.12.7).

**Comment by TheRonGDD** [comment]
Seeing the same on MC 1.21.1. 

Reverted back to lithium-fabric-mc1.21-0.12.7 and edited fabric.mod.json as a temp fix. Server seems stable for now.

Better option though...
https://github.com/CaffeineMC/lithium-fabric/issues/543#issuecomment-2282893674

**Comment by Heitzenberg** [comment]
https://github.com/CaffeineMC/lithium-fabric/issues/543
