### ISSUE TITLE
GUI Bug

### ISSUE THREAD

**Issue by Joshua1056** [jellysquid3/Lithium#547]
### Version Information

> mc1.21-0.13.0 on fabric alongside sodium.

### Expected Behavior

> The buy me a coffee and shaders button should be seperate.

### Actual Behavior

> The buy me a coffee button conflicts with the shaders button.

### Reproduction Steps

>Install sodium and the stated version of lithium.
> Open video settings
> Look on the top bar

### Other Information

> Sodium extra, Indium, other mods that i think would not conflict with video settings gui.

**Comment by Joshua1056** [comment]
The reason i put this bug here is because the buy me a coffee button linked to the owner of this mod's link.

**Comment by 2No2Name** [comment]
This is not relevant for lithium, report to sodium instead
