### ISSUE TITLE
Crash with carpet (1.21.1)

### ISSUE THREAD

**Issue by ninjaguardian** [jellysquid3/Lithium#557]
### Version
lithium-fabric-mc1.21.1-0.13.0
### Reproduction Steps

1. Get [fabric-carpet-1.21-1.4.147+v240613](https://github.com/gnembon/fabric-carpet/releases/download/1.4.147/fabric-carpet-1.21-1.4.147+v240613.jar)
2. Launch
3. Crash

### Crash Report File

https://mclo.gs/a33rZg3

**Comment by MeeniMc** [comment]
Look at #521 there is a linked PR on carpet, following from there you can obtain a patched carpet in the actions from the PR

**Comment by 2No2Name** [comment]
There is also a fix on lithium's side now
