### ISSUE TITLE
Latest version of performant(?) causing a crash with lithium while initializing

### ISSUE THREAD

**Issue by Megra** [jellysquid3/Lithium#560]
Version = lithium 0.11.2 Fabric 

Reproduction Steps
>Start the server
>crashes

latest.log= https://mclo.gs/TmXUawC
Crash report = https://mclo.gs/TZU1dCN

Additional Information
The issue seems to be caused by the latest performant version as no performant or an older version of the mod doesnt result in a crash

disabling the mixin entity fast retrieval also fixes the crash

**Comment by Timolino456** [comment]
The incompatibility is listed on [Performant's mod page](https://www.curseforge.com/minecraft/mc-mods/performant) under "Compatibility". There is probably no other option (for now at least) than disabling the mixin as you said or disabling either Lithium or Performant.

**Comment by jellysquid3** [comment]
Not going to fix this. Performant is closed source, and their authors have wrongly accused us in the past of stealing their code, among other things.
