### ISSUE TITLE
NullPointerException in Lithium Mod During Item Entity Stack Swap

### ISSUE THREAD

**Issue by ByteSizeJoker** [jellysquid3/Lithium#561]
### **Version Information**
- Minecraft: 1.20.6
- Fabric Loader: 0.16.2
- Fabric API: 0.100.4
- Lithium: 0.12.5 for MC 1.20.6

### **Crash Report Files**
- [Crash log 1](https://github.com/user-attachments/files/16918196/Crash_log1.txt)
- [Crash log 2](https://github.com/user-attachments/files/16918197/Crash_log.txt)

### **Steps to Reproduce the Issue**
1. Place a hopper minecart with a repeating command block on top of it to facilitate item retrieval.
2. Configure the repeating command block to summon items.
3. The game crashes approximately 5 seconds after performing these actions.

### **Update**

**Note: This Issues exits only if "mixin.experimental" is set to true in lithium.properties**

This bug exists only on Lithium: 0.12.3 to 0.12.35 for MC **1.20.6**.

Tested on:

- Lithium: 0.13.0 and above (Fixed)
- Lithium: 0.12.3, 0.12.4, 0.12.5 (Bug present)

### **How to fix**

1. Go to `C:\Users\(userName)\AppData\Roaming\.minecraft\config\lithium.properties`
     Note: (Replace (userName) with your user name)
2. Remove  "mixin.experimental" or change its value to false

**Comment by 2No2Name** [comment]
Are you using mixin.experimental=true ?

**Comment by ByteSizeJoker** [comment]
Yep

**Comment by ByteSizeJoker** [comment]
> Are you using mixin.experimental=true ?

Yep

**Comment by 2No2Name** [comment]
Don't.

Marking as invalid as this is already fixed versions
