### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [jellysquid3/Lithium#564]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

Might sound stupid to ask this for such a large and widely used mod, but I do it anyway.

**Comment by douira** [comment]
By uploading mods to modrinth, permission is given to use that mod as part of a modpack. See [this help page](https://support.modrinth.com/en/articles/8797527-obtaining-modpack-permissions). Furthermore lithium is licensed as LGPLv3 which means you're allowed to redistribute it as part of a modpack under the license terms.
