### ISSUE TITLE
neoforge 1.21.1 crash on launch with newest snapshot

### ISSUE THREAD

**Issue by VaporeonScripts** [jellysquid3/Lithium#569]
- Have you used the search tool to find similar issues? Make sure you are not opening a duplicate.
- they dont exist, im the first :smile: 
- Are you using the latest version of the mod? If not, try updating to see if it resolves your issue.
- yes

------------------------

### Version Information

neoforge 1.21.1
> 
> latest and only existent lithium version

### Expected Behavior

expected to work

### Actual Behavior

crash on launch

### Reproduction Steps

add the mod,crash

### Other Information

https://mclo.gs/2MyYH4B

**Comment by douira** [comment]
appears to be a conflict of something with ferrite core, unsure if related to lithium
> java.lang.UnsupportedOperationException: A mod tried to access the state neighbor table directly. Please report this at https://github.com/malte0811/FerriteCore/issues

**Comment by VaporeonScripts** [comment]
so its an incompatibility between lithium and ferritecore?

**Comment by douira** [comment]
If it doesn't happen with everything except ferrite core, and also not with everything except lithium that would point to an conflict between the two.

**Comment by VaporeonScripts** [comment]
well this crash only happens if i add lithium to my mods folder,along with ferrite core

**Comment by VaporeonScripts** [comment]
ima see if ferrite core owner can do something about it

**Comment by 2No2Name** [comment]
Can you try using the latest actions build from FerriteCore? Malte seems to have fixed it already.

https://github.com/malte0811/FerriteCore/actions/runs/11371242578
The mod jar is in the build-artifacts.

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/issues/570 Is the same issue
