### ISSUE TITLE
Update to 1.16 pre8. This is VERY far behind.

### ISSUE THREAD

**Issue by MagmaSlime123** [jellysquid3/Lithium#57]
### Reproduction Steps
Use the mod...

### Crash Report File
Please upload your crash report as a file to [GitHub Gist](https://gist.github.com/) and replace this text with a link to the uploaded report.
No errors are given. I'm simply given the usual Fabric The game crashed window, so no point.

### Additional Information
Provide any additional information or context which may be relevant to the issue. If you have none to add, you can remove this section.
N/A.

**Comment by jellysquid3** [comment]
Stop spamming my issue trackers with update requests. You will be banned the next time it happens.
