### ISSUE TITLE
[Neoforge] Lithium is incompatible with ferritecore

### ISSUE THREAD

**Issue by lzm11111111** [jellysquid3/Lithium#570]
#### Instructions

When have both lithium and ferritecore installed, the game crash at startup

------------------------

### Version
1.21.1 neoforge 21.1.71

### Modlist:
 lithium-neoforge-0.14.0-snapshot+mc1.21.1-build.88
 ferritecore-7.0.0-neoforge (2).jar

### Reproduction Steps

 1. Installing lithium and ferritecore on neoforge client
 2. Launch the game
 3. Crash

### Crash Report File

[crash-2024-10-18_18.24.55-client.txt](https://github.com/user-attachments/files/17433862/crash-2024-10-18_18.24.55-client.txt)

### Minecraft Save

 If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

**Comment by 2No2Name** [comment]
Can you try using the latest actions build from FerriteCore? Malte seems to have fixed it already.

https://github.com/malte0811/FerriteCore/actions/runs/11371242578
The mod jar is in the build-artifacts.

**Comment by 2No2Name** [comment]
Related issue on ferritecore: https://github.com/malte0811/FerriteCore/issues/175
