### ISSUE TITLE
[NeoForge][1.21.1]Crash when opening AE2 guide page

### ISSUE THREAD

**Issue by YuezhangWang** [jellysquid3/Lithium#573]
Actually, Radium already fixed this problem, here is the [issue](https://github.com/Reforged-Hub/radium-upstream/issues/41) and the [commit](https://github.com/Reforged-Hub/radium-upstream/commit/4994e83e3377f127bf3b118fb85719d3ec7b8992). That might be a reference.

### Version
lithium-neoforge-mc1.21.1-0.14.0
neoforge: 21.1.72

### Reproduction Steps
1. Open a world with both Lithium and AE2
2. open AE2's guide(either with the guide item, or by holding G on any AE2 item)
3. flip through the pages until you crash (not all pages crash)
4. actually, there is same problem for mods using AE2's guide book like ExtendedAE and AdvancedAE.

### Crash Report File
[view on Gist](https://gist.github.com/YuezhangWang/823ecffb1e2dbfda7e99892341c0a6a1)
[file](https://github.com/user-attachments/files/17528797/crash-2024-10-26_11.01.30-client.txt)

### Additional Information
Actually, Radium already fixed this problem, here is the [issue](https://github.com/Reforged-Hub/radium-upstream/issues/41) and the [commit](https://github.com/Reforged-Hub/radium-upstream/commit/4994e83e3377f127bf3b118fb85719d3ec7b8992). That might be a reference.

**Comment by Desempregago** [comment]
The problem lies specifically in any section that renders cables, I've just had this a few times.
