### ISSUE TITLE
1.21.3 build is not on jitpack

### ISSUE THREAD

**Issue by MCBEModder2020** [jellysquid3/Lithium#579]
self explanitory
https://jitpack.io/com/github/CaffeineMC/lithium-fabric/mc1.21.3-0.14.1/build.log

**Comment by jellysquid3** [comment]
Do not use JitPack. It is unreliable and buggy. Use the [Modrinth Maven](https://support.modrinth.com/en/articles/8801191-modrinth-maven) instead.
