### ISSUE TITLE
Lithium Warnings

### ISSUE THREAD

**Issue by giuliotoplad** [jellysquid3/Lithium#584]
**Description:**
I updated my Minecraft Fabric Server from 1.21.1 to 1.21.3 and every time I start It a lot of warnings appears on the console.
I checked if there's some anomalies in game but everything seems to work just fine.
I'm not completely sure if this depends only from Lithium or Fabric too.

**Technical Details (all mods used on the Server linked here):**
Fabric Loader: 0.16.9
Fabric API: 0.108.0+1.21.3
Lithium: 0.14.1-snapshot+mc1.21.3-build.89
Java Version: 21

**Full Log:**
https://pastebin.com/EuVsYfe2

**Comment by 2No2Name** [comment]
The warnings should probably be INFO level instead. In the latest release some optimizations are disabled by default, because they have issues.

**Comment by giuliotoplad** [comment]
> The warnings should probably be INFO level instead. In the latest release some optimizations are disabled by default, because they have issues.

Okey, then It's good to know that there's nothing to worry about.
If Lithium get updated and those warnings will disappear then I will close this issue post or you can close it too, thank you for the answer.

**Comment by 2No2Name** [comment]
Changed the warnings to info level
