### ISSUE TITLE
Minecart is shaking on a 1.21.3 Server with experimental minecart datapack open.

### ISSUE THREAD

**Issue by CelestialSayuki** [jellysquid3/Lithium#585]
### Version Information

> lithium-fabric-0.14.1-snapshot+mc1.21.3-build.89

### Expected Behavior

> The minecart should move on a ascending/descending rail smoothly.

### Actual Behavior

> Example: The minecart is shaking.

### Reproduction Steps

> 1. Enable the experimental minecart datapack.
> 2. Put minecart on a descending/ascending rail.
> 3. The movement is strange.

### Other Information

https://github.com/user-attachments/assets/24157c46-644b-473e-a723-db181ed67fbe

**Comment by 2No2Name** [comment]
Should be fixed by https://github.com/CaffeineMC/lithium-fabric/commit/fa9864dc30b03d5dca71aeaf498c15a519d82ce8
