### ISSUE TITLE
NeoForge's Creative Flight API doesn't work anymore with Lithium Installed

### ISSUE THREAD

**Issue by Leclowndu93150** [jellysquid3/Lithium#587]
NeoForge 21.1.79
Modular Angel Ring 1.5.1 (Curseforge)
Curios API Continuation 9.0.15 (Curseforge)
Lithium 0.14.0

i can't fly anymore using the angel ring when Lithium is installed, this issue doesn't happen only with my mod but other mods aswell

https://github.com/Leclowndu93150/Modular-Angel-Ring/blob/main/src/main/java/com/leclowndu93150/modular_angelring/common/AngelRingItem.java

here you can see how creative flight is handeled

**Comment by 2No2Name** [comment]
It is unclear why this is happening. Can you try with 0.14.2 ?

**Comment by Leclowndu93150** [comment]
![Uploading 2024-11-17_22.32.00.png…]()
can't fly

**Comment by Leclowndu93150** [comment]
![2024-11-17_22 32 00](https://github.com/user-attachments/assets/537c8951-e09f-4ae7-965e-4d8b18998ca1)
can't fly

**Comment by 2No2Name** [comment]
My best guess is to try with `mixin.entity.equipment_tracking=false` in the lithium.properties file in the config folder. If that doesn't work, I will have to check with the debugger

**Comment by Leclowndu93150** [comment]
I'll try in an hour

**Comment by Leclowndu93150** [comment]
that didn't fix it

**Comment by Vartis** [comment]
Seems to break all flying in Modern Industrialization as well. 
MI version : Modern-Industrialization-2.2.25
Lithium version: lithium-neoforge-0.14.2-snapshot+mc1.21.1-build.90.jar
Probably the same issue as #591 #540 .

**Comment by 2No2Name** [comment]
Maybe try `mixin.entity.fast_elytra_check=false` in the lithium.properties file in the config folder

**Comment by Vartis** [comment]
> Maybe try `mixin.entity.fast_elytra_check=false` in the lithium.properties file in the config folder

No change.

**Comment by 2No2Name** [comment]
Okay running in the debugger now to find out why this happens

**Comment by Vartis** [comment]
If it helps. 
Minecraft : 1.21.1
Neoforge : 21.1.80
Sodium : sodium-neoforge-0.6.0+mc1.21.1
Modern Industrialization : Modern-Industrialization-2.2.25
Cloth config : cloth-config-15.0.140-neoforge (_dependency for MI_)
Lithium : lithium-neoforge-0.14.2-snapshot+mc1.21.1-build.90

Grav chest plate and quantum chest plate both give creative style flight and no longer work. The jetpack however does continue to work since it is a different style of flying.

**Comment by 2No2Name** [comment]
Seems to be fixed by adding the line
`mixin.collections.attributes=false` to the lithium.properties file in the config folder.
