### ISSUE TITLE
lithium-fabric on fabric-server-mc.1.21.3-loader.0.16.9-launcher.1.0.1.jar throws some warnings

### ISSUE THREAD

**Issue by 4shpool** [jellysquid3/Lithium#588]
### Version Information
lithium-fabric-0.14.2-snapshot+mc1.21.3-build.91.jar

### Expected Behavior
launching the fabric server without warnings (as for fabric 1.21.3 without lithium ([log](https://pastebin.com/Ybfm8BQ9)))

### Actual Behavior
launching the fabric 1.21.3 server with above lithium added as a mod throws formerly unknown warnings ([log](https://pastebin.com/WLf5zbex))

### Reproduction Steps
launch a fresh instalment of fabric-server 1.21.3 together with just fabric-api and lithium as added mods

### Other Information
Haven't faced such warnings before and botched my 'search-engine'-fu for them, I am curious/interested in any information about the implications and meanings of encountered warnings/infos and whether I may simply ignore them for updating "_my server/our world-(1.21.1)_" or wait for a warning-free lithium version before doing so.

**Comment by 2No2Name** [comment]
The warnings shouldn't occur and will be removed in a future release. They should not cause any issues right now.

**Comment by 2No2Name** [comment]
The relevant warnings are

`[23:48:48] [main/WARN]: Reference map 'lithium.refmap.json' for lithium.mixins.json could not be read. If this is a development environment you can ignore this message
[23:48:48] [main/WARN]: Reference map 'lithium-fabric.refmap.json' for lithium-fabric.mixins.json could not be read. If this is a development environment you can ignore this message`

**Comment by 2No2Name** [comment]
Probably removed by https://github.com/CaffeineMC/lithium-fabric/commit/3c03b95e61d4cf70718a44cc52b3a01e3031ba41
