### ISSUE TITLE
lithium makes productive bees bees and nests unable to spawn

### ISSUE THREAD

**Issue by VaporeonScripts** [jellysquid3/Lithium#589]
latest version of lithium
neoforge 1.21.1 .80
arch linux OS
https://mclo.gs/A9bKS1h

**Comment by 2No2Name** [comment]
The issue seems to be that they are returning the wrong block entity type when calling BlockEntity::getType() during block entity initialization. Lithium uses the method very early to check whether the block at the position supports the block entity.

**Comment by 2No2Name** [comment]
Marking as external as I think the other mod is violating a very reasonable assumption, i.e. that the block entity type of a block entity is correct from the start.

**Comment by VaporeonScripts** [comment]
Aight,ima let U guys find a solution between productive bees and lithium,as I saw on productive bees part

**Comment by 2No2Name** [comment]
The solution is to disable the optimization

**Comment by VaporeonScripts** [comment]
which one specifically?

**Comment by VaporeonScripts** [comment]
?

**Comment by 2No2Name** [comment]
Workaround is to add the line 
`mixin.minimal_nonvanilla.world.block_entity_ticking.support_cache=false`
to the lithium.properties file in the config folder and restarting the game.
There should not be lasting damage to your world, since the beehives just weren't ticked when the issue occurred.

**Comment by VaporeonScripts** [comment]
I disabled another one and it worked? Lemme show

**Comment by VaporeonScripts** [comment]
mixin.world.block_entity_ticking=false

**Comment by 2No2Name** [comment]
Yes, the support_cache optimization depends on the general block entity ticking optimization. But disabling that also disables a few other optimizations that might not have a problem

**Comment by VaporeonScripts** [comment]
So would be better to disable cache one? So that it fixes the issue while improving perf?

**Comment by 2No2Name** [comment]
Yes

**Comment by VaporeonScripts** [comment]
aight,ty

**Comment by 2No2Name** [comment]
It seems like the issue may be fixed in the future by productive bees mod authors, will check again in a while.

**Comment by VaporeonScripts** [comment]
it got fixed, does this mean i can remove this line?
mixin.minimal_nonvanilla.world.block_entity_ticking.support_cache=false

**Comment by 2No2Name** [comment]
Yes, if there is a new issue, please make another bug report

**Comment by 2No2Name** [comment]
Fix on productive bees side (untested so far, but very plausible fix)
