### ISSUE TITLE
unable to generate mss structures

### ISSUE THREAD

**Issue by VaporeonScripts** [jellysquid3/Lithium#590]
neoforge 1.21.1 .80
arch linux
latest lithium

https://mclo.gs/rRRS56k

**Comment by VaporeonScripts** [comment]
what do i need to disable to make it work?

**Comment by VaporeonScripts** [comment]
https://mclo.gs/YV12Fyr

**Comment by 2No2Name** [comment]
Untested workaround:
Add the line 
`mixin.alloc.nbt=false`
to the lithium.properties file in the config folder and restart the game.
Please reply whether this works around the issue

**Comment by VaporeonScripts** [comment]
will see ig

**Comment by VaporeonScripts** [comment]
added, will test tomorrow with my server,cuz rn i cant

**Comment by 2No2Name** [comment]
@VaporeonScripts Did you get around to testing it?

**Comment by VaporeonScripts** [comment]
Seems to work for now,I'll see more later

**Comment by VaporeonScripts** [comment]
the issue is not fixed:

https://mclo.gs/F1qTill

**Comment by VaporeonScripts** [comment]
https://mclo.gs/nwlw7xZ

**Comment by 2No2Name** [comment]
Does the issue occur when you remove lithium entirely?

**Comment by VaporeonScripts** [comment]
idk, i will need to test

**Comment by VaporeonScripts** [comment]
without lithium, it still gives that error, altough it says mixin by kubejs(what)
