### ISSUE TITLE
Reliquary Reincarnations flight effect is not working.

### ISSUE THREAD

**Issue by BlackRiceXY** [jellysquid3/Lithium#591]
### Version Information

>Lithium 0.14.2 for Neoforge

### Expected Behavior

>Double-tap to fly

### Actual Behavior

>Double-tapping only makes the character jump.

### Reproduction Steps

> In ATM10, the flight effect from the Reliquary Reincarnations mod's potion does not trigger, meaning double-tapping space to fly does not work.

### Other Information

> atm10 1.24

**Comment by 2No2Name** [comment]
The other issue to be fixed by adding the line
`mixin.collections.attributes=false` to the lithium.properties file in the config folder.

If this fixes the issue, this issue is a duplicate of #587

**Comment by BlackRiceXY** [comment]
The problem is solved
