### ISSUE TITLE
[NEOFORGE][1.21.1] mouseClicked event handler crash in guide menu (applied energistics 2)

### ISSUE THREAD

**Issue by RatGames212121** [jellysquid3/Lithium#593]
### Version Information
neoforge lithium 0.14.2 (mc1.21.1-0.14.2)

### Expected Behavior

should open guide menu

### Actual Behavior

crash, some tabs not working (most)
### Reproduction Steps

in video
https://github.com/user-attachments/assets/7a0faecc-8c3d-4241-b70e-fbc8f0aa339b
>
### Other Information

people from applied energistics 2 github says it was lithium, and... i'm here 
[crash-2024-11-24_20.09.43-client (1).txt](https://github.com/user-attachments/files/17906846/crash-2024-11-24_20.09.43-client.1.txt)

**Comment by RatGames212121** [comment]
Can please explain what i need to do with it (i'm not very smart)

**Comment by RatGames212121** [comment]
I think, I need to decompile mod file, or what i need?

**Comment by RatGames212121** [comment]
I'm on correct way, but how i can redact file?

**Comment by 2No2Name** [comment]
You can either wait for the next lithium release or download the current latest action build's artifacts and use the neoforge jar from inside the zip file. https://github.com/CaffeineMC/lithium-fabric/actions/runs/12021620323 (not the api jar)

**Comment by RatGames212121** [comment]
help please, i understood what i need to do with it, but he crash, and THIS i don't understood 
Caused by: java.lang.ClassNotFoundException: The specified mixin 'net.caffeinemc.mods.lithium.mixin.ai.pathing.BlockStateBaseMixin' was not found
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1314) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:857) ~[sponge-mixin-0.15.2+mixin.0.8.7.jar:0.15.2+mixin.0.8.7]
... 33 more

**Comment by RatGames212121** [comment]
ah, ok

**Comment by RatGames212121** [comment]
THAAAAANK YOUUUU )))))
