### ISSUE TITLE
Incompatible with modded POI Type registrations on Neoforge

### ISSUE THREAD

**Issue by lostmyself8** [jellysquid3/Lithium#594]
### Version Information

> lithium-neoforge-mc1.21.1-0.14.2

### Expected Behavior

> Villagers in other mods(for example, AE2, ie, and PneumaticCraft) should receive their professions.
> Work blocks(other mods) should be able to be placed in the trader of [Simple-Villagers](https://github.com/henkelmax/easy-villagers).

### Actual Behavior

> Villagers in other mods cannot receive professions.
> I cannot put work blocks(other mods) into the trader of [Simple-Villagers](https://github.com/henkelmax/easy-villagers).

### Reproduction Steps

> Load lithium and other mods, such as AE2, and then place charger and villagers,and you will find that they will not receive work block.

### Other Information

> Forgive me for using translation software.

**Comment by 2No2Name** [comment]
Possibly related to https://github.com/CaffeineMC/lithium-fabric/issues/582

**Comment by 2No2Name** [comment]
Workaround:
Add the line
`mixin.ai.poi=false`
to the lithium.properties file in the config folder and restart the game.

**Comment by 2No2Name** [comment]
This didn't have anything to do with simple-villagers, but just lithium and neoforge's poi registration technique

**Comment by lostmyself8** [comment]
Thank you for your answer. It is indeed useful.
But after the change, the villagers' transactions became chaotic
![2024-11-28_15 53 27](https://github.com/user-attachments/assets/19a9a2d9-b757-4520-9ca7-c126f71ba598)

**Comment by 2No2Name** [comment]
Which block is needed to get a machinist trader in your screenshot

**Comment by lostmyself8** [comment]
Engineer's Circuit Workbench from Immersive Engineering

**Comment by lostmyself8** [comment]
Oh, I searched and it seems to be an issue with immersion engineering. Sorry

**Comment by 2No2Name** [comment]
Probably referring to https://github.com/BluSunrize/ImmersiveEngineering/issues/6109
