### ISSUE TITLE
LittleTiles compatibility

### ISSUE THREAD

**Issue by CreativeMD** [jellysquid3/Lithium#599]
Hey there,

I'm the author of LittleTiles and there are issues between our mods. I do some changes to the `Shapes` class in order to optimize performance. I do that in a way it should not affect other mods, as I only add a hook and change behavior for shape classes added by LittleTiles. Unfortunately this still breaks compatibility with lithium.

This can be solved by disabling these two features `mixin.shapes.specialized_shapes` and `mixin.entity.collisions`. The question if there is an easy way for me to set these two settings to false. Another option could also be for you to check whether LittleTiles is installed to disable these two features in question.

Let me know what you think about it.

In Regards
CreativeMD

**Comment by IThundxr** [comment]
https://github.com/CaffeineMC/lithium-fabric/wiki/Disabling-Lithium's-Mixins-using-your-mod's-fabric.mod.json-or-neoforge.mods.toml

**Comment by CreativeMD** [comment]
Thanks a lot!
