### ISSUE TITLE
Discord Link not working

### ISSUE THREAD

**Issue by Dravere** [jellysquid3/Lithium#604]
On Modrinth you have a Discord Invite Link pointing to https://caffeinemc.net/discord. My browser says it can't connect to that URL.

Here on GitHub in the Readme it links to https://jellysquid.me/discord, but it has the same issue.

Does the Discord no longer exist? Then it perhaps should be removed. Otherwise it might be a good idea to have the same link everywhere as well as a working one 😄

**Comment by 2No2Name** [comment]
It is fixed now
