### ISSUE TITLE
Crash with Vexes and Carpet mod

### ISSUE THREAD

**Issue by James103** [jellysquid3/Lithium#68]
### Mods and versions used
Minecraft 1.16.1
Fabric 0.8.9+build.203
Lithium 0.5.0-rc1
(Carpet Mod 1.4.0)
(Fabric API 0.14.1+build.372)
(Not Enough Crashes 1.2.4+20w17a)

### Reproduction Steps
1. Create a new Superflat world. Use the Void preset for best performance.
2. Set your spawn point where you initially spawn (`/spawnpoint`).
3. Summon 5 evokers (`/summon evoker` x5). You can instead activate a repeating command block with the command `/summon vex ~ ~ ~ {LifeTicks:20}`.
4. Give yourself max healing (`/effect give @p instant_health 1000000 22`).
5. Switch gamemode to survival.
6. If Carpet mod is installed, fast-forward the game with `/tick warp 72000`.
7. The server will crash after a few minutes.
8. If Not Enough Crashes is installed, click through the crash screen.
9. The game will exit to the multiplayer menu with "Internal exception: java.lang.StackOverflowError".

### Crash Report File
https://gist.github.com/James103/e35b958585c3700722edfb700c0d0e8e

### Additional Information
The crash does not occur without Lithium installed, and Not Enough Crashes tells me that Lithium is a possible cause of the above crash.

In my case, the world on which the game crashed is hidden from the world selection screen due to `java.nio.channels.OverlappingFileLockException` until you restart the game entirely.

**Comment by 2No2Name** [comment]
Is there a "Entity <something here> left loaded chunk area" in the log just before the crash?

**Comment by James103** [comment]
I added the corresponding latest.log from a more recent reproduction of the crash. Several hundred lines of sound pool warnings were stripped to reduce the file size.

**Comment by James103** [comment]
Not fixed yet. Game generates additional crash files: [crash-2020-07-25_07.42.22-server.txt](https://github.com/jellysquid3/lithium-fabric/files/4975528/crash-2020-07-25_07.42.22-server.txt)
Same error as above. Reproduced by running the following commands in succession:
`/summon villager ~ ~ ~ {NoAI:1b}`
`/effect give @e[type=villager] resistance 1000000 5`
`/summon evoker`
(if Carpet Mod is installed) `/tick warp 72000`

**Comment by 2No2Name** [comment]
Fixed on the 1.16.x/dev branch. You can either build lithium yourself or wait for the next release. Thank you for reporting this bug. The steps to reproduce were essential, I was able to locate the problem with your help.
