### ISSUE TITLE
OptiFine is incompatible with Lithium

### ISSUE THREAD

**Issue by MaoDoBan** [jellysquid3/Lithium#73]
Mods and versions used:
Minecraft 1.16.1
Fabric 0.8.9+build.203
Lithium 0.5.0-rc1 (default settings)
Fabric API 0.14.1+build.372
Preview_OptiFine_1.16.1_HD_U_G2_pre2 (default settings)
Optifabric-1.1.0-beta2 (default settings)
(Not Enough Crashes 1.2.4+1.16.1)

Reproduction Steps:
1. Singleplayer
2. Create New World (on main menu)
3. Create New World (botton left confirm button)

Crash Report File:
https://gist.github.com/MaoDoBan/fe76263d57013cea043befec20380031

Additional Information:
I have no ideia if this is a Lithium, Optfabric or Optfine problem.

**Comment by amnotbananaama** [comment]
Duplicate of #70 and #72.

**Comment by jellysquid3** [comment]
Optifine is not supported, and recent versions of it with Optifabric are breaking many other Fabric mods.

**Comment by ghost** [comment]
Well...
At least sodium exists.
