### ISSUE TITLE
Creepers aren't afraid of cats (MC 1.16.1, Lithium 0.5.0, Fabric 0.8.9b203)

### ISSUE THREAD

**Issue by chland** [jellysquid3/Lithium#75]
### Expected Behavior
Creepers should run away from cats if they are within 6 blocks of them.

### Actual Behavior
Creepers don't care about cats at all.

### Reproduction Steps
1. Spawn in a creeper
2. Spawn in a cat right next to it
3. Nothing happens

I did search a bit around and found that #13 mentions the same problem, but apparently it was fixed? Also, over on Discord, lucy mentions the same bug 2-3 weeks ago.

**Comment by LucilleTea** [comment]
I can confirm this bug, creepers being scared of cats is completely broken now.

When I mentioned this previously in the discord it was not completely broken, and I found that my farm was equally broken in vanilla. So I think that's unrelated. Here's a link to that report: https://discordapp.com/channels/602796788608401408/648967810139029505/723792245270118482

**Comment by MMK21Hub** [comment]
Oof. Seems pretty major to me.

**Comment by 2No2Name** [comment]
Okay I have located the problem in the code, it was introduced about 2 days ago.

**Comment by chland** [comment]
Thanks for finding/fixing this issue so quickly :)
