### ISSUE TITLE
World generation is different

### ISSUE THREAD

**Issue by Zetsphiron** [jellysquid3/Lithium#78]
### Expected Behavior
Although the mod touches world gen, it is supposed to not affect the way in a way like that.

### Actual Behavior
Worlds generated with this mod on are different from the ones without it/vanilla. The terrain itself generates differently, but other observed effects are more floating islands on the nether, smaller end cities, less connected caves, among other things.

### Reproduction Steps

1. Create a world in vanilla or without a mod, take note of the seed
2. Create another world with the mod on with the same seed as the previous
3. Compare generation results

### Attachments
First on each pair are without Lithium, and the second, with. Seed was 104967040175852735 .
![2020-07-08_12 24 17](https://user-images.githubusercontent.com/68052438/87015405-3954f600-c182-11ea-89a9-6773fa270c9c.png)
![2020-07-08_12 24 58](https://user-images.githubusercontent.com/68052438/87015430-4376f480-c182-11ea-9b09-3ef4870c6edf.png)
![2020-07-08_12 15 13](https://user-images.githubusercontent.com/68052438/87015497-5ab5e200-c182-11ea-88e1-52a4a3134324.png)
![2020-07-08_12 15 41](https://user-images.githubusercontent.com/68052438/87015509-5db0d280-c182-11ea-9476-6c2145904053.png)

**Comment by jellysquid3** [comment]
Lithium 0.5.1 has been released and contains the fix for this issue.
