### ISSUE TITLE
Server crashes without warning or explanation

### ISSUE THREAD

**Issue by The8BitMonkey** [jellysquid3/Lithium#80]
### Reproduction Steps
I don't know how to reproduce this crash as there is no indication as to why it is happening, the server is running fine and then all of the sudden it stops

### Crash Report File
https://gist.github.com/The8BitMonkey/2c5d53fe64d10805b1b720c126b4d0c0

### Additional Information
The server is running Fabric 0.8.9+build.203 with the following mods:
- lithium-fabric-mc1.16.1-0.5.1.jar
- phosphor-fabric-mc1.16.1-0.6.0+build.7.jar

**Comment by amnotbananaama** [comment]
This looks very similar to the error in #68. Do you recall anything that was happening on the server before the crash? Players have reported this error so far when fighting endermen or vexes.

**Comment by The8BitMonkey** [comment]
from the player that was on the server at the time, they said that they where in The End at there Enderman farm, so yeah likely a link to something to do with Endermen.

**Comment by 2No2Name** [comment]
Are you running carpet mod? ( I know you didn't list it, but it might be a really good hint)
Edit: reproduced it without carpet as well now

**Comment by 2No2Name** [comment]
Fixed on the 1.16.x/dev branch. You can either build lithium yourself or wait for the next release. Thank you for reporting this bug.
