### ISSUE TITLE
Spigot support

### ISSUE THREAD

**Issue by AndiLeni** [jellysquid3/Lithium#89]
Hello,
i wanted to ask if there is a way to run Lithium or Phosphor on a spigot/paper-spigot server.

**Comment by LucilleTea** [comment]
Lithium and Phosphor are Fabric mods, they're not available for Spigot or Paper.
The Github issue tracker is intended for bugs, so if you have more questions or discussion they'd be better suited to the [Discord server](https://jellysquid.me/discord)! Thanks.
