### ISSUE TITLE
Crash with ReplayMod

### ISSUE THREAD

**Issue by kesu1** [jellysquid3/Lithium#9]
When starting the mod with Replay Mod in 1.14.4, it doesn't even load to the menu, just says "An unexpected error occured..."

**Comment by silversquirl** [comment]
If you can provide a log, that'd be a big help with diagnosing the issue

**Comment by kesu1** [comment]
[output_log.txt](https://github.com/jellysquid3/Lithium/files/3995243/output_log.txt)

**Comment by jellysquid3** [comment]
This issue is caused by the `client.reduceCuboidTransformations` patch. It's not likely it can ever be resolved without disabling this patch. However, I'm looking into creating a hints system to Lithium so we can detect incompatibilities like this and automatically adjust our configuration.

**Comment by jellysquid3** [comment]
This patch has since been removed in Minecraft 1.15+.
