### ISSUE TITLE
Lithium crashes my game everytime I enter a single-player world?

### ISSUE THREAD

**Issue by KingXigo** [jellysquid3/Lithium#93]
> Everytime I try to enter a single-player world with the Lithium mod, I crash? But when entering a Multiplayer world it works perfectly fine. Sorry, this might sound like someone already reported it but I just can't seem to find the reason for it?

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2020-07-28 13:00:59 CST
Description: Exception in server tick loop

java.lang.IllegalAccessError: tried to access field net.minecraft.class_3898$class_3208.field_18247 from class net.minecraft.class_3898
    at Not Enough Crashes deobfuscated stack trace.(1.15.2+build.17)
    at net.minecraft.server.world.ThreadedAnvilChunkStorage.updateCameraPosition(ThreadedAnvilChunkStorage:2249)
    at net.minecraft.server.world.ServerChunkManager.updateCameraPosition(ServerChunkManager:467)
    at net.minecraft.server.network.ServerPlayNetworkHandler.onPlayerMove(ServerPlayNetworkHandler:867)
    at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket.apply(PlayerMoveC2SPacket:122)
    at net.minecraft.network.packet.c2s.play.PlayerMoveC2SPacket$Both.apply(PlayerMoveC2SPacket:18)
    at net.minecraft.network.NetworkThreadUtils.lambda$checkThreadAndEnqueue$0(NetworkThreadUtils:34)
    at net.minecraft.class_2600$$Lambda$5479/1082886050.run(Unknown Source)
    at net.minecraft.server.ServerTask.run(ServerTask:18)
    at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:172)
    at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:763)
    at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer:154)
    at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:134)
    at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer:745)
    at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:739)
    at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:115)
    at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer:723)
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer:676)
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:256)
    at net.minecraft.server.MinecraftServer$$Lambda$4526/1988560864.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.16.1
  Minecraft Version ID: 1.16.1
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 301586728 bytes (287 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
  CPUs: 4
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  Suspected Mods: Unknown
  Fabric Mods: betterdroppeditems: Better Dropped Items 1.2.0-1.16
               blur: Blur 1.0.6
               boostedbrightness: Boosted Brightness 1.0.0
               clear-skies: Clear Skies 1.3.38
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-config2: Cloth Config v4 4.5.6
               durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.7.2
               fabric: Fabric API 0.13.1+build.370-1.16
               fabric-api-base: Fabric API Base 0.1.3+12a8474c7c
               fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea8667c
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea897c
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308367c
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f7c
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8667c
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d7c
               fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b30537c
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f7c
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.1.3+0d474ec47c
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f96367c
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.0+e16a97747c
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c57c
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.0.0+b0993bc102
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 0.1.10+059ea8667c
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce997c
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d67c
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b7c
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.5+e00ecb5f7c
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.0+da175ad67c
               fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a707c
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c7c
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb87c
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.1+059ea8667c
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.0.1+5a0f9a607c
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d7c
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.7+12a8474c7c
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+534104907c
               fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d77c
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.5+059ea8667c
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.0.1+f362c86e7c
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.5+5a6e8f4c7c
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb87c
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.1.4+5794386e7c
               fabricloader: Fabric Loader 0.9.0+build.204
               gameinfo: GameInfo 1.5.3 1.16
               gbfabrictools: GBfabrictools 1.2.2+1.16
               lithium: Lithium 0.5.1
               loadcatcher: Entrypoint Catcher 2.0.0
               minecraft: Minecraft 1.16.1
               mm: Manningham Mills 2.0
               modmenu: Mod Menu 1.12.2+build.16
               notenoughcrashes: Not Enough Crashes 2.1.0+1.16.1
               optifabric: Optifabric 1.1.0-beta2
               org_slf4j_slf4j-api: slf4j-api 1.7.30
               org_slf4j_slf4j-simple: slf4j-simple 1.7.30
               org_zeroturnaround_zt-zip: zt-zip 1.14
               phosphor: Phosphor 0.6.0+build.7
               satin: Satin 1.4.0-nightly.1.16-pre5+build.1
               smb: Better Mod Button 1.1.0
               voxelmap: VoxelMap 1.10.6
               waila: Hwyla 1.9.22
               worldedit: WorldEdit 7.2.0-beta-02+d10d7d6
  Player Count: 1 / 8; [class_3222['XiG0'/49, l='ServerLevel[Resource Flat Test]', x=-276.78, y=54.12, z=-171.87]]
  Data Packs: vanilla, fabric/fabric-tool-attribute-api-v1
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by ghost** [comment]
optifine isnt supported anymore

**Comment by 2No2Name** [comment]
Optifabric and Lithium are incompatible with each other (see https://github.com/jellysquid3/lithium-fabric/issues/73 ). The solution to your crash is to not use them together.
