### ISSUE TITLE
Crash with towellette

### ISSUE THREAD

**Issue by machinesmith42** [jellysquid3/Lithium#95]
https://hastebin.com/ucemimahit.cs

**Comment by 2No2Name** [comment]
Try setting mixin.shapes.blockstate_cache=false in the lithium config file https://github.com/jellysquid3/lithium-fabric/wiki/Configuration-File . Does that help?

**Comment by 2No2Name** [comment]
The incompatibility should be fixed by the author of towelette now, at least they closed the corresponding issue.
